--[[--------------------------------------------------
002_Durotar.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 001 Introduction
    1.04.1
        -- First Release
            Orcs&Trolls Durotar's Guide
            from level 1 to lever 12
    1.04.2
    	-- no changes in here for this revision
		
	07/06/2019 - Update with most recent Joanna guide (https://www.joanasworld.com/horde-1-12-durotar.html)
------------------------------------------------------
Connection:
--]]--------------------------------------------------


Table_002_Durotar = {
  [0106] = {
    title = "1-6 Valley of Trials (Durotar)",
    items = {
      [1] = { str = "Warlock, Next to the wagon & brown rug, from #NPCRuzan#, accept #GETVile Familiars# (#COORD[43.69]#)."},
      [2] = { str = "West at The Den entrance, turn in #INYour Place In The World# (#COORD[42.68]#), accept #GETCutting Teeth# ."},
      [3] = { str = "Warlock, The goal now is to obtain your Imp ASAP: Grind north in Valley of Trials (to around #COORD[45.57]#, #11 on map) and do #DOVile Familiars# : kill/loot #NPCVile Familiars#. You will be fighting higher lvl mobs, but is definitely doable, just be careful."},
      [4] = { str = "Warlock, Die on purpose to get back to the starting spot and from #NPCRuzan# (#COORD[43.69]#) next to the wagon & brown rug, turn in #INVile Familiars# , accept the next #GETpart#. You can now Summon an Imp!"},
      [5] = { str = "Warlock, Next to you, turn in #INVile Familiars# , accept #GETBurning Blade Medallion# . Make sure you are repaired/resupplied."},
      [6] = { str = "Start doing #DOCutting Teeth# by killing the #NPCMottled Boars# all around the area. Once you hit level 2, go accept #GETSarkoth# (#COORD[40.62]#), then do next step.."},
      [7] = { str = "Go south a bit and do #DOSarkoth# : kill/loot the scorpid #NPCSarkoth# (#COORD[41.67]#)."},
      [8] = { str = "Turn in #INSarkoth# (#COORD[40.62]#, #3 on map), accept the next #GETpart#."},
      [9] = { str = "Make sure #DOCutting Teeth# is complete, then go to The Den entrance and turn in #INCutting Teeth# and #INSarkoth# (#COORD[42.68]#, #2 on map), accept #GETSting of the Scorpid# and WARRIOR: #GETSimple Parchment/Tablet# ] HUNTER: #GETEtched Tablet/Parchment# ] ROGUE: #GETEncrypted Tablet/Parchment# ] PRIEST: #GETHallowed Tablet# ] SHAMAN: #GETRune-Inscribed Tablet/Parchment# ] MAGE: #GETGlyphic Tablet# ] #GETTainted Parchment# ."},
      [10] = { str = "Outside next to the wagon/tent, from the WARRIOR: #NPCWarrior Trainer# (#COORD[43.69]#) turn in #INSimple Parchment/Tablet# ]Outside next to the wagon/tent, from the HUNTER: #NPCHunter Trainer# (#COORD[43.69]#) turn in #INEtched Tablet/Parchment# ]Go half way into the cave and from the ROGUE: #NPCRogue Trainer# (#COORD[41.68]#) turn in #INEncrypted Tablet/Parchment# ]Just outside of the cave on the brown rug, from the PRIEST: #NPCPriest Trainer# (#COORD[42.69]#) turn in #INHallowed Tablet# ]Just outside of the cave on the brown rug, from the SHAMAN: #NPCShaman Trainer# (#COORD[42.69]#) turn in #INRune-Inscribed Tablet/Parchment# ]Just outside of the cave on the brown rug, from the MAGE: #NPCMage Trainer# (#COORD[42.69]#) turn in #INGlyphic Tablet# ]Go all the way back to the end of the cave and from the #NPCWarlock Trainer# (#COORD[41.68]#) turn in #INTainted Parchment# . Also get new spells/abilities from your class trainer."},
      [11] = { str = "N/AJust outside of The Den, next to the wagon, accept #GETVile Familiars# (#COORD[43.69]#)."},
      [12] = { str = "By the cauldron / cooking area, accept #GETGalgar's Cactus Apple Surprise# (#COORD[43.67]#). Make sure you get resupplied here."},
      [13] = { str = "East a bit, accept #GETLazy Peons# (#COORD[45.69]#)."},
      [14] = { str = "Around the starting area, do: #DOGalgar's Cactus Apple Surprise# , #DOSting of the Scorpid# , and #DOLazy Peons# and #DOVile Familiars# . Pick up #ITEMCactus Apples#, kill/loot #NPCScorpid Workers#, use the #ITEMForeman's Blackjack# quest item on the #NPCLazy Peons#. Also work your way to the outside of the cave (#COORD[45.57]#) and kill #NPCVile Familiars#."},
      [15] = { str = "Once everything is done, go turn in #INGalgar's Cactus Apple Surprise# (at the cooking area, #COORD[43.67]#, #9 on map). Make sure you get resupplied."},
      [16] = { str = "In The Den entrance, turn in #INSting of the Scorpid# (#COORD[42.68]#, #2 on map)."},
      [17] = { str = "Shaman, 13)"},
      [18] = { str = "Just outside of The Den, next to the #NPCShaman Trainer# (#COORD[42.69]#), accept #GETCall of Earth# . Also get your level 4 spells/abilities."},
      [19] = { str = "Outside by the wagon, turn in #INVile Familiars# (#COORD[43.69]#, #8 on map), accept #GETBurning Blade Medallion# . Also make sure you get new spells/abilities. The WARRIOR: #NPCWarrior Trainer# (is at #COORD[43.69]# next to the wagon/tent).]The HUNTER: #NPCHunter Trainer# is right next to you on the rug (#COORD[43.69]#).]The ROGUE: #NPCRogue Trainer# (is at #COORD[41.68]# half way into the cave).]The PRIEST: #NPCPriest Trainer# (is at #COORD[42.69]# on the brown rug).]The MAGE: #NPCMage Trainer# (is at #COORD[42.69]# on the brown rug).]The #NPCWarlock Trainer# (is at #COORD[41.68]# at the end of the cave)."},
      [20] = { str = "Go east a bit and turn in #INLazy Peons# (#COORD[45.69]#, #10 on map), accept #GETThazz'ril's Pick# ."},
      [21] = { str = "Go north inside the cave (#COORD[44.56]#) and do SHAMAN: #DOCall of Earth# ,] #DOBurning Blade Medallion# and #DOThazz'ril's Pick# : keep hugging the right side of the cave until you get to #NPCYarrog Baneshadow# and kill/loot him. Then drop down and keep hugging the left side of the cave until you get to #ITEMThazz'ril's Pick#, and loot it. And kill/loot the SHAMAN: #NPCFelstalkers# for the 2 hooves.]"},
      [22] = { str = "Once done, use your Hearthstone to go back to the Valley of Trials and then by the wagon, turn in #INBurning Blade Medallion# (#COORD[43.69]#, #8 on map), accept #GETReport to Sen'jin Village# ."},
      [23] = { str = "Shaman, Next to the #NPCShaman Trainer# (#COORD[42.69]#), turn in #INCall of Earth# , accept the next #GETpart#."},
      [24] = { str = "Shaman, Go south and go to the Hidden Path (entrance at #COORD[41.74]#).."},
      [25] = { str = "Shaman, Follow the path and hug the left side of the mountains and once you get to Spirit Rock (#COORD[44.76]#), then use your #ITEMEarth Sapta# quest item at the big grey stone. Talk to the #NPCbig elemental# that spawns to turn in #INCall of Earth# , accept the next #GETpart#."},
      [26] = { str = "Shaman, Go back to the starting spot (there is a shortcut right as you start going back over the mountains). Back next to the #NPCShaman Trainer# (#COORD[42.69]#, #17a on map), turn in #INCall of Earth# . You now have Stoneskin Totem!"},
      [27] = { str = "Priest, On the brown rug, from the #NPCPriest Trainer# (#COORD[42.69]#), accept #GETIn Favor of Spirituality# ."},
      [28] = { str = "Go east a bit and turn in #INThazz'ril's Pick# (#COORD[45.69]#, #10 on map)."},
      [29] = { str = "Leave starting noob zone by heading east on the path..."},
    },
  },
  [0608] = {
    title = "6-8 Durotar",
    items = {
      [1] = { str = "At Sen'jen Village (#COORD[56.75]#), turn in #INReport to Sen'jin Village# , accept all quests there: #GETMinshina's Skull# , #GETReport to Orgnil# and #GETZalazane# . Next to you, accept #GETA solvent Spirit# . Then next to you up in the little hut, accept #GETPractical Prey# . You can get resupplied by the #NPCdancing male troll# by the Raging Bonefire. Hunters, you can buy arrows inside the biggest hut if you need to.HUNTER: ] Mages, learn your level 6 spells/abilities in the hut (#COORD[56.75]#) from the MAGE: #NPCMage Trainer#.]"},
      [2] = { str = "Orc Warrior, ORC Warrior Only: If you have 4s 84c after selling unneeded items, buy a #ITEMLarge Axe# from #NPCTrayexir# (back in the big hut, #COORD[56.73]#). If not, grind during step 04 until you have enough items to buy it in Razor Hill."},
      [3] = { str = "Go NW towards the main path and accept #GETA Peon's Burden# (#COORD[52.68]#)."},
      [4] = { str = "Run up north to Razor Hill, grinding mobs along the way, and make sure you get to level 6 before you get up there for new spells/abilities. Once there, on your left, turn in #INReport to Orgnil# (#COORD[52.44]#), accept #GETDark Storms# . In the burrow next to you, accept #GETVanquish the Betrayers# and #GETEncroachment# . Also get new spells/abilities from the HUNTER: #NPCHunter Trainer# in the bottom of the burrow.] Also get new spells/abilities from the ROGUE: #NPCRogue Trainer# at the top of the burrow.]"},
      [5] = { str = "Go up to the top of the watchtower NW of Razor Hill, (up at #COORD[50.40]#) and accept #GETCarry Your Weight# ."},
      [6] = { str = "Drop down SE and accept #GETBreak a Few Eggs# (at the cooking area, #COORD[51.42]#)."},
      [7] = { str = "Go in the Inn next to you and turn in #INA Peon's Burden# (#COORD[52.42]#). And also make Razor Hill your new home for your Hearthstone. Make sure you are repaired/resupplied."},
      [8] = { str = "Orc Warrior, ORC Warrior Only: If you haven't got a #ITEMLarge Axe# yet, and have 4s 84c after selling unneeded items, buy a #ITEMLarge Axe# from #NPCUhgar# (next to the Inn at the Heated Forge area, #COORD[56.73]#)."},
      [9] = { str = "Enter the Barracks across the path, make a left at the entrance and get Apprentice First Aid (#COORD[54.42]#) from #NPCRawrk#."},
      [10] = { str = "Priest, Next to you in the Barracks, from the #NPCPriest Trainer# (#COORD[54.43]#), turn in #INIn Favor of Spirituality# , accept #GETGarments of Spirituality# . Also get new/spells abilities."},
      [11] = { str = "Priest, Go south of Razor Hill and on the east side of the main path next to a tall rock do #DOGarments of Spirituality# : heal the kneeling #NPCGrunt Kor'ja# (#COORD[53.46]#) with Lesser Heal R2, and buff her with Fortitude."},
      [12] = { str = "Shaman, Next to you in the Barracks, from the #NPCShaman Trainer# (#COORD[54.43]#) get new/spells abilities."},
      [13] = { str = "Warrior, Next to you in the Barracks, from the #NPCWarrior Trainer# (#COORD[54.43]#) get new/spells abilities. NOTE: Learn Parry, but Thunder Clap is not that important right now."},
      [14] = { str = "Warlock, Go behind the Barracks and from the #NPCWarlock Trainer# (#COORD[54.43]#) get new/spells abilities. The #NPCDemon Trainer# is back there too."},
      [15] = { str = "Go SE to Tiragarde Keep and do #DOVanquish the Betrayers# along with #DOCarry Your Weight# : kill/loot the humans around and in the fortress, also work your way to the top of the fortress and kill/loot #NPCLieutenant Benedict# (#COORD[60.58]#). Once you loot the key from his corpse, then go up the other steps to open #ITEMBenedict's Chest#, to accept #GETThe Admiral's Orders# from the #ITEMAged Envelope# inside."},
      [16] = { str = "Once done, die on purpose and res at spirit to get back to Razor Hill and up in the burrow, turn in #INVanquish the Betrayers# (#COORD[52.44]#, #4 on map), accept #GETFrom The Wreckage....# . Also turn in #INThe Admiral's Orders# , accept the next #GETpart#."},
      [17] = { str = "Go up to the top of the watchtower NW of Razor Hill, (up at #COORD[50.40]#, #5 on map) and turn in #INCarry Your Weight# . Make sure you are repaired/resupplied."},
      [18] = { str = "Go east to the beach and under the water do #DOA solvent Spirit# along with #DOFrom The Wreckage....# : kill/loot the crabs and makrura mobs and loot the #ITEMGnomish Toolboxes#."},
      [19] = { str = "Go just SW of Razor Hill and do the first half of #DOEncroachment# (around #COORD[49.49]#): kill the #NPCRazormane Quilboars# and #NPCRazormane Scouts#."},
      [20] = { str = "If you're not at least 3 bars away from lvl 8, grind until you are (for lvl 8 spells/abilities), Then go to Razor Hill and at the top of the burrow turn in #INFrom The Wreckage....# (#COORD[52.44]#, #4 on map). Also get new spells/abilities from the HUNTER: #NPCHunter Trainer# in the bottom of the burrow.] Also get new spells/abilities from the ROGUE: #NPCRogue Trainer# at the top of the burrow.] Also make sure you are repaired/resupplied."},
      [21] = { str = "Priest, Go in the Barracks and from the #NPCPriest Trainer# (#COORD[54.43]#), turn in #INGarments of Spirituality# . Also get new/spells abilities."},
      [22] = { str = "Shaman, Go in the Barracks and from the #NPCShaman Trainer# (#COORD[54.43]#) get your level 8 spells/abilities."},
      [23] = { str = "Warrior, Go in the Barracks and from the #NPCWarrior Trainer# (#COORD[54.43]#) get your level 8 spells/abilities."},
      [24] = { str = "Warlock, Go behind the Barracks and from the #NPCWarlock Trainer# (#COORD[54.43]#) get your level 8 spells/abilities. The #NPCDemon Trainer# is back there too."},
    },
  },
  [0810] = {
    title = "8-10 Durotar",
    items = {
      [1] = { str = "Click on #ITEMAttack Plan: Valley of Trials# (#COORD[50.81]#)."},
      [2] = { str = "Click on #ITEMAttack Plan: Sen'jin Village# (#COORD[48.77]#)."},
      [3] = { str = "Click on #ITEMAttack Plan: Orgrimmar# (#COORD[46.79]#)."},
      [4] = { str = "Go east towards Sen'jin Village to the #NPCNPC# that patrols and hides around tress/rocks (around #COORD[55.75]#) and turn in #INThwarting Kolkar Aggression# ."},
      [5] = { str = "Go to Sen'jin Village and turn in #INA solvent Spirit# (#COORD[56.74]#). Make sure you are repaired/resupplied."},
      [6] = { str = "Mage, Make sure you are level 8 (grind on any mobs until you are). Then go to the #NPCMage Trainer# in the hut (#COORD[56.75]#) at Sen'jin Village and get your level 8 spells/abilities."},
      [7] = { str = "Go to Echo Isles (the islands SE of Durotar) and do the following 4 quests together #DOBreak a Few Eggs# , #DOPractical Prey# , #DOMinshina's Skull# and #DOZalazane# : kill/loot #NPCDurotar Tigers#, pickup #ITEM Taillasher Eggs#, and (at #COORD[68.88]#) pickup #ITEMMinshina's Skull# (on the little hill with candles around it) and in that same area kill/loot #NPCZalazane# (See Video)."},
      [8] = { str = "After completing all these quests, die on purpose (then res) to get to Sen'jin Village quickly, and turn in #INMinshina's Skull# and #INZalazane# (#COORD[56.75]#). NOTE: Save the quest reward item #ITEMFaintly Glowing Skull# for a later #DOquest#."},
      [9] = { str = "In the little hut next to you, turn in #INPractical Prey# (#COORD[56.74]#)."},
      [10] = { str = "Hearth to Razor Hill and turn in #INBreak a Few Eggs# (by the cooking area next to the Inn, #COORD[51.43]#). Make sure you are repaired/resupplied."},
      [11] = { str = "Go west of Razor Hill and do the second half of #DOEncroachment# : kill the #NPCRazormane Dustrunners# and #NPCRazormane Battleguards# (around #COORD[44.40]#)."},
      [12] = { str = "Grind north to the little house (#COORD[43.30]#) and accept #GETLost But Not Forgotten# ."},
      [13] = { str = "Go NE to the #NPCgoblin# and accept #GETWinds in the Desert# (#COORD[46.23]#)."},
      [14] = { str = "Go east a bit (#COORD[49.22]#) and do #DOWinds in the Desert# : loot #ITEMStolen Supply Sacks# around the harpies."},
      [15] = { str = "Go back to the #NPCgoblin# and turn in #INWinds in the Desert# (#COORD[46.23]#, #13 on map), accept #GETSecuring the Lines# ."},
      [16] = { str = "Keep grinding on any mob in the area until you are at least #COORD[1.5]# bars away from level 10, then Hearth (or run back) to Razor Hill and at the top of the burrow turn in #INEncroachment# (#COORD[52.43]#). Make sure you are repaired/resupplied. Upgrade First Aid in the Barracks if you need to from #NPCRawrk#."},
      [17] = { str = "Shaman, Go in the Barracks and from the #NPCShaman Trainer# (#COORD[54.43]#) accept #GETCall of Fire# . Also get new spells/abilities."},
      [18] = { str = "Shaman, Go north then west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [19] = { str = "Warlock, Go behind the Barracks and from the #NPCWarlock Trainer# (#COORD[54.41]#) accept #GETGan'rul's Summons# . Also get new spells/abilities."},
      [20] = { str = "Warlock, Go north then west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [21] = { str = "Warrior, Go in the Barracks and from the #NPCWarrior Trainer# (#COORD[54.43]#) accept #GETVeteran Uzzek# . Also get new spells/abilities."},
      [22] = { str = "Warrior, Go north then west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [23] = { str = "Priest, Go in the Barracks and from the #NPCPriest Trainer# (#COORD[54.43]#) accept #GETHex of Weakness# . Also get new spells/abilities."},
      [24] = { str = "Priest, Go north then west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [25] = { str = "Rogue, Next to you at the top of the burrow, accept your level 10 class quest #GETTherzok# . Also get new spells/abilities."},
      [26] = { str = "Rogue, Go north then west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [27] = { str = "Mage, Go west and between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
      [28] = { str = "Mage, Keep grinding up north (near Orgrimmar's entrance) until you reach level 10.."},
    },
  },
  [1010] = {
    title = "[Hunter] level 10 Class Quests",
    items = {
      [1] = { str = "Tame a #NPCDire Mottled Boar# (just SW of Razor Hill, around #COORD[52.46]#)."},
      [2] = { str = "Run back and turn in #INTaming the Beast# (#COORD[52.44]#, # 1 on map) and accept the next #GETpart#."},
      [3] = { str = "At the #NPCBowyer# (#COORD[53.41]#) under the red tent, upgrade to #ITEMSharp Arrows# and a #ITEMMedium Quiver#."},
      [4] = { str = "Tame a #NPCSurf Crawler# NE of Razor Hill along the beach (around #COORD[59.28]#)."},
      [5] = { str = "#COORD[59.28]#"},
      [6] = { str = "Run back and turn in #INTaming the Beast# (#COORD[52.44]#, # 1 on map) and accept the next #GETpart#."},
      [7] = { str = "Tame a #NPCArmored Scorpid# NW of Razor Hill (around the watchtower #COORD[49.37]#)."},
      [8] = { str = "Run back and turn in #INTaming the Beast# (#COORD[52.44]#, # 1 on map), accept #GETTraining the Beast# ."},
      [9] = { str = "#GETTraining the Beast# "},
      [10] = { str = "Go up north, (around #COORD[45.21]#) and tame a #NPCVenomtail Scorpid# for your first real pet. Try to get a level 10. This allows you to learn Claw R2 and Scorpid Poison."},
      [11] = { str = "Between the large rocks (#COORD[42.19]#), accept #GETNeed for a Cure# . NOTE: Don't worry about the timer countdown."},
    },
  },
  [1011] = {
    title = "Orgrimmar",
    items = {
      [1] = { str = "Warrior, If you have at least 35 silver to spare, then consider purchasing a #ITEMTabar# axe down in The Shattered Axe (#COORD[48.69]#, next to the bank)."},
      [2] = { str = "Warrior, If you have 10 silver to spare go NE to The Valley of Honor and at the Weapon Masters (#COORD[81.20]#) learn #VIDEOTwo-Handed Axes# (#COORD[66.18]# in Orgrimmar). If not make sure you do this later."},
      [3] = { str = "Warlock, If you have 10 silver to spare go NE to The Valley of Honor and at the Weapon Masters (#COORD[81.20]#) learn Staves (#COORD[66.18]# in Orgrimmar). If not make sure you do this later."},
      [4] = { str = "Hunter, Go to the Hunter Trainer and turn in #INTraining the Beast# (#COORD[66.18]# in Orgrimmar)."},
      [5] = { str = "Hunter, If you can afford to, you can learn new weapon possibilities at the two Weapon Masters in the hut (east of you at #COORD[82.19]#). I recommend eventually learning Two-Handed Axes and/or Staves from them."},
      [6] = { str = "Shaman, If you have 10 silver to spare go NE to The Valley of Honor and at the Weapon Masters (#COORD[81.20]#) learn #VIDEOOne-Handed Axes# (#COORD[66.18]# in Orgrimmar)."},
      [7] = { str = "Priest, As you enter Orgrimmar keep left on the path and then go up the ramp in the building (at #COORD[42.62]#), to go up.."},
      [8] = { str = "Rogue, As you enter Orgrimmar keep left on the path and then go up the ramp in the building (at #COORD[42.62]#), to go up.."},
      [9] = { str = "Priest, Go SW to the Valley of Spirits and at the #NPCPriest Trainer# (#COORD[36.88]# in Orgrimmar) turn in #INHex of Weakness# (#COORD[66.18]# in Orgrimmar)."},
      [10] = { str = "Go up and north to #NPCThrall# and accept #GETHidden Enemies# (#COORD[32.38]#). Next to you, turn in #INThe Admiral's Orders# ."},
      [11] = { str = "Go into the Cleft of Shadow (an entrance is at #COORD[40.53]# in Orgrimmar)..."},
      [12] = { str = "Rogue, As you enter Cleft of Shadow make a sharp left into the first hut and turn in #INTherzok# (#COORD[43.53]#), accept #GETThe Shattered Hand# ."},
      [13] = { str = "Then accept #GETFinding the Antidote# (#COORD[47.54]#)."},
      [14] = { str = "Warlock, Also down & NE in Cleft of Shadow, turn in #INGan'rul's Summons# (#COORD[48.45]#), accept #GETCreature of the Void# ."},
      [15] = { str = "Warlock, Go south to exit Orgrimmar, then go east to enter Skull Rock (cave entrance at #COORD[55.10]# in Durotar).."},
      [16] = { str = "Warlock, In Skull Rock do #DOCreature of the Void# : keep hugging the right side of the cave until you get to a ledge and then loot the #ITEMBurning Blade Stash# (in the cave, #COORD[52.10]#)"},
      [17] = { str = "Warlock, Die on purpose, then res at spirit."},
      [18] = { str = "Warlock, Go north to enter Orgrimmar and to the Cleft of Shadow (#3 on map), then turn in #INCreature of the Void# (#COORD[48.45]# in Orgrimmar, #4a on map), accept #GETThe Binding# ."},
      [19] = { str = "Warlock, Just south in Cleft of Shadow go to #NPCNeeru Fireblade's# hut and do #DOThe Binding# : use the #ITEMGlyphs of Summoning# quest item in his tent to summon a voidwalker, then kill it."},
      [20] = { str = "Warlock, Go back north in Cleft of Shadows and turn in #INThe Binding# (#COORD[48.45]# in Orgrimmar, #4a on map). You can now summon a Voidwalker!"},
      [21] = { str = "SE in Cleft of Shadows, enter RFC Dungeon to die on purpose (entrance at #COORD[53.49]#), then res at spirit."},
    },
  },
  [1012] = {
    title = "[Mage] Orgrimmar",
    items = {
      [1] = { str = "As you enter Orgrimmar keep left on the path and then go up the ramp in the building (at #COORD[42.62]#), to go up.."},
      [2] = { str = "Stay up and go south to The Valley of Spirits and in the Darkbriar Lodge, go to the Mage Trainers (#COORD[38.87]#) and accept #GETSpeak with Un'thuwa# . Also get your level 10 spells/abilities."},
      [3] = { str = "Stay up and go into the Cleft of Shadow (an entrance is at #COORD[40.53]# in Orgrimmar)..."},
      [4] = { str = "Then accept #GETFinding the Antidote# (#COORD[47.54]#)."},
      [5] = { str = "Go up and go north to #NPCThrall# and accept #GETHidden Enemies# (#COORD[32.38]#). Next to you, turn in #INThe Admiral's Orders# ."},
      [6] = { str = "Hearth to Razor Hill. Make sure you are repaired/resupplied."},
      [7] = { str = "At the top of the burrow turn in #INEncroachment# (#COORD[52.43]#)."},
      [8] = { str = "Go south to Sen'Jin Village and at the #NPCMage Trainer# in the hut (#COORD[56.75]#) turn in #INSpeak with Un'thuwa# , accept #GETJu-Ju Heaps# ."},
      [9] = { str = "Go SE to Echo Isles and do #DOJu-Ju Heaps# : click the #ITEMJu-Ju Heaps# (around #COORD[68.83]#) in the huts (there is at least one in every hut on the island)."},
      [10] = { str = "Die on purpose and res at spirit to get back to Sen'Jin Village, then at the #NPCMage Trainer# in the hut (#COORD[56.75]#, #9 on map) turn in #INJu-Ju Heaps# . NOTE: Many agree that the #ITEM Ley Orb# is the better reward."},
    },
  },
  [1013] = {
    title = "10-12 Durotar",
    items = {
      [1] = { str = "At the #NPCgoblin#, turn in #INSecuring the Lines# (#COORD[46.23]#)."},
      [2] = { str = "Start working on #DOFinding the Antidote# : kill/loot #NPCVenomtail Scorpids#. And start working on #DOLost But Not Forgotten# : kill/loot the #NPCDreadmaw Crocolisk# in the river for #ITEMKron's Amulet#. Work your way south along the river to do the next step:"},
      [3] = { str = "Go west into The Barrens and follow the road west until you see a small tower on the right side of the road. There you will find #NPCKranal Fiss# (#COORD[56.20]# in The Barrens). Turn in #INCall of Fire# , accept the next #GETpart#."},
      [4] = { str = "Go back east to the bridge at Durotar and work south along the river while continue working on #DOLost But Not Forgotten# : kill/loot the #NPCDreadmaw Crocolisk# in the river for #ITEMKron's Amulet#. Work your way south along the river to do the next step:"},
      [5] = { str = "Go to the hidden path (entrance at #COORD[37.58]#). Follow this path upwards to the next step, be careful the path has tight edges:"},
      [6] = { str = "Once you get to #NPCTelf Joolam# (#COORD[39.59]#), turn in #INCall of Fire# , accept the next #GETpart#."},
      [7] = { str = "Run down the mountain (use jumping shortcuts halfway down) and head north along the river while finishing #DOLost But Not Forgotten# : kill/loot the #NPCDreadmaw Crocolisk# in the river for #ITEMKron's Amulet#. Work your way to Thunder Ridge (entrance at #COORD[39.31]#)."},
      [8] = { str = "In Thunder Ridge, do #DODark Storms# : work your way to #NPCFizzle Darkstorm# (a goblin at #COORD[42.27]#) and kill/loot him. Be careful he is heavily guarded."},
      [9] = { str = "Exit Thunder Ridge, then go east to the little house and turn in #INLost But Not Forgotten# (#COORD[43.30]#)."},
      [10] = { str = "Go to Razor Hill and turn in #INDark Storms# (#COORD[52.43]# in Durotar), accept #GETMargoz# . Make sure you are repaired/resupplied."},
      [11] = { str = "Exit Razor Hill through the NE gate exit (#COORD[55.40]#).."},
      [12] = { str = "Go north and enter Dustwind Cave (entrance up at #COORD[53.28]#). In the cave do part of #INCall of Fire# : kill/loot #NPCBurning Blade Cultists# (the ones with the Imps) for the #ITEMReagent Pouch# (medium drop rate)."},
      [13] = { str = "Exit the cave then go north along the coast and turn in #INMargoz# (#COORD[56.20]#), accept #GETSkull Rock# ."},
      [14] = { str = "Go to the cave up north (#COORD[55.10]#) and do #DOSkull Rock# along with #DOHidden Enemies# : kill/loot the mobs in the cave. If you can, try to kill #NPCGazz'uz#, he drops #ITEMEye of Burning Shadow# item which starts #GETBurning Shadows# quest. TIPS: use the quest reward item #ITEMFaintly Glowing Skull# to help you kill him, he's tough without it. If you are an Orc, don't use Blood Fury before you have used your healing items. Also try to party up with somebody if you can. (See Video on how I killed Gazz'uz). Also don't leave this cave until you have grinded out First Aid (40) to learn #VIDEOHeavy Linen Bandage# soon."},
      [15] = { str = "Exit the cave and go directly south to turn in #INSkull Rock# (#COORD[56.20]#, #1 on map), accept #GETNeeru Fireblade# . And make sure #DOFinding the Antidote# is finished (kill/loot scorpids, #3 on map)."},
      [16] = { str = "Go into Orgrimmar and go to #NPCThrall# to turn in #INHidden Enemies# (#COORD[32.38]#). Accept the next #GETpart#."},
      [17] = { str = "Go to Cleft of Shadows (#COORD[47.53]# in Orgrimmar) and turn in #INFinding the Antidote# ."},
      [18] = { str = "Also in the Cleft of Shadows, turn in #INNeeru Fireblade# and (if you have it) #INBurning Shadows# (#COORD[50.51]# in Orgrimmar), accept #GETAk'Zeloth# . Also keep talking to this NPC to complete #DOHidden Enemies# ."},
      [19] = { str = "Go back to #NPCThrall# (#COORD[32.38]#, #4 on map) and turn in #INHidden Enemies# , SKIP the next #DOpart# (Dungeon). NOTE: You can destroy the #ITEMLieutenant's Insignia#, as its not used for anything else."},
      [20] = { str = "Go into Cleft of Shadows and enter RFC Dungeon (entrance at #COORD[53.49]#) to die on purpose, res at spirt."},
      [21] = { str = "Go west in Durotar and turn in #INNeed for a Cure# (between the large rocks, #COORD[41.18]#). NOTE: You will most likely have to abandon the quest and accept it again to turn it in."},
      [22] = { str = "Make sure you are level 12, then Hearth to Razor Hill. Make sure you get repaired/resupplied. Upgrade First Aid in the Barracks if you need to from #NPCRawrk#. Go in the Barracks and from the #NPCShaman Trainer# (#COORD[54.43]#) get new/spells abilities."},
      [23] = { str = "On the west side in Razor Hill, accept #GETConscript of the Horde# (#COORD[51.44]#)."},
      [24] = { str = "Run west into the Barrens..."},
    }
  },
}

