--[[--------------------------------------------------
002_Teldrassil.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 002 Teldrassil
1.04.1
-- First Release
Night Elves Teldrassil's Guide
from level 1 to lever 12
1.04.2
-- no changes in here for this revision

Faelwen
04 June 2019 - Guide replaced with Joanna's Alliance Guide (https://www.joanasworld.com/alliance-1-12-teldrassil.html)

------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_002_Teldrassil = {
  [0106] = {
    title = "1-6 Shadowglen",
    items = {
      [1] = { str = "Start working on #DOThe Balance of Nature# : kill #NPCYoung Nightsabers# and #NPCYoung Thistle Boars# around the immediate area. Work your way to the next steps while doing this:"},
      [2] = { str = "Go east to the entrance of Aldrassil and accept #GETThe Woodland Protector# (#COORD[60.42]#)."},
      [3] = { str = "Near where you started from, at the Dryad #NPCTarindrella#, turn in #INThe Woodland Protector# (#COORD[58.45]#), accept the next #GETpart#."},
      [4] = { str = "Go just west to the Grell camps (around #COORD[56.46]#) and do #DOThe Woodland Protector# : kill/loot #NPCGrell# and #NPCGrellkin#."},
      [5] = { str = "Back at the Dryad #NPCTarindrella#, turn in #INThe Woodland Protector# (#COORD[58.45]#, #4 on map)."},
      [6] = { str = "Make sure #INThe Balance of Nature# is finished, then turn it in (at the starting spot, #COORD[59.44]#, #1 on map). Accept #GETThe Balance of Nature# (Part2). We will get HUNTER: #DOEtched Sigil# later.] And accept your class's quest WARRIOR: #GETSimple Sigil# .]We will get ROGUE: #DOEncrypted Sigil# later.]And accept your class's quest PRIEST: #GETHallowed Sigil# .]We will get DRUID: #DOVerdant Sigil# later.]"},
      [7] = { str = "Go near the entrance of Aldrassil, next to the Cauldron and accept #GETA Good Friend# (#COORD[61.42]#)."},
      [8] = { str = "Go up the ramp in Aldrassil to get repaired/resupplied (#COORD[59.41]#)."},
      [9] = { str = "Warrior, Go inside Aldrassil next to you and up the ramp and at the #NPCWarrior Trainer# (#COORD[60.38]#), turn in #INSimple Sigil# and learn #VIDEOBattle Shout# R1."},
      [10] = { str = "Priest, Go up the ramp next to you and at the #NPCPriest Trainer# (#COORD[59.40]#), turn in #INHallowed Sigil# and learn #VIDEOPower Word: Fortitude# R1."},
      [11] = { str = "Go to the west side of Aldrassil at the bottom of the ramp entrance and accept #GETWebwood Venom# (#COORD[58.42]#)."},
      [12] = { str = "Grind NW to #NPCIverron# (sitting between some mountains) and turn in #INA Good Friend# (#COORD[55.33]#), accept #GETA Friend in Need# ."},
      [13] = { str = "Just east of you, do #DOWebwood Venom# : kill/loot #NPCWebwood Spiders#. A lot of spiders can be found outside of the cave and more inside (#COORD[57.32]#)."},
      [14] = { str = "All around the north side of Shadowglen, do #DOThe Balance of Nature# : kill 7 #NPCMangy Nightsabers# and 7 #NPCThistle Boars#."},
      [15] = { str = "Die on purpose, then res at Spirit Healer."},
      [16] = { str = "Go south to the starting spot and from #NPCConservator Ilthalaine#, turn in #INThe Balance of Nature# (#COORD[59.44]#). Also accept your class's quest ROGUE: #GETEncrypted Sigil# .]Also accept your class's quest HUNTER: #GETEtched Sigil# .]Also accept your class's quest DRUID: #GETVerdant Sigil# .]"},
      [17] = { str = "Go east near the entrance of Aldrassil, next to the Cauldron and turn in #INA Friend in Need# (#COORD[61.42]#), accept #GETIverron's Antidote# ."},
      [18] = { str = "Go up the ramp in Aldrassil to get repaired/resupplied (#COORD[59.41]#)."},
      [19] = { str = "Warrior, Go inside Aldrassil next to you and up the ramp and at the #NPCWarrior Trainer# (#COORD[60.38]#), learn new abilities."},
      [20] = { str = "Rogue, Go inside Aldrassil next to you and up the ramp and at the #NPCRogue Trainer# (#COORD[60.38]#), turn in #INEncrypted Sigil# and learn new abilities."},
      [21] = { str = "Priest, Go up the ramp next to you and at the #NPCPriest Trainer# (#COORD[59.40]#), learn new abilities."},
      [22] = { str = "Go to the west side of Aldrassil at the bottom of the ramp entrance and turn in #INWebwood Venom# (#COORD[58.42]#), accept #GETWebwood Egg# ."},
      [23] = { str = "Druid, Druids, go up the ramp next to you and the first room you see on your left you will find the #NPC Druid Trainer#, from him turn in #INVerdant Sigil# and learn new abilities."},
      [24] = { str = "hunter, Hunters, go up the ramp next to you and the first room you see on your left you will find the #NPC Hunter Trainer#, from him turn in #INEtched Sigil# and learn new abilities."},
      [25] = { str = "Go west to the #NPCGrellkin# camp (around #COORD[55.39]#) and do part of #DOIverron's Antidote# : kill/loot #NPCGrellkin# for the #ITEMHyacinth Mushrooms#. NOTES: These shrooms do NOT drop from the #NPCGrell# mobs, only #NPCGrellkin#. You can also find these from #ITEMHyacinth Mushroom# objects around the trees & mountains all around Shadowglen, but focus on kill/looting the #NPCGrellkin# for faster leveling."},
      [26] = { str = "Go east to the two small ponds (around #COORD[58.38]#) and do part of #DOIverron's Antidote# : loot the #ITEMMoonpetal Lily# (yellow flowers) around the ponds."},
      [27] = { str = "Go NW to Shadowthread Cave (entrance at #COORD[57.32]#) and do #DOWebwood Egg# along with finishing #DOIverron's Antidote# : kill/loot the spiders while working your way NW in the cave to eventually loot a #ITEM Webwood Egg#."},
      [28] = { str = "Use your Hearthstone to hearth to the starting spot."},
      [29] = { str = "Go east near the entrance of Aldrassil, next to the Cauldron and turn in #INIverron's Antidote# (#COORD[61.42]#), accept the next #GETpart#. NOTE: Work somewhat quickly to do the next steps as this quest is on a 5 min timer."},
      [30] = { str = "Go in Aldrassil to get repaired/resupplied (#COORD[59.41]#)."},
      [31] = { str = "Go to the west side of Aldrassil at the bottom of the ramp entrance and turn in #INWebwood Egg# (#COORD[58.42]#). Accept #GETTenaron's Summons# ."},
      [32] = { str = "Go up the ramp next to you, to the very top and then turn in #INTenaron's Summons# , accept #GETCrown of the Earth# ."},
      [33] = { str = "Go NW to #NPCIverron# (sitting between some mountains) and turn in #INIverron's Antidote# (#COORD[55.33]#)."},
      [34] = { str = "Go east to the Moonwell (#COORD[60.33]#) and do #DOCrown of the Earth# : use the #ITEM Crystal Phial# quest item in the Moonwell."},
      [35] = { str = "Die on purpose, then res at Spirt Healer."},
      [36] = { str = "Go to the top of Aldrassil (ramp entrance at #COORD[58.41]#, #5 on map) and turn in #INCrown of the Earth# , accept the next #GETpart#."},
      [37] = { str = "Follow the main path south to leave Shadowglen and on your way out, accept #GETDolanaar Delivery# (#COORD[61.48]#)."},
    },
  },
  [0610] = {
    title = "6-10 Dolanaar",
    items = {
      [1] = { str = "Keep going west to Dolanaar and make sure you are at least 340 XP away from level 6 before getting there for new spells/abilities. Once at Dolanaar, at the bottom of the tower entrance, accept #GETDenalan's Earth# (#COORD[56.58]#)."},
      [2] = { str = "Just up the ramp, accept #GETA Troubling Breeze# (#COORD[56.57]#)."},
      [3] = { str = "Just inside the tower, from the #NPC First Aid Trainer# (#COORD[55.57]#), learn Apprentice First Aid."},
      [4] = { str = "Priest, Next to you at the #NPCPriest Trainer# (#COORD[57.59]#), learn your level 6 spells."},
      [5] = { str = "Next to you, go up the ramp to the very top of the tower and accept #GETTwisted Hatred# and #GETThe Emerald Dreamcatcher# ."},
      [6] = { str = "Drop down and go in the Inn to get repaired/resupplied (#COORD[56.59]#)."},
      [7] = { str = "Go up the ramp to the #NPCInnkeeper# and turn in #INDolanaar Delivery# (#COORD[56.60]#). Also make Dolanaar your new home for your hearthstone."},
      [8] = { str = "Go south in Dolanaar to the Moonwell and turn in #INCrown of the Earth# (#COORD[56.62]#), accept the next #GETpart#. NOTE: If you are already lvl 6 right now, then do the next step first before doing this!"},
      [9] = { str = "Hunter, Go just to the east outside of the Inn to find the #NPCHunter Trainer# (#COORD[57.59]#) to learn your level 6 abilities."},
      [10] = { str = "Warrior, Go in the bottom part of the Inn to find the #NPCWarrior Trainer# (#COORD[56.59]#) to learn your level 6 abilities."},
      [11] = { str = "Rogue, Go in the bottom part of the Inn to find the #NPCRogue Trainer# (#COORD[56.59]#) to learn your level 6 abilities."},
      [12] = { str = "Druid, Learn your level 6 abilities at the #NPCDruid Trainer# (#COORD[56.62]#) right next to you at the moonwell."},
      [13] = { str = "Go SE to the small camp at Lake Al'Ameth and turn in #INDenalan's Earth# (#COORD[61.68]#). Accept #GETTimberling Seeds# and #GETTimberling Sprouts# ."},
      [14] = { str = "All around Lake Al'Ameth do #DOTimberling Seeds# along with #DOTimberling Sprouts# : kill/loot #ITEM Timberling# mobs and also loot the #ITEMTimberling Sprouts# on the ground."},
      [15] = { str = "Go back to the small camp at Lake Al'Ameth and turn in #INTimberling Seeds# (#COORD[61.68]#, #1 on map), accept #GETRellian Greenspyre# . Also turn in #INTimberling Sprouts# . "},
      [16] = { str = "Start working on #DOZenn's Bidding# : kill/loot nightsabers (cats), spiders and owls. While working on this, work your way to the next steps:"},
      [17] = { str = "Go NE to the Moonwell at Starbreeze Village and do #DOCrown of the Earth# : use the #ITEM Jade Phial# quest item in the Moonwell (#COORD[63.58]#)."},
      [18] = { str = "Follow the path east and go up in the first building on your right and turn in #INA Troubling Breeze# (#COORD[56.57]#), accept #GETGnarlpine Corruption# ."},
      [19] = { str = "Go in the east most building at Starbreeze Village and do #DOThe Emerald Dreamcatcher# : loot #ITEMTallonkai's Dresser# (#COORD[68.60]#)."},
      [20] = { str = "Finish #DOZenn's Bidding# : kill/loot nightsabers (cats), spiders and owls around the open fields of Teldrassil (#4 on map)."},
      [21] = { str = "Go to #NPCZenn Foulhoof# north of the main path between Dolanaar and Starbreeze Village and turn in #INZenn's Bidding# (#COORD[60.56]#). NOTE: Make sure you save the quest reward #ITEMitem# for later, do not sell it to a vendor!"},
      [22] = { str = "Go west to Dolanaar and at the bottom of the tower entrance, accept #GETSeek Redemption!# (#COORD[56.58]#). NOTE: Save any #ITEMSmall Spider Legs# you have as you will use them for a later #DOquest#."},
      [23] = { str = "Just up the ramp, turn in #INGnarlpine Corruption# (#COORD[56.57]#), accept #GETThe Relics of Wakening# ."},
      [24] = { str = "Go south in the Inn to get repaired/resupplied (#COORD[56.59]#)."},
      [25] = { str = "Go south in Dolanaar to the Moonwell and turn in #INCrown of the Earth# (#COORD[56.62]#), accept the next #GETpart#."},
      [26] = { str = "Just east of you at the Cauldron, Learn Apprentice Cook from the #NPC Cook# (#COORD[57.61]#). Then accept #GETRecipe of the Kaldorei# (cooking quest). Then as you are doing the next sections start working on this by kill/looting any spiders along the way and do not sell the #ITEMSmall Spider Legs# to a vendor. Also turn this in once you get all the legs."},
      [27] = { str = "Do #DOSeek Redemption!# : loot 3 #ITEMFel Cones#. These are found around the trees of Teldrassil. See map for locations."},
      [28] = { str = "Go north of the main path between Dolanaar and Starbreeze Village at #NPCZenn Foulhoof# (#COORD[60.56]#) and turn in #INSeek Redemption!# ."},
      [29] = { str = "If you happen to have a group, continue on with the next steps (even if you are lvl 7). If you are going solo, make sure you are level 8 before proceeding, grind on any mobs in the immediate area to level 8."},
      [30] = { str = "Go to Dolanaar and in the Inn, get repaired/resupplied (#COORD[56.59]#)."},
      [31] = { str = "If you are level 8, get new spells/abilities at your class trainer. Hunters, go just to the east outside of the Inn to find the HUNTER: #NPCHunter Trainer# (#COORD[57.59]#).]Go in the bottom part of the Inn to find the WARRIOR: #NPCWarrior Trainer# (#COORD[56.59]#).]Go in the bottom part of the Inn to find the ROGUE: #NPCRogue Trainer# (#COORD[56.59]#).]Go in the bottom of the tree tower to find the PRIEST: #NPCPriest Trainer# (#COORD[56.57]#).]The DRUID: #NPCDruid Trainer# (#COORD[56.62]#) is right next to the moonwell at Dolanaar.]"},
      [32] = { str = "Go just north to Fel Rock (cave entrance at #COORD[55.52]#), enter the cave and do #DOTwisted Hatred# : keep hugging the right side of the cave and then make a left after the river, then see if #NPCLord Melenas# (an orange satyr) is standing at the edge and kill/loot him. If he is not there, continue hugging the right side of the cave and you will eventually get to him. This mob can be hard to solo so be prepared. Use the #ITEMSevered Voodoo Claw# to help you kill him. If you cannot do it, then skip it. Then exit the cave by heading SE."},
      [33] = { str = "Go to the bottom of the tree tower at Dolanaar (#COORD[55.57]#) to get resupplied at #NPCDanlyia#, then go up to the top of the tower and turn in #INTwisted Hatred# and #INThe Emerald Dreamcatcher# , accept #GETFerocitas the Dream Eater# ."},
      [34] = { str = "Go NE of Starbreeze Village and do #DOFerocitas the Dream Eater# : kill 7 #NPCGnarlpine Mystics# and kill/loot #NPCFerocitas the Dream Eater# (grey color furblog at #COORD[69.53]#), then loot the #ITEM Gnarlpine Necklace# that drops (in your inventory)."},
      [35] = { str = "Hearth to Dolanaar."},
      [36] = { str = "In the Inn, get repaired/resupplied and get lvl 8 spells/abilities if you haven't yet. Hunters, go just to the east outside of the Inn to find the HUNTER: #NPCHunter Trainer# (#COORD[57.59]#).]Go in the bottom part of the Inn to find the WARRIOR: #NPCWarrior Trainer# (#COORD[56.59]#).]Go in the bottom part of the Inn to find the ROGUE: #NPCRogue Trainer# (#COORD[56.59]#).]Go in the bottom of the tree tower to find the PRIEST: #NPCPriest Trainer# (#COORD[56.57]#).]The DRUID: #NPCDruid Trainer# (#COORD[56.62]#) is right next to the moonwell at Dolanaar.]"},
      [37] = { str = "Go to the top of the tree tower at Dolanaar (#COORD[55.57]#, #7 on map) and turn in #INFerocitas the Dream Eater# ."},
      [38] = { str = "Follow the main path west until you run into 3 nightelfs on their mounts (no further than #COORD[50.53]#), and from #NPCMoon Priestess Amara#, accept #GETThe Road to Darnassus# ."},
      [39] = { str = "Drop down to Ban'ethil Hollow (around #COORD[47.53]#) and do #DOThe Road to Darnassus# : kill 6 #NPCGnarlpine Ambushers#."},
      [40] = { str = "Go south and enter Ban'ethil Barrow Den (entrance at #COORD[44.58]#). NOTE: The Den quests can be difficult to do solo. Try to find help if you can, if not you can try to solo it. If you find yourself dying constantly, then it can be skipped (go to next section below) and you can come back later to do it, but my guide won't mention it."},
      [41] = { str = "Once in the Den, do part of #DOThe Relics of Wakening# : when you go down in the Den entrance you will get to two bridges, each of those two bridges takes you to 2 of the 4 chests you need to loot, which contains the #ITEMBlack Feather Quill# and #ITEMRune of Nesting#, loot them."},
      [42] = { str = "The next thing to do in the den is go down and take the SW tunnel. Then go across the bridge and on your right, accept #GETThe Sleeping Druid# (#COORD[45.62]#)."},
      [43] = { str = "As you do the following steps, also focus on doing #DOThe Sleeping Druid# : kill/loot #NPC Gnarlpine Shaman# until you receive the #ITEMShaman Voodoo Charm# (very low drop rate). You will find the shaman scattered throughout the Den (both inside and outside):"},
      [44] = { str = "Go down at the bridge and go SE and do part of #DOThe Relics of Wakening# : loot the #ITEMChest of the Sky# (#COORD[45.62]#) for the #ITEMSapphire of Sky#."},
      [45] = { str = "Finish #DOThe Sleeping Druid# : kill/loot #NPC Gnarlpine Shaman# until you receive the #ITEMShaman Voodoo Charm# (very low drop rate). You will find the shaman scattered throughout the Den (both inside and outside). When you found the Voodoo Charm, go to the south end of the Den, up past the bridge, then on your right, turn in #INThe Sleeping Druid# (#COORD[45.62]#, #5 on map), accept #GETDruid of the Claw# ."},
      [46] = { str = "Go to the very north end of the Den and do #DODruid of the Claw# : kill #NPC Rageclaw#, then use the #ITEMVoodoo Charm# quest item on his corpse. #NPC Rageclaw# is a Night Elf druid patrolling clockwise in a circle around the bottom of the room."},
      [47] = { str = "Up in the room you are at, take the east bridge and then finish #DOThe Relics of Wakening# : loot the #ITEMChest of the Raven Claw# (up at #COORD[46.57]#) to obtain the #ITEMRaven Claw Talisman#."},
      [48] = { str = "Go back to the south end of the Den, up past the bridge, then on your right, turn in #INDruid of the Claw# (#COORD[45.62]#, #5 on map)."},
      [49] = { str = "Leave the Den (exit at #COORD[43.60]#).."},
      [50] = { str = "Go SW to the Pools of Arlithrien and do #DOCrown of the Earth# : use the #ITEMTourmaline Phial# quest item at the Moonwell there (#COORD[42.67]#)."},
      [51] = { str = "Grind your way back towards Dolanaar and make sure you are at least 4,250 XP into lvl 9 before doing the next steps (or 5,050 into lvl 9 if you didn't do the Den). You can grind on Furblogs just west of Dolanaar, or any mobs in the open fields of Teldrassil."},
      [52] = { str = "Go north to the main path until you run into 3 nightelfs on their mounts (no further west than #COORD[50.53]#), and from #NPCMoon Priestess Amara#, turn in #INThe Road to Darnassus# ."},
      [53] = { str = "Go east to the entrance of the tree tower at Dolanaar and turn in (if you did it) #INThe Relics of Wakening# (#COORD[56.57]#), accept #GETUrsal the Mauler# ."},
      [54] = { str = "Go south to Dolanaar's Inn to get repaired/resupplied (#COORD[56.59]#)."},
      [55] = { str = "South at the Moonwell at Dolanaar, turn in #INCrown of the Earth# (#COORD[56.62]#), accept the next #GET part#."},
      [56] = { str = "You should be level 10 right now, if not grind to it."},
    },
  },
  [1001] = {
    title = "[Warrior] Level 10 Class Quest",
    items = {
      [1] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [2] = { str = "Just south of the main path in Darnassus, accept #GETNessa Shadowsong# (#COORD[71.45]#)."},
      [3] = { str = "As you enter Darnassus, make a left after the ramp/purple rug, and go to the #NPCWeapon Master# and learn new weapon possibilities if you can afford to. Learning #VIDEOThrown# is very useful for Warriors, so make sure you get that soon. You can revisit the #NPCWeapon Master# later to learn more. Also next to you, get repaired."},
      [4] = { str = "Slightly north of you, turn in #INElanaria# (#COORD[57.35]#), accept #GETVorlus Vilehoof# ."},
      [5] = { str = "Go NW to Cenarion Enclave and turn in #INRellian Greenspyre# (#COORD[38.22]#), accept #GETTumors# ."},
      [6] = { str = "West in Darnassus, next to the red glowing teleporter, accept #GETThe Temple of the Moon# (#COORD[29.46]#)."},
      [7] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, then turn in #INThe Temple of the Moon# (#COORD[29.46]#), accept #GETTears of the Moon# ."},
      [8] = { str = "As you exit Temple of the Moon north, make a left then go to the ledge (#COORD[20.64]#) and walk off the right side of the tree to land on the other one directly below you so you can die and then res back at Teldrassil (saving 32 sec)."},
      [9] = { str = "Go SE in Teldrassil and at the furblog camp is a hidden path (starting at #COORD[49.63]#). Go up this path and do #DOVorlus Vilehoof# : kill/loot #NPCVorlus Vilehoof# in the moonwell (#COORD[47.64]#)."},
    },
  },
  [1002] = {
    title = "[Rogue] Level 10 Class Quest",
    items = {
      [1] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [2] = { str = "Just south of the main path in Darnassus, accept #GETNessa Shadowsong# (#COORD[71.45]#)."},
      [3] = { str = "As you enter Darnassus, make a left after the ramp/purple rug, and go to the #NPCWeapon Master# and learn new weapon possibilities if you can afford to. Learning #VIDEOThrown# is very useful for Rogues, so make sure you get that soon. You can revisit the #NPCWeapon Master# later to learn more. Also next to you, get repaired."},
      [4] = { str = "Go NW to Cenarion Enclave and turn in #INRellian Greenspyre# (#COORD[38.22]#), accept #GETTumors# ."},
      [5] = { str = "Just NW a bit, go down the spiral ramp (entrance at #COORD[32.16]#), at the bottom turn in #INThe Apple Falls# . Accept #GETDestiny Calls# ."},
      [6] = { str = "West in Darnassus, next to the red glowing teleporter, accept #GETThe Temple of the Moon# (#COORD[29.46]#)."},
      [7] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, then turn in #INThe Temple of the Moon# (#COORD[29.46]#), accept #GETTears of the Moon# ."},
      [8] = { str = "As you exit Temple of the Moon north, make a left then go to the ledge (#COORD[20.64]#) and walk off the right side of the tree to land on the other one directly below you so you can die and then res back at Teldrassil (saving 32 sec)."},
    },
  },
  [1003] = {
    title = "[Druid] Level 10 Class Quests",
    items = {
      [1] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [2] = { str = "Just south of the main path in Darnassus, accept #GETNessa Shadowsong# (#COORD[71.45]#)."},
      [3] = { str = "As you enter Darnassus, make a left after the ramp/purple rug, and go to the #NPCWeapon Master# and learn new weapon possibilities if you can afford to. You can revisit the #NPCWeapon Master# later to learn more. Also next to you, get repaired."},
      [4] = { str = "Go NW to Cenarion Enclave and turn in #INRellian Greenspyre# (#COORD[38.22]#), accept #GETTumors# ."},
      [5] = { str = "Just NW a bit, go straight forward to enter the tree tower (entrance at #COORD[35.10]#). Go to the middle level and turn in #INHeeding the Call# , accept #GETMoonglade# ."},
      [6] = { str = "Use your new spell #VIDEOTeleport: Moonglade# to take you to Moonglade."},
      [7] = { str = "Once teleported, go upstairs in the building in front of you and turn in #INMoonglade# , accept #GETGreat Bear Spirit# ."},
      [8] = { str = "Go west and do #DOGreat Bear Spirit# by talking to the #NPCGreat Bear Spirit# (#COORD[39.27]#)."},
      [9] = { str = "Use #VIDEOTeleport: Moonglade#. Once teleported go upstairs in the building and turn in #INGreat Bear Spirit# (#COORD[56.31]#, #2 on map), accept #GETBack to Darnassus# ."},
      [10] = { str = "Go SW to the Druid only #NPCDarnassus Flight Master# (#COORD[44.45]#) and take a flight to Rut'theran Village."},
      [11] = { str = "When you land go west and right off the dock turn in #INNessa Shadowsong# (#COORD[56.92]# in Teldrassil), accept #GETThe Bounty of Teldrassil# ."},
      [12] = { str = "Go up north to enter the red portal (#COORD[56.89]#)."},
      [13] = { str = "When you enter Darnassus and right next to the red portal, accept #GETThe Temple of the Moon# (#COORD[29.46]#)."},
      [14] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, then turn in #INThe Temple of the Moon# (#COORD[29.46]#), accept #GETTears of the Moon# ."},
      [15] = { str = "Go north to the Cenarion Enclave and at the middle level of the tree tower, turn in #INBack to Darnassus# (#COORD[35.8]#), accept #GETBody and Heart# ."},
      [16] = { str = "Go south to enter the red portal (#COORD[29.43]#)."},
      [17] = { str = "Go east on the bridge to the #NPCHippogryph Master# (#COORD[58.94]#) and turn in #INThe Bounty of Teldrassil# , accept #GETFlight to Auberdine# . Then take a ride to Auberdine, Darkshore."},
      [18] = { str = "Go down in the Inn at Auberdine and turn in #INFlight to Auberdine# (#COORD[37.44]#), accept #GETReturn to Nessa# ."},
      [19] = { str = "Go east a bit to the small cave and do #DOBody and Heart# : use the #ITEMCenarion Moondust# quest item on the #ITEMMoonkin Stone#, then kill #NPCLunaclaw# (lvl 12 owlbeast)."},
      [20] = { str = "Go west to the #NPCHippogryph Master# (#COORD[36.46]#) at Auberdine and fly to Rut'theran Village, Teldrassil."},
      [21] = { str = "Once you land, go west past the bridge a bit and turn in #INReturn to Nessa# (#COORD[56.92]# in Teldrassil)."},
      [22] = { str = "Go north to enter the red portal (#COORD[56.89]#)."},
      [23] = { str = "At Darnassus, go north to the Cenarion Enclave and at the middle level of the tree tower, turn in #INBody and Heart# (#COORD[35.8]#). You now have #VIDEOBear Form# along with a few abilities that go with it."},
      [24] = { str = "Exit Darnassus by heading east.."},
    },
  },
  [1004] = {
    title = "[Hunter] Level 10 Class Quests",
    items = {
      [1] = { str = "Hunter, Go NE (or south-west) a bit and do #DOTaming the Beast# : use the #ITEM Taming Rod# quest item on a #NPCWebwood Lurker# (around #COORD[60.60]#)."},
      [2] = { str = "Hunter, Go back to Dolanaar at the #NPCHunter Trainer# (#COORD[57.59]#, #1 on map) and turn in #INTaming the Beast# , accept the next #GETpart#."},
      [3] = { str = "Hunter, Go SE past Lake Al'Ameth and do #DOTaming the Beast# : use the #ITEMTaming Rod# quest item on a #NPCNightsaber Stalker# (around #COORD[63.73]#)."},
      [4] = { str = "Hunter, Die on purpose, to go back to Dolanaar. Then go to the #NPCHunter Trainer# (#COORD[57.59]#, #1 on map) and turn in #INTaming the Beast# , accept the next #GETpart#."},
      [5] = { str = "Hunter, Go SE past Lake Al'Ameth and do #DOTaming the Beast# : use the #ITEMTaming Rod# quest item on a #NPCStrigid Screecher# (around #COORD[65.67]#)."},
      [6] = { str = "Hunter, Die on purpose, to go back to Dolanaar. Then go to the #NPCHunter Trainer# (#COORD[57.59]#, #1 on map) and turn in #INTaming the Beast# , accept #GETTraining the Beast# ."},
      [7] = { str = "In the Inn, get repaired/resupplied (#COORD[56.59]#). Hunters, go to the #NPCBowyer# (in the Inn) and upgrade all your arrows to #ITEMSharp Arrows#."},
      [8] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [9] = { str = "Just south of the main path in Darnassus, accept #GETNessa Shadowsong# (#COORD[71.45]#)."},
      [10] = { str = "As you enter Darnassus, make a left after the ramp/purple rug, and go to the #NPCWeapon Master# and learn new weapon possibilities if you can afford to (make sure you have at least 5 silver left). You can revisit the #NPCWeapon Master# later to learn more. Also next to you, get repaired."},
      [11] = { str = "Hunter, Find the #NPCMeat Vendor#, she patrols counter-clockwise around the path at Tradesmen's Terrace (starting at #COORD[63.56]#) and stock up on meat so you can feed your future pet. I recommend getting about 40-60 of the #ITEMHaunch of Meat#."},
      [12] = { str = "Go NW to Cenarion Enclave and turn in #INRellian Greenspyre# (#COORD[38.22]#), accept #GETTumors# ."},
      [13] = { str = "Hunter, Go up the ramps just NE to the #NPCHunter Trainer# and turn in #INTraining the Beast# (#COORD[40.9]#). You now have a bunch of new pet abilities!"},
      [14] = { str = "West in Darnassus, next to the red glowing teleporter, accept #GETThe Temple of the Moon# (#COORD[29.46]#)."},
      [15] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, then turn in #INThe Temple of the Moon# (#COORD[29.46]#), accept #GETTears of the Moon# ."},
      [16] = { str = "As you exit Temple of the Moon north, make a left then go to the ledge (#COORD[20.64]#) and walk off the right side of the tree to land on the other one directly below you so you can die and then res back at Teldrassil (saving 32 sec)."},
      [17] = { str = "Hunter, Leave Darnassus and take the north path and tame a #NPCStrigid Hunter# (around #COORD[39.46]# in Teldrassil) as your main pet you will be using. Try to get a level 9. Be sure to put Claw Rank 2 on autocast and teach him Growl Rank 1 from the Beast Training in your Spellbook."},
    },
  },
  [1005] = {
    title = "[Priest] Level 10 Class Quest",
    items = {
      [1] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [2] = { str = "Just south of the main path in Darnassus, accept #GETNessa Shadowsong# (#COORD[71.45]#)."},
      [3] = { str = "As you enter Darnassus, make a left after the ramp/purple rug, and go to the #NPCWeapon Master# and learn new weapon possibilities if you can afford to. You can revisit the #NPCWeapon Master# later to learn more. Also next to you, get repaired."},
      [4] = { str = "Go NW to Cenarion Enclave and turn in #INRellian Greenspyre# (#COORD[38.22]#), accept #GETTumors# ."},
      [5] = { str = "West in Darnassus, next to the red glowing teleporter, accept #GETThe Temple of the Moon# (#COORD[29.46]#)."},
      [6] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, make a left and then turn in #INReturning Home# (#COORD[40.81]#). You now have #VIDEOStarshards# R1."},
      [7] = { str = "Go west a bit more and turn in #INThe Temple of the Moon# (#COORD[29.46]#), accept #GETTears of the Moon# ."},
      [8] = { str = "As you exit Temple of the Moon north, make a left then go to the ledge (#COORD[20.64]#) and walk off the right side of the tree to land on the other one directly below you so you can die and then res back at Teldrassil (saving 32 sec)."},
    },
  },
  [1012] = {
    title = "10-12 Teldrassil",
    items = {
      [1] = { str = "Go SW and do (if you have it) #DOUrsal the Mauler# : kill #NPCUrsal the Mauler# (lvl 12 grey furblog, #COORD[39.80]#)."},
      [2] = { str = "Right where #NPCUrsal the Mauler# was, die on purpose to get to Darnassus. NOTE: If you didn't have #DOUrsal the Mauler# quest, then just run up north to do the next steps:"},
      [3] = { str = "In western Teldrassil, follow the main path north to The Oracle Glade and at the end of the path, off to your right, accept #GETThe Enchanted Glade# (next to the Moonwell, #COORD[38.34]# in Teldrassil)."},
      [4] = { str = "Next to you, do #DOCrown of the Earth# : use the #ITEM Amethyst Phial# quest item in the Moonwell there."},
      [5] = { str = "As you do the following steps start working on #DOTumors# by kill/looting the Timberling mobs (#6 on map):"},
      [6] = { str = "Go east past the river and see if #NPCBlackmoss the Fetid# is there (a lvl 13 rare Elite at #COORD[44.30]# with a 2 hour respawn) and try to kill/loot this mob. He drops an #ITEMitem#, which starts #GETThe Moss-twined Heart# , accept it. Use the #ITEMSevered Voodoo Claw# to help you kill him. NOTE: If you cannot solo him or find help, then my guide will remind you later to try again."},
      [7] = { str = "Go NE and do #DOTears of the Moon# : kill/loot #NPC Lady Sathrah# (lvl 12 grey spider, around #COORD[48.25]#). NOTE: This spider has several different spawn locations, they will be updated for the guide eventually!"},
      [8] = { str = "Just west at Wellspring River (around #COORD[43.28]#, #6 on map), finish #DOTumors# : kill/loot Timberling mobs."},
      [9] = { str = "Rogue, Go NW on the big tree branch that extends from Teldrassil (around #COORD[37.23]#) and do #DODestiny Calls# : first use your #VIDEOStealth# and then use #VIDEOSap# & finally #VIDEOPick Pocket# ability on #NPCSethir the Ancient# (he patrols around on the big tree branch). It's best to execute the #VIDEOPick Pocket# ability as far away from him as possible. If you fail he will spawn minions, in which case it is best to #VIDEOSprint# away and try again."},
      [10] = { str = "Go west and from the #ITEMStrange Fronded Plant# (glowing red tree, #COORD[34.29]#), accept #GETThe Shimmering Frond# ."},
      [11] = { str = "In the immediate area do #DOThe Enchanted Glade# : kill/loot the Bloodfeather harpies. While doing this, work your way to the next step:"},
      [12] = { str = "Back in the harpy camp there is a black panther named #NPCMist# that starts an escort quest #GETMist# , accept it."},
      [13] = { str = "Make sure #DOThe Enchanted Glade# is finished, then lead #NPCMist# to the Moonwell at The Oracle Glade (#COORD[38.34]#, #4 on map) and then turn in #INThe Enchanted Glade# and #INMist# . Accept #GETTeldrassil# ."},
      [14] = { str = "If you need to, check again to see if #NPCBlackmoss the Fetid# is there (a lvl 13 rare Elite at #COORD[44.30]#, #7 on map). Having a group helps, but you can attempt to solo him. Try to kill/loot this mob, he drops an #ITEMitem#, which starts #GETThe Moss-twined Heart# , accept it. NOTES: This mob has a 2 hour respawn, and if he is not there or you cannot kill him, then it can be skipped."},
      [15] = { str = "Go west of the main path at The Oracle Glade, then die on purpose to get to Darnassus."},
      [16] = { str = "Warrior, Go west into Darnassus to #NPCElanaria# (#COORD[57.34]#) and turn in #INVorlus Vilehoof# . Accept #GETThe Shade of Elura# ."},
      [17] = { str = "In Darnassus, go NW to Cenarion Enclave and turn in #INTumors# (#COORD[38.22]# in Darnassus), accept #GETReturn to Denalan# ."},
      [18] = { str = "Follow the path straight forward and go up in the tree tower and turn in #INTeldrassil# (#COORD[35.9]#), accept #GETGrove of the Ancients# ."},
      [19] = { str = "Rogue, Just south a bit, go down the spiral ramp (entrance at #COORD[32.16]#), at the bottom turn in #INDestiny Calls# ."},
      [20] = { str = "Go south in Darnassus to enter Temple of the Moon, go up the ramp, then turn in #INTears of the Moon# (#COORD[29.46]#), accept #GETSathrah's Sacrifice# ."},
      [21] = { str = "Next to you, do #DOSathrah's Sacrifice# : drop down and use the #ITEMSathrah's Sacrifice# quest item at the fountain in the middle of the temple."},
      [22] = { str = "Go back up the ramp in the Temple of the Moon and turn in #INSathrah's Sacrifice# (#COORD[29.46]#, #4 on map)."},
      [23] = { str = "Hearth to Dolanaar."},
      [24] = { str = "In the Inn, get repaired/resupplied."},
      [25] = { str = "At the entrance of the tree tower at Dolanaar, turn in (if you have it) #INUrsal the Mauler# (#COORD[56.57]#)."},
      [26] = { str = "Go south to the Moonwell at Dolanaar and turn in #INCrown of the Earth# (#COORD[56.62]#), accept the next #GETpart#. Also turn in #INRecipe of the Kaldorei# at the #NPCCook# (#COORD[57.61]#) if its finished. If you turned level 12, then get new spells abilities. Hunters, go just to the east outside of the Inn to find the HUNTER: #NPCHunter Trainer# (#COORD[57.59]#).]Go in the bottom part of the Inn to find the WARRIOR: #NPCWarrior Trainer# (#COORD[56.59]#).]Go in the bottom part of the Inn to find the ROGUE: #NPCRogue Trainer# (#COORD[56.59]#).]Go in the bottom of the tree tower to find the PRIEST: #NPCPriest Trainer# (#COORD[56.57]#).]The DRUID: #NPCDruid Trainer# (#COORD[56.62]#) is right next to the moonwell at Dolanaar.]"},
      [27] = { str = "Go SE to the small camp at Lake Al'Ameth (#COORD[61.68]#) and turn in (if you have it) #INThe Moss-twined Heart# , accept (if it's available) #GETPlanting the Heart# ."},
      [28] = { str = "Next to you, click on #ITEM Denalan's Planter# to turn in (if you have it) #INPlanting the Heart# ."},
      [29] = { str = "Also turn in #INThe Glowing Fruit# , #INThe Shimmering Frond# and #INReturn to Denalan# , accept #GETOakenscowl# . Then, next to you, click on the #ITEMSprouted Frond# in the planter to complete #INThe Sprouted Fronds# ."},
      [30] = { str = "Go west to the small cave at Lake Al'Ameth and try to do #DOOakenscowl# (Elite): kill/loot #NPCOakenscowl# (lvl 9 Elite at #COORD[54.75]#). Try to get some help if you can, or you can try to solo him. He shouldn't be too hard at level 12, but be prepared and use a #ITEMSprouted Frond# and the #ITEMSevered Voodoo Claw# to help."},
      [31] = { str = "If you did #INOakenscowl# , go back east to the small camp at Lake Al'Ameth and turn it in (#COORD[61.68]#)."},
      [32] = { str = "You should be level 12 by now, if not grind on mobs south of Lake Al'Ameth until you are. Then die on purpose (or run back) to Dolanaar to get new spells/abilities & repaired/resupplied. Hunters, go just to the east outside of the Inn to find the HUNTER: #NPCHunter Trainer# (#COORD[57.59]#).]Go in the bottom part of the Inn to find the WARRIOR: #NPCWarrior Trainer# (#COORD[56.59]#).]Go in the bottom part of the Inn to find the ROGUE: #NPCRogue Trainer# (#COORD[56.59]#).]Go in the bottom of the tree tower to find the PRIEST: #NPCPriest Trainer# (#COORD[56.57]#).]The DRUID: #NPCDruid Trainer# (#COORD[56.62]#) is right next to the moonwell at Dolanaar.]"},
      [33] = { str = "Follow the main path west and then just past the blue bridge (around #COORD[43.51]#), die on purpose to get to Darnassus quicker."},
      [34] = { str = "Go NW in Darnassus and go up to the top of the tree tower and turn in #INCrown of the Earth# (#COORD[35.9]#)."},
      [35] = { str = "Go south in Darnassus and enter the red glowing teleporter (#COORD[28.42]#)."},
      [36] = { str = "Once at Rut'theran Village, go down the path and turn in #INNessa Shadowsong# (#COORD[56.92]# in Teldrassil), accept #GETThe Bounty of Teldrassil# ."},
      [37] = { str = "Go east on the bridge to the #NPCHippogryph Master# and turn in #INThe Bounty of Teldrassil# (#COORD[58.94]#), accept #GETFlight to Auberdine# . Then take a ride to Auberdine, Darkshore."},
      [38] = { str = "Go down in the Inn at Auberdine and turn in #INFlight to Auberdine# (#COORD[37.44]#), accept #GETReturn to Nessa# ."},
      [39] = { str = "Warrior, Go out in the sea to the west and do #DOThe Shade of Elura# : loot the #ITEMCrate of Elunite# boxes around the sunken ships and kill/loot #NPCShade of Elura# (#COORD[32.45]#)."},
      [40] = { str = "Go back up to the #NPCHippogryph Master# at Auberdine and fly to Rut'theran Village, Teldrassil."},
      [41] = { str = "Go west past the bridge a bit and turn in #INReturn to Nessa# (#COORD[56.92]# in Teldrassil)."},
      [42] = { str = "Warrior, Go north through the red portal (#COORD[56.89]#) to enter Darnassus."},
      [43] = { str = "Warrior, Go east in Darnassus to #NPCElanaria# (#COORD[57.34]#) and turn in #INThe Shade of Elura# , accept #GETSmith Mathiel# ."},
      [44] = { str = "Warrior, Go just south a bit to the other side of the platform your on, to #NPCMathiel# (#COORD[59.45]#) and turn in #INSmith Mathiel# . Wait a few seconds, then accept and complete #INWeapons of Elunite# . Get repaired/resupplied next to you."},
      [45] = { str = "Warrior, Go south through the red portal (#COORD[28.40]#, #6 on map)."},
      [46] = { str = "Go back east on the bridge to the #NPCHippogryph Master# (#COORD[58.94]#) and fly to Auberdine, Darkshore."},
      [47] = { str = "Go SE on the bridge to the #NPCHippogryph Master# (#COORD[58.94]#) and fly to Auberdine, Darkshore."},
    }
  },
}