--[[--------------------------------------------------
002_ElwynnForest.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 001 Elwynn Forest
1.04.1
-- First Release
Human Elwynn Forest's Guide
from level 1 to lever 12
1.04.2
-- no changes in here for this revision

Faelwen
04 June 2019 - Guide replaced with Joanna's Alliance Guide (https://www.joanasworld.com/alliance-1-12-elwynn-forest.html)

------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_002_ElwynnForest = {
  [0106] = {
    title = "1-6 Northshire",
    items = {
      [1] = { str = "Next to you, go in Northshire Abbey and turn in #INA Threat Within# (#COORD[49.42]#), accept #GETKobold Camp Cleanup# ."},
      [2] = { str = "Just outside of Northshire Abbey's entrance, from #NPCDeputy Willem#, accept #GETEagan Peltskinner# (#COORD[48.43]#, #1 on map)."},
      [3] = { str = "Outside on the NW side yard of Northshire Abbey, turn in #INEagan Peltskinner# (#COORD[49.40]#), accept #GETWolves Across the Border# ."},
      [4] = { str = "Do #DOKobold Camp Cleanup# along with #DOWolves Across the Border# : kill 10 #NPCKobold Vermins# and kill/loot wolves. The Kobolds are just north of Northshire Abbey (#5 on map) and the #ITEMwolves# are scattered all around the starting zone (but west of the river)."},
      [5] = { str = "Outside on the NW side yard of Northshire Abbey, turn in #INWolves Across the Border# (#COORD[49.40]#, #4 on map)."},
      [6] = { str = "In front of the wagon & red tent, make sure you are repaired/resupplied (#COORD[47.41]#)."},
      [7] = { str = "Just inside of Northshire Abbey, turn in #INKobold Camp Cleanup# (#COORD[49.42]#, #2 on map). Accept #GETInvestigate Echo Ridge# and your class's quest #GETTainted Letter# WARRIOR: #GETSimple Letter# ] PALADIN: #GETConsecrated Letter# ] ROGUE: #GETEncrypted Letter# ] PRIEST: #GETHallowed Letter# ] MAGE: #GETGlyphic Letter# ] ."},
      [8] = { str = "Warrior, Just east inside of Northshire Abbey, at the #NPCWarrior Trainer# (#COORD[50.42]#), turn in #INSimple Letter# and learn #VIDEOBattle Shout# R1."},
      [9] = { str = "Paladin, Just east inside of Northshire Abbey, at the #NPCPaladin Trainer# (#COORD[50.42]#), turn in #INConsecrated Letter# and learn #VIDEODevotion Aura# R1."},
      [10] = { str = "Priest, Make a left inside of Northshire Abbey then stay at the bottom floor at the Library Wing to get to the #NPCPriest Trainer# (#COORD[50.40]#), then turn in #INHallowed Letter# and learn #VIDEOPower Word: Fortitude# R1."},
      [11] = { str = "Mage, Make a left inside of Northshire Abbey then go up the steps at the Library Wing to get to the #NPCMage Trainer# (#COORD[50.40]#), then turn in #INGlyphic Letter# and learn #VIDEOArcane Intellect# R1."},
      [12] = { str = "Just outside of Northshire Abbey's entrance, from #NPCDeputy Willem#, accept #GETBrotherhood of Thieves# (#COORD[48.43]#, #1 on map)."},
      [13] = { str = "Rogue, Go to the Stables on the NE side-yard of Northshire Abbey and from the #NPCRogue Trainer# (#COORD[50.40]#), turn in #INEncrypted Letter# and learn #VIDEO Stealth# R1."},
      [14] = { str = "Warlocks, Go to the east outside graveyard of Northshire Abbey and turn in #INTainted Letter# (#COORD[50.43]#). Accept #GETThe Stolen Tome# . Also learn #VIDEOImmolate# R1."},
      [15] = { str = "Warlocks, Go east across the river to the Defias camp and do #DOThe Stolen Tome# : loot the #ITEMStolen Books# on the ground in front of the tent (#COORD[57.44]#)."},
      [16] = { str = "Warlocks, Go to the east outside graveyard of Northshire Abbey and turn in #INThe Stolen Tome# (#COORD[50.43]#, #9a on map). Get your Imp out!"},
      [17] = { str = "Go east past the river and do #DOBrotherhood of Thieves# : kill/loot the #NPCDefias Thugs#."},
      [18] = { str = "Rogue, Grind your way NW to the #NPCRogue Trainer# (#COORD[50.40]#) at the Stables, make sure you are level 4 before getting there, then learn new abilities."},
      [19] = { str = "Go north of Northshire Abbey and do #DOInvestigate Echo Ridge# : kill 10 #NPCKobold Workers#. There are multiple camps up north and there is a larger concentration before the cave entrance (around #COORD[48.33]#)."},
      [20] = { str = "Just outside of Northshire Abbey's entrance, from #NPCDeputy Willem#, turn in #INBrotherhood of Thieves# (#COORD[48.43]#). Accept #GETBounty on Garrick Padfoot# and #GETMilly Osworth# ."},
      [21] = { str = "Go inside of Northshire Abbey and turn in #INInvestigate Echo Ridge# (#COORD[49.42]#), accept #GETSkirmish at Echo Ridge# ."},
      [22] = { str = "Warrior, Go east inside of Northshire Abbey to the #NPCWarrior Trainer# (#COORD[50.42]#) and learn new abilities."},
      [23] = { str = "Paladin, Go east inside of Northshire Abbey to the #NPCPaladin Trainer# (#COORD[50.42]#) and learn new abilities."},
      [24] = { str = "Priest, Make a left inside of Northshire Abbey then stay at the bottom floor at the Library Wing to get to the #NPCPriest Trainer# (#COORD[50.42]#), then learn new abilities."},
      [25] = { str = "Mage, Make a left inside of Northshire Abbey then go up the steps at the Library Wing to get to the #NPCMage Trainer# (#COORD[50.42]#), then learn new spells/abilities."},
      [26] = { str = "Just outside of Northshire Abbey make sure you are repaired/resupplied (#COORD[47.41]#)."},
      [27] = { str = "Go in the Echo Ridge Mine up north (entrance at #COORD[48.31]#) and do #DOSkirmish at Echo Ridge# : kill 12 #NPCKobold Laborers#."},
      [28] = { str = "Go to the NE outside of Northshire Abbey (next to the stables/wagon) and turn in #INMilly Osworth# (#COORD[51.39]#), accept #GETMilly's Harvest# ."},
      [29] = { str = "Go east across the river to Northshire Vineyards (around #COORD[54.49]#) and do #DOMilly's Harvest# : loot #ITEMMilly's Harvest# (crates) on the ground around the farm. Keep the next step in mind:"},
      [30] = { str = "Just east of the Northshire Vineyards do #DOBounty on Garrick Padfoot# : kill/loot #NPCGarrick Padfoot# (in front of the shack, #COORD[57.48]#)."},
      [31] = { str = "Go to the NE outside of Northshire Abbey (next to the stables/wagon) and turn in #INMilly's Harvest# (#COORD[51.39]#, #5 on map), accept #GETGrape Manifest# ."},
      [32] = { str = "In front of Northshire Abbey's entrance, from #NPCDeputy Willem#, turn in #INBounty on Garrick Padfoot# (#COORD[48.43]#, #1 on map)."},
      [33] = { str = "Just inside of Northshire Abbey, turn in #INSkirmish at Echo Ridge# (#COORD[49.42]#, #2 on map). Accept #GETReport to Goldshire# ."},
      [34] = { str = "Make a right inside of Northshire Abbey, then go up through the spiral staircase to the top of the Abbey and turn in #INGrape Manifest# ."},
      [35] = { str = "Priest, Drop down at the bottom floor then go north to the #NPCPriest Trainer# (#COORD[50.42]#), and accept #GETIn Favor of the Light# ."},
      [36] = { str = "Go outside of Northshire Abbey and make sure you are repaired/resupplied (#COORD[47.41]#, #3 on map)."},
      [37] = { str = "Leave Northshire Valley by heading SW (exit at #COORD[47.48]#)."},
      [38] = { str = "In front of the lion fountain, accept #GETRest and Relaxation# (#COORD[46.48]#)."},
    },
  },
  [0611] = {
    title = "6-11 Goldshire",
    items = {
      [1] = { str = "Enter Goldshire's Inn (entrance at #COORD[43.66]#). Make a left and accept #GETKobold Candles# ."},
      [2] = { str = "Next to you at #NPCInnkeeper Farley#, turn in #INRest and Relaxation# . Also make Goldshire your new home for your Hearthstone from the Innkeeper."},
      [3] = { str = "Go upstairs in the Inn and in the middle room from the #NPCPhysician#, learn Apprentice First Aid."},
      [4] = { str = "Get new spells/abilities at Goldshire. Warlocks go down in the basement of the Inn to find the #NPCWarlock Trainer#.The WARRIOR: #NPCWarrior Trainer# (#COORD[41.66]#) is on the outside western entrance of the refinery.]The PALADIN: #NPCPaladin Trainer# (#COORD[41.66]#) is on the outside western entrance of the refinery.]The ROGUE: #NPCRogue Trainer# (#COORD[44.66]#) is next to you in the other room.]At the PRIEST: #NPCPriest Trainer# next to you, turn in #INIn Favor of the Light# , accept #GETGarments of the Light# and get your level 6 spells.]The MAGE: #NPCMage Trainer# (#COORD[43.66]#) is next to you in the other room.]"},
      [5] = { str = "On the south side of Goldshire by the wagon, accept #GETGold Dust Exchange# (#COORD[42.67]#)."},
      [6] = { str = "Priest, Go east at Crystal Lake and do #DOGarments of the Light# : at #NPCGuard Roberts# (#COORD[47.67]#) next to the lake, use #VIDEOLesser Heal# R2 and then #VIDEOPower Word: Fortitude# on him."},
      [7] = { str = "Priest, Go back west to Goldshire and upstairs in the Inn at the #NPCPriest Trainer#, turn in #INGarments of the Light# (#COORD[43.66]#, #2 on map)."},
      [8] = { str = "Go SW to The Stonefield Farm and next to the house (#COORD[35.84]#), accept #GETLost Necklace# and #GETPrincess Must Die!# ."},
      [9] = { str = "Go east to The Maclure Vineyards and in front of the barn turn in #INLost Necklace# (#COORD[43.86]#), accept #GETPie for Billy# . "},
      [10] = { str = "Go south in The Maclure Vineyards and in the small house, accept #GETYoung Lovers# (#COORD[43.90]#)."},
      [11] = { str = "Go west to The Stonefield Farm and next to the river turn in #INYoung Lovers# (#COORD[30.86]#), accept #GETSpeak with Gramma# . ALSO: While on your way, grind on Boars to collect 4 #ITEMChunk of Boar Meats# (for a future #DOquest#), and don't sell them to a vendor!"},
      [12] = { str = "In the small house east in The Stonefield Farm, turn in #INSpeak with Gramma# (#COORD[35.84]#, #7 on map), accept #GETNote to William# ."},
      [13] = { str = "All around southern Elwynn Forest do #DOPie for Billy# : kill/loot Boars. NOTE: You may already have the 4 #ITEMChunk of Boar Meats# by grinding previously!"},
      [14] = { str = "At the small house in The Stonefield Farm, next to the well (#COORD[35.84]#, #7 on map), turn in #INPie for Billy# , accept #GETBack to Billy# ."},
      [15] = { str = "Go east to The Maclure Vineyards and in front of the barn turn in #INBack to Billy# (#COORD[43.86]#, #8 on map), accept #GETGoldtooth# ."},
      [16] = { str = "Go NW to Fargodeep Mine and take the upper mine entrance (#COORD[39.83]#). Keep hugging the left side of the mine until you get to #NPCGoldtooth# and kill/loot him for #DOGoldtooth# . Then make sure #DOGold Dust Exchange# along with #DOKobold Candles# is finished by kill/looting the Kobolds inside or outside the mine."},
      [17] = { str = "Hearth to Goldshire."},
      [18] = { str = "In the Inn, near the entrance, turn in #INKobold Candles# (#COORD[43.66]#), accept #GETShipment to Stormwind# . Also turn in #INNote to William# , accept #GETCollecting Kelp# ."},
      [19] = { str = "Exit the Inn and on the south side of Goldshire by the wagon, turn in #INGold Dust Exchange# (#COORD[42.67]#). Accept #GETA Fishy Peril# ."},
      [20] = { str = "In front of the refinery, turn in #INA Fishy Peril# , accept #GETFurther Concerns# . Also turn in #INThe Fargodeep Mine# (#COORD[42.66]#), accept #GETThe Jasperlode Mine# . Make sure you are repaired/resupplied (in the refinery)."},
      [21] = { str = "Go east a bit to Crystal Lake (around #COORD[50.67]#) and do #DOCollecting Kelp# : kill/loot the murlocs around the lake."},
      [22] = { str = "Go NE and enter Jasperlode Mine (entrance at #COORD[62.53]#) and do #DOThe Jasperlode Mine# : work your way into the mine until you get it scouted."},
      [23] = { str = "Go SE to the bridge where the main path and the river meet (make sure you are at least 420xp away from lvl 8) and then turn in #INFurther Concerns# (#COORD[74.72]#), accept #GETFind the Lost Guards# and #GETProtect the Frontier# ."},
      [24] = { str = "Go NE a bit to Eastvale Logging Camp at the small house and accept #GETRed Linen Goods# (#COORD[80.69]#)."},
      [25] = { str = "NE a bit more, next to the wagon, accept #GETA Bundle of Trouble# (#COORD[81.66]#)."},
      [26] = { str = "Just east, you can go to the #NPCBowyer# (#COORD[83.66]#) to get repaired/resupplied."},
      [27] = { str = "Go just north of Eastvale Logging Camp (around #COORD[80.61]#) and start working on #DOProtect the Frontier# and #DOA Bundle of Trouble# : kill #NPC Prowlers# (wolves) and #NPCYoung Forest Bears#. Also loot the #ITEMBundle of Wood# around the trees. Work your way to the next step:"},
      [28] = { str = "Grind NW to the shore and click on #ITEMA half-eaten body# (#COORD[73.60]#) to turn in #INFind the Lost Guards# , accept #GETDiscover Rolf's Fate# ."},
      [29] = { str = "Go NE next to the murloc camp (watch out for the multiple murlocs) and click on #ITEMRolf's corpse# (#COORD[80.55]#) to turn in #INDiscover Rolf's Fate# , accept #GETReport to Thomas# ."},
      [30] = { str = "Make sure #DOA Bundle of Trouble# is finished by looting the #ITEMBundle of Wood# around the trees north of Eastvale Logging Camp. And continue working on #DOProtect the Frontier# by killing #NPC Prowlers# (wolves, #1 on map) and #NPCYoung Forest Bears#."},
      [31] = { str = "Go to the middle of Eastvale Logging Camp, next to the wagon and turn in #INA Bundle of Trouble# (#COORD[81.66]#)."},
      [32] = { str = "You can go east a bit to the #NPCBowyer# (#COORD[83.66]#) to get repaired/resupplied."},
      [33] = { str = "As you work on the following steps, continue working on #DOProtect the Frontier# by killing #NPC Prowlers# (wolves) and #NPCYoung Forest Bears#:"},
      [34] = { str = "Go SE to the Defias camp (around #COORD[89.79]#) and start working on #DORed Linen Goods# : kill/loot the Defias mobs for the #ITEMbandanas#. If you run out of mobs, just continue on to the next steps:"},
      [35] = { str = "Grind west to Brackwell Pumpkin Patch (around #COORD[70.79]#) and finish working on #DORed Linen Goods# : kill/loot the Defias mobs for the #ITEMbandanas# around the farm. NOTE: Any of the Defias mobs has a very low chance to drop an item called #ITEMWestfall Deed#, which starts #GETFurlbrow's Deed# (accept it if you are able to find it). Keep the next step in mind:"},
      [36] = { str = "At Brackwell Pumpkin Patch, if you can find a small group, you can try to do #DOPrincess Must Die!# : kill/loot #NPCPrincess#. This lvl 9 boar patrols around the farm and has two #NPClvl 7 bodyguards#. If you cannot find a group, then you can try to solo it (warning its tough), but there's another chance to do this later."},
      [37] = { str = "Make sure #DOProtect the Frontier# is finished: kill #NPC Prowlers# and #NPCYoung Forest Bears#. NOTE: The #NPCYoung Forest Bears# are sporadically spaced around southern Elwynn Forest (see map)."},
      [38] = { str = "Go to where the main path and the river meets (#COORD[74.72]#) and turn in #INProtect the Frontier# and #INReport to Thomas# , accept #GETDeliver Thomas' Report# . Also accept #GETReport to Gryan Stoutmantle# ."},
      [39] = { str = "Go NE a bit to Eastvale Logging Camp and at the small house turn in #INRed Linen Goods# (#COORD[79.69]#)."},
      [40] = { str = "Hearth to Goldshire."},
      [41] = { str = "In the Inn, near the entrance, turn in #INCollecting Kelp# (#COORD[43.66]#). Wait a few seconds, then accept #GETThe Escape# ."},
      [42] = { str = "Just outside of the Inn, in front of the refinery (#COORD[42.66]#), turn in #INDeliver Thomas' Report# , accept #GETCloth and Leather Armor# . Also turn in #INThe Jasperlode Mine# . Accept #GETWestbrook Garrison Needs Help!# ."},
      [43] = { str = "Go into the refinery next to you and accept #GETElmore's Task# (#COORD[42.66]#). Make sure you are repaired/resupplied."},
      [44] = { str = "Warrior, Make sure you are level 10. If you are close to it then grind on any mobs right around Goldshire until you are. You can also do the next few turn-ins to achieve more XP. Then once you are level 10, accept your Warrior's level 10 quest #GETA Warrior's Training# from the #NPCWarrior Trainer# (#COORD[41.66]#) on the outside western entrance of the refinery at Goldshire. Also get new abilities."},
      [45] = { str = "Paladin, Make sure you are level 10. If you are close to it then grind on any mobs right around Goldshire until you are. You can also do the next few turn-ins to achieve more XP. Then once you are level 10, get new spells/abilities from the #NPCPaladin Trainer# (#COORD[41.66]#) on the outside western entrance of the refinery at Goldshire."},
      [46] = { str = "Rogue, Make sure you are level 10. If you are close to it then grind on any mobs right around Goldshire until you are. You can also do the next few turn-ins to achieve more XP. Then once you are level 10, accept your Rogue's level 10 quest #GETSeek out SI: 7# from the #NPCRogue Trainer# (#COORD[41.66]#) upstairs in the Inn at Goldshire. Also get new abilities."},
      [47] = { str = "Rogue, Make sure you are level 10. If you are close to it then grind on any mobs right around Goldshire until you are. You can also do the next few turn-ins to achieve more XP. Then once you are level 10, accept your Priest's level 10 quest #GETDesperate Prayer# from the #NPCPriest Trainer# (#COORD[41.66]#) upstairs in the Inn at Goldshire. Also get new spells/abilities."},
      [48] = { str = "Mage, Make sure you are level 10. If you are close to it then grind on any mobs right around Goldshire until you are. You can also do the next few turn-ins to achieve more XP. Then once you are level 10, accept your Mage's level 10 quest #GETSpeak with Jennea# from the #NPCMage Trainer# (#COORD[41.66]#) upstairs in the Inn at Goldshire. Also get new spells/abilities."},
      [49] = { str = "Go south to The Maclure Vineyards and in the small house, turn in #INThe Escape# (#COORD[43.90]#)."},
      [50] = { str = "Go west to The Stonefield Farm and in front of the small house, turn in (if you did it) #INPrincess Must Die!# (#COORD[35.84]#). And next to you, turn in #INGoldtooth# ."},
      [51] = { str = "Go NW to Westbrook Garrison and in front of the garrison's entrance, turn in #INWestbrook Garrison Needs Help!# (#COORD[24.74]#), accept #GETRiverpaw Gnoll Bounty# ."},
      [52] = { str = "Next to you from the Wanted Poster, accept #GETWanted: Hogger# ."},
    },
  },
  [1111] = {
    title = "11-11 Westfall + Stormwind",
    items = {
      [1] = { str = "Follow the main path south and off to your right go in the house at Saldean's Farm and turn in #INWestfall Stew# (#COORD[56.30]#), SKIP the next #DOpart#."},
      [2] = { str = "Go south to Sentinel Hill at the tower and turn in #INReport to Gryan Stoutmantle# (#COORD[56.47]#)."},
      [3] = { str = "Back inside the tower, accept #GETA Swift Message# (#COORD[57.47]#)."},
      [4] = { str = "Just south of the tower, at the #NPCGryphon Master# (#COORD[57.53]#), turn in #INA Swift Message# , accept #GETContinue to Stormwind# . Then take a flight to Stormwind, Elwynn."},
      [5] = { str = "In Stormwind, go to Old Town and in the Limited Immunity, turn in #INContinue to Stormwind# (#COORD[74.47]#), accept #GETDungar Longdrink# ."},
      [6] = { str = "Rogue, Go SE and upstairs in SI:7 turn in #INSeek out SI: 7# (#COORD[76.60]#). Accept #GETSnatch and Grab# ."},
      [7] = { str = "Warrior, Just north a bit, enter Pig and Whistle Tavern and turn in your Warrior quest #INA Warrior's Training# (#COORD[74.37]#), accept #GETBartleby the Drunk# ."},
      [8] = { str = "Warrior, Next to you in the bar, turn in #INBartleby the Drunk# , accept and do #DOBeat Bartleby# by defeating #NPCBartleby# to a duel. Then turn it in and accept #GETBartleby's Mug# ."},
      [9] = { str = "Warrior, Next to you in the bar, turn in #INBartleby's Mug# . Accept #GETMarshal Haggard# . Note the new abilities learned."},
      [10] = { str = "Priest, Go north to the Cathedral Square and turn in #INDesperate Prayer# (#COORD[39.26]#). You now have #VIDEODesperate Prayer# R1."},
      [11] = { str = "Near the entrance in Stormwind, enter Pestle's Apothecary and turn in #INShipment to Stormwind# (#COORD[56.65]#)."},
      [12] = { str = "Slightly north, you can go in Weller's Arsenal and from the #NPCWeapon Master# (#COORD[57.58]#), you can learn new weapon possibilities if you can afford to."},
      [13] = { str = "Mage, Go west to The Mage Quarter and then go up the spiral ramp (entrance at #COORD[39.82]#) and inside the portal to Wizard's Sanctum and then turn in #INSpeak with Jennea# , accept #GETMirror Lake# ."},
      [14] = { str = "Go east to the #NPCGryphon Master# (#COORD[66.62]#) in Stormwind and turn in #INDungar Longdrink# , accept #GETReturn to Lewis# . Then fly to Sentinel Hill, Westfall."},
      [15] = { str = "In Westfall, go north a bit inside the tower and turn in #INReturn to Lewis# (#COORD[57.47]#, #3 on map)."},
      [16] = { str = "You should be level 10 by now, if not grind on any mob until you are."},
      [17] = { str = "Go SW in Stormwind and enter The Slaughtered Lamb, then go down in the basement and turn in (if you have it) #INGakin's Summons# , accept #GETSurena Caledon# . Also get new spells/abilities."},
      [18] = { str = "Go east to the #NPCGryphon Master# (#COORD[66.62]#) in Stormwind and turn in #INDungar Longdrink# , accept #GETReturn to Lewis# . Then fly to Sentinel Hill, Westfall."},
      [19] = { str = "In Westfall, go north a bit inside the tower and turn in #INReturn to Lewis# (#COORD[57.47]#)."},
      [20] = { str = "Hearth to Goldshire (if you can), then go east to Brackwell Pumpkin Patch and in the small house do #DOSurena Caledon# : kill/loot #NPCSurena Caledon# (#COORD[71.81]# in Elwynn Forest)."},
      [21] = { str = "Hearth to Goldshire (if you can), then go back to Stormwind at the Mage Quarter down in The Slaughtered Lamb and turn in #INSurena Caledon# (# 2a on map), accept #GETThe Binding# ."},
      [22] = { str = "Next to you, go down the spiral ramp, then make a right and keep going down until you get to the purple summoning circle and do #DOThe Binding# : use the #ITEMBloodstone Choker# quest item there, then kill the voidwalker that spawns."},
      [23] = { str = "Go back up and turn in #INThe Binding# . You can now summon a Voidwalker!"},
    },
  },
  [1112] = {
    title = "11-12 Elwynn Forest",
    items = {
      [1] = { str = "If you have a group you can try to do #DOWanted: Hogger# : kill/loot #NPCHogger# (lvl 11 Elite gnoll). If you don't have a group, you can attempt to solo him if you dare, if not it can be skipped."},
      [2] = { str = "Go north to Westbrook Garrison and in front of the entrance, turn in #INRiverpaw Gnoll Bounty# (#COORD[24.74]#)."},
      [3] = { str = "Mage, Go north to Mirror Lake and do #DOMirror Lake# : use #ITEM Jennea's Flask# quest item at the bottom of the waterfall (#COORD[29.61]#)."},
      [4] = { str = "Rogue, Go SE to the small house with a dock next to it and do #DOSnatch and Grab# : first use your #VIDEOStealth# and then use the #VIDEOPick Pocket# ability on the #NPCDefias Dockmaster# (#COORD[48.87]#). TIPS: Be careful there is 3 #NPCDefias Dockworkers# that patrol around the area. It's usually safer to wait until Dockmaster patrols in the house and faces the fireplace to execute this."},
      [5] = { str = "Paladin, Make sure you have the #ITEMGold Pickup Schedule# item, which starts #GETThe Collector# . Keep grinding on gnolls until you obtain it (#1 on map). If you happen to turn level 12 while grinding then skip to the next step below. Also make sure you save 10 #ITEMLinen Cloth# for a later #DOquest#."},
      [6] = { str = "Paladin, If you are not level 12 yet and have obtained #DOThe Collector# , keep grinding on gnolls (#1 on map) until you are 200xp away from lvl 12 (or 875xp if you did #DOWanted: Hogger# , or 1,000xp if you did both #DOWanted: Hogger# & #DOThe Collector# )."},
      [7] = { str = "Die on purpose (res at spirit) to get back to Goldshire and in front of the refinery (#COORD[42.66]#), turn in (if you have it) #INThe Collector# and (if you did it) #INWanted: Hogger# . If it's available, accept #GETManhunt# ."},
      [8] = { str = "Paladin, You should be level 12 right now. Go to the #NPCPaladin Trainer# (#COORD[41.66]#) on the outside western entrance of the refinery at Goldshire and accept your class's level 12 quest #GETTome of Divinity# . Also get your level 12 spells/abilities."},
      [9] = { str = "Paladin, Go NW to Stormwind and then NW to the Cathedral Square and turn in #INTome of Divinity# (#COORD[40.30]#), accept #GETThe Tome of Divinity#. Then turn it in right there and accept the next #GETpart# from the #ITEMitem# received. Then turn that in right there and accept the next #GETpart#."},
      [10] = { str = "Paladin, Go SE in Stormwind to the Trade District and turn in #INThe Tome of Divinity# (#COORD[57.62]#), accept and turn in the next #INpart# (with 10 #ITEMLinen Cloth#). Then accept the next #GETpart#."},
      [11] = { str = "Paladin, Go back NW to the Cathedral Square and turn in #INThe Tome of Divinity# (#COORD[40.30]#, #4b on map), accept the next #GETpart#."},
      [12] = { str = "Paladin, Across the room and up the steps, turn in #INThe Tome of Divinity# (#COORD[39.26]#), accept the next #GETpart#."},
      [13] = { str = "Paladin, Go into the water at the Canals (rivers running through Stormwind) and drown/die on purpose (then res at spirit) to get to Goldshire."},
      [14] = { str = "Go east on the main path and at the bridge/river accept #GETBounty on Murlocs# (#COORD[74.72]#)."},
      [15] = { str = "Do (if you have it) #DOManhunt# : go SW to Brackwell Pumpkin Patch and in the small house kill/loot #NPCMorgan the Collector#. ALSO: If you haven't yet, at Brackwell Pumpkin Patch you can try to do #DOPrincess Must Die!# : kill/loot #NPCPrincess#. This lvl 9 boar patrols around the farm and has two #NPClvl 7 bodyguards#. Try to team up with someone in the area if you can or you can try to solo it. If you can't do it, then skip it."},
      [16] = { str = "Do #DOBounty on Murlocs# : kill/loot Murlocs along the coast of the river south running through Elwynn Forest."},
      [17] = { str = "Go back to the bridge where the main path and the river meet and turn in #INBounty on Murlocs# (#COORD[74.72]#, #5 on map)."},
      [18] = { str = "Go NE to Eastvale Logging Camp and at the small house turn in #INCloth and Leather Armor# (#COORD[80.69]#)."},
      [19] = { str = "Paladin, Go north to the island at Stone Cairn Lake and do #DOThe Tome of Divinity# : use the #ITEMSymbol of Life# quest item at the corpse of #NPCHenze Faulk# (#COORD[73.51]#). Then turn in #INThe Tome of Divinity# , accept the next #GETpart#."},
      [20] = { str = "Paladin, In the immediate area around the island do #DOThe Tome of Divinity# : kill/loot #NPCDefias Rogue Wizards# until the #ITEMDefias Script# drops."},
      [21] = { str = "Warrior, Go east a bit and in front of the big house, turn in #INMarshal Haggard# (#COORD[85.69]#), accept #GETDead-tooth Jack# ."},
      [22] = { str = "Warrior, Go SE to the small Defias camp and do #DODead-tooth Jack# : kill/loot #NPCDead-Tooth Jack# (#COORD[89.79]#), then next to that mob loot #ITEMDead-tooth's Strongbox#."},
      [23] = { str = "Warrior, Go back NW and in front of the big house, turn in #INDead-tooth Jack# (#COORD[85.69]#, #9a on map)."},
      [24] = { str = "Follow the main path east into Redridge Mountains (#COORD[94.72]# in Elwynn Forest)."},
      [25] = { str = "Follow the main path east and at the first intersection, accept #GETEncroaching Gnolls# (#COORD[15.71]# in Redridge)."},
      [26] = { str = "Go NE and on your left before the bridge turn in #INEncroaching Gnolls# (#COORD[31.60]#), accept #GETAssessing the Threat# ."},
      [27] = { str = "Next to you, get the Flight Path from the #NPCGryphon Master#."},
      [28] = { str = "If you need to turn in either #DOManhunt# or #DOPrincess Must Die!# then Hearth to Goldshire. If you cannot hearth then fly to Stormwind, drop in the water to die on purpose, and res at spirit to get back to Goldshire. If you DONT need to turn in either of those quests then just fly to Stormwind, Elwynn and skip to the next section below."},
      [29] = { str = "Upgrade First Aid in the Inn (if you need to), then exit the Inn, and in front of the refinery turn in #INManhunt# (#COORD[42.66]#, #4 on map). Make sure you are repaired/resupplied."},
      [30] = { str = "If you did #INPrincess Must Die!# , go SW to The Stonefield Farm and in front of the small house (#COORD[35.84]#), turn it in. Afterwards go east a bit and die on purpose to the Troggs (around #COORD[37.83]#), then res at spirit."},
    },
  },
  [1112] = {
    title = "11-12 Ironforge + Dun Morogh",
    items = {
      [1] = { str = "Paladin, Go NW to Stormwind and then NW to the Cathedral Square and turn in #INThe Tome of Divinity# (#COORD[39.26]#), accept the next #GETpart#."},
      [2] = { str = "Paladin, Across the room, turn in #INThe Tome of Divinity# (#COORD[40.30]#). After all that, you now have #VIDEORedemption# R1."},
      [3] = { str = "Rogue, Go north to enter Stormwind, then go east and upstairs in SI:7, turn in #INSnatch and Grab# (#COORD[76.60]#)."},
      [4] = { str = "Mage, Go NW to enter Stormwind, then west to The Mage Quarter and then go up the spiral ramp (entrance at #COORD[39.82]#) and inside the portal to Wizard's Sanctum and then turn in #INMirror Lake# . If you are level 12 get new spells/abilities."},
      [5] = { str = "Go north to enter Stormwind, then go NE to the Dwarven District and turn in #INElmore's Task# (#COORD[52.12]#), accept #GETStormpike's Delivery# ."},
      [6] = { str = "Go NE in the Dwarven District to enter the Deeprun Tram (#COORD[64.8]#). Then wait for the tram ride to show up and it will take you to Ironforge's side of the Deeprun Tram."},
      [7] = { str = "Once at the other side of the Deeprun Tram, accept #GETDeeprun Rat Roundup# (this is accepted between the two Tram tracks)."},
      [8] = { str = "Just around the immediate area do #DODeeprun Rat Roundup# : use the #ITEMRat Catcher's Flute# quest item on the #NPCDeeprun Rats#."},
      [9] = { str = "Go back between the two tracks at the Deeprun Tram, and turn in #INDeeprun Rat Roundup# . NOTE: #DOMe Brother, Nipsy# will be skipped for now."},
      [10] = { str = "Exit the Deeprun Tram by heading north through the tunnel.."},
      [11] = { str = "Warrior, At Ironforge, If you are level 12, you can get new abilities SE at the Military Ward (#COORD[67.89]#)."},
      [12] = { str = "Rogue, At Ironforge, If you are level 12, you can get new abilities north at The Forlorn Cavern (up at #COORD[52.15]#)."},
      [13] = { str = "Priest, At Ironforge, If you are level 12, you can get new abilities NW at the Mystic Ward (#COORD[25.9]#)."},
      [14] = { str = "Warlock, At Ironforge, If you are level 12, you can get new abilities north at The Forlorn Cavern (#COORD[50.6]#)."},
      [15] = { str = "In the middle of Ironforge at The Great Forge, get the Flight Path there from the #NPCGryphon Master# (#COORD[56.48]#)."},
      [16] = { str = "Mage, If you are level 12, and haven't got your lvl 12 spells yet, you can get new abilities NW at the Mystic Ward (#COORD[26.7]#)."},
      [17] = { str = "Go SW to leave Ironforge (exit at #COORD[15.86]#)."},
      [18] = { str = "In Dun Morogh, follow the main path east to Gol'Bolar Quarry and accept #GETThe Public Servant# (#COORD[69.56]#)."},
      [19] = { str = "Next to you, behind the tent, accept #GETThose Blasted Troggs!# (#COORD[69.56]#)."},
      [20] = { str = "Drop down in the Quarry and enter the cave (entrance at #COORD[71.56]#) and do #DOThe Public Servant# along with #DOThose Blasted Troggs!# : kill #NPC Rockjaw Skullthumpers# and #NPC Rockjaw Bonesnappers#. Focus inside the cave more as both of the these mobs are found in there."},
      [21] = { str = "Go back up and turn in #INThe Public Servant# (#COORD[69.56]#, #10 on map)."},
      [22] = { str = "Next to you, behind the tent, turn in #INThose Blasted Troggs!# (#COORD[69.56]#)."},
      [23] = { str = "Follow the main path east to enter Loch Modan (entrance at #COORD[86.51]#).."},
    },
  },
  [1213] = {
    title = "12-13 Loch Modan",
    items = {
      [1] = { str = "Go up in the watchtower in front of you and accept #GETThe Trogg Threat# (#COORD[23.74]#)."},
      [2] = { str = "Follow the main path NE, then make a right to go to Stonesplinter Valley (around #COORD[32.73]#) and do #DOIn Defense of the King's Lands# along with #DOThe Trogg Threat# : kill 10 #NPC Stonesplinter Troggs# and 10 #NPCStonesplinter Scouts#, and loot them for the #ITEMStone Tooth#."},
      [3] = { str = "Go back west to Valley of Kings and turn in #INIn Defense of the King's Lands# (#COORD[22.73]#, #1 on map)."},
      [4] = { str = "Go up in the watchtower and turn in #INThe Trogg Threat# (#COORD[23.74]#)."},
      [5] = { str = "Go north to Thelsamar (around #COORD[34.48]#) and find #NPC Mountaineer Kadrell# and accept #GETRat Catching# and #GETMountaineer Stormpike's Task# ."},
      [6] = { str = "Go in the Inn (the building with the big barrels around it) and the first NPC you see (#NPCInnkeeper Hearthstove#, #COORD[35.48]#), talk to him to make this Inn your new home."},
      [7] = { str = "At the bar, from #NPCVidra Hearthstove#, accept #GETThelsamar Blood Sausages# (#COORD[35.49]#). Make sure you are resupplied."},
      [8] = { str = "While working your way north to the next steps, also start working on #DORat Catching# by kill/looting Tunnel Rat mobs (troggs) along the west side of the main path (#3 on map). Also start working on #DOThelsamar Blood Sausages# by killing #NPCboars#, #NPCbears# and #ITEMspiders# (in the open fields of Loch Modan, #1 on map): "},
      [9] = { str = "Grind north to Algaz Station, go up in the watchtower and turn in #INMountaineer Stormpike's Task# (#COORD[25.18]#), accept #GETStormpike's Order# . Turn in #INStormpike's Delivery# . Accept #GETFilthy Paws# . NOTE: You can get repaired/resupplied at the bottom of the watchtower but do not sell your #DOThelsamar Blood Sausages# quest items to a vendor!"},
      [10] = { str = "Go east to Silver Stream Mine (around #COORD[35.19]#) and finish #DORat Catching# : kill/loot the Tunnel Rat mobs (troggs) outside of the mine. And if you have a group, do #DOFilthy Paws# : loot the #ITEMMiner's League Crates# inside the mine. You can skip the quest if you cannot get a group (but keep it accepted, as you will be able to solo it later)."},
      [11] = { str = "If you did #INFilthy Paws# go west and turn in up in the watchtower at Algaz Station, (#COORD[25.18]#, #2 on map)."},
      [12] = { str = "Finish #DOThelsamar Blood Sausages# : kill #NPCboars#, #NPCbears# and #ITEMspiders# (in the open fields of Loch Modan, #1 on map)."},
      [13] = { str = "Hearth (if you can) to Stoutlager Inn (Thelsamar) and in the Inn at the bar, turn in #INThelsamar Blood Sausages# . Make sure you are repaired/resupplied."},
      [14] = { str = "In Thelsamar, find #NPC Mountaineer Kadrell# (he patrols back and forth in the town) and turn in #INRat Catching# ."},
      [15] = { str = "You should be level 12 now, if not grind to it."},
      [16] = { str = "South in the town, go to the #NPCGryphon Master# (#COORD[34.51]#) and take a flight to Ironforge, Dun Morogh."},
      [17] = { str = "Get your level 12/14 spells/abilities. Warlocks, go north to The Forlorn Cavern to find the Warlock Trainers (#COORD[50.6]#).Warriors, go SE at the WARRIOR: Military Ward (#COORD[67.89]#).]Hunters, go SE to HUNTER: Hall of Arms to find the Hunter Trainers (#COORD[71.84]#), the #NPCPet Trainer# is right next to you as well.]Paladins, go NW to the PALADIN: Mystic Ward to find the Paladin Trainers (#COORD[24.5]#).]Rogues go north to ROGUE: The Forlorn Cavern to find the Rogue Trainers (up at #COORD[52.15]#).]Priests, go NW to the PRIEST: Mystic Ward to find the Priest Trainers (#COORD[25.9]#).]Mages, go NW to the MAGE: Mystic Ward to find the Mage Trainers (#COORD[26.7]#).]"},
      [18] = { str = "You can upgrade First Aid upstairs in the Ironforge Physician (#COORD[55.58]#).."},
      [19] = { str = "If you can afford to, you can learn new weapon possibilities south at the two Weapon Masters inside Timberline Arms (#COORD[62.89]#)."},
      [20] = { str = "It is now time to travel to Auberdine to continue questing. We will take the big shortcut west in Dun Morogh. First leave Ironforge SW (exit at #COORD[16.84]#). NOTE: The normal route to get there would be to take the flight path back to Thelsamar then go north through Dun Algaz to get to Menethil, but we wont be doing this!"},
      [21] = { str = "Go west in Dun Morogh and above Brewnall Village take the hidden ramp up the mountains (starting at #COORD[31.33]#). This is kind of hard to find. VIDEO coming later for this!"},
      [22] = { str = "Continue north up the mountains, you will need to run for about 45 seconds then jump off the big mountain to your left to die on purpose. This should take you to the graveyard at Baradin Bay, res at spirit."},
      [23] = { str = "Go SW to enter Menethil Harbor and from the #NPC Gryphon Master# (#COORD[9.60]# in Wetlands), get the Flight Path."},
      [24] = { str = "Go to the northern most docks (#COORD[4.57]#) to get on the boat to take you to Auberdine, Darkshore."},
      [25] = { str = "Once at Auberdine, follow the docks east, through the Inn, then up on the platform and from the #NPCHoppogryph Master# (#COORD[36.46]# in Darkshore), get the Flight Path."},
    }
  },
}