--[[--------------------------------------------------
002_DunMorogh.lua
Authors: mrmr, lanjelin
Version: 1.04.3
------------------------------------------------------
Description: Guide Serie - 002 DunMorogh
1.04.1
-- First Release
Dwarves&Gnomes DunMorogh's Guide
from level 1 to lever 12
1.04.2
-- no changes in here for this revision
1.04.3
-- Added color codes
Fixed various spelling errors
Adjustment to coordinate visibility

Faelwen
04 June 2019 - Guide replaced with Joanna's Alliance Guide (https://www.joanasworld.com/alliance-1-12-dun-morogh.html)

------------------------------------------------------
Connection:
--]]--------------------------------------------------
Table_002_DunMorogh = {
  [0106] = {
    title = "1-6 Coldridge Valley",
    items = {
      [1] = { str = "Just to the south of you, do #DODwarven Outfitters# : kill/loot wolves."},
      [2] = { str = "Go back to the starting spot and turn in #INDwarven Outfitters# (#COORD[30.71]#, #1 on map). Accept #GETColdridge Valley Mail Delivery# . We will get HUNTER: #DOEtched Rune# later.]And accept your class's quest WARRIOR: #GETSimple Rune# / #GET Memorandum# .]And accept your class's quest PALADIN: #GETConsecrated Rune# .]We will get ROGUE: #DOEncrypted Rune# / #DO Memorandum# later.]We will get PRIEST: #DOHallowed Rune# later.]We will get MAGE: #DOGlyphic Memorandum# later.]And accept your class's quest #GETTainted Memorandum# .Remember to Choose Your Class At Top of Screen!!!"},
      [3] = { str = "Next to you, accept #GETA New Threat# ."},
      [4] = { str = "Warrior, Go up north to enter Anvilmar (entrance at #COORD[29.69]#), then at the #NPCWarrior Trainer# (#COORD[29.67]#) behind the big fire pit, turn in #INSimple Rune# / #INMemorandum# and learn #VIDEO Battle Shout# R1."},
      [5] = { str = "Paladin, Go up north to enter Anvilmar (entrance at #COORD[29.69]#), and right as you enter turn and you will see the #NPCPaladin Trainer# (#COORD[29.68]#), turn in #INConsecrated Rune# and learn #VIDEODevotion Aura# R1."},
      [6] = { str = "Warlock, Go up north to enter Anvilmar (entrance at #COORD[29.69]#), and all the way up in the back, from the #NPCWarlock Trainer#, turn in #INTainted Memorandum# . Accept #GETBeginnings# . Also learn #VIDEO Immolate# R1."},
      [7] = { str = "Warlock, GROUP: It's wise to do your class's quest #DOBeginnings# ASAP so you can get your Imp minion. This quest is done south in the cave (entrance at #COORD[27.80]#). You would need to kill/loot the #NPCFrostmane Novices# which are sporadically spaced out around in the back of the cave. Try to group up with others in the cave if you can. This is also possible to solo, but it's rough at lvl 2/3. If you cannot do this now, you will be reminded later to try again. As soon as you complete this quest, die on purpose and res at spirit, then go north into the back of Anvilmar and turn it in to get your Imp."},
      [8] = { str = "As you do the following steps start working on #DOA New Threat# : kill #NPCRockjaw Troggs# and #NPCBurly Rockjaw Troggs#:"},
      [9] = { str = "Go SW at the small camp/tent and turn in #INColdridge Valley Mail Delivery# (#COORD[23.71]#), accept the next #GETpart#. Also accept #GETThe Boar Hunter# ."},
      [10] = { str = "Just west and north of you do #DOThe Boar Hunter# : kill 12 #NPCSmall Crag Boars#."},
      [11] = { str = "Go back to the small camp/tent and turn in #INThe Boar Hunter# (#COORD[23.71]#, #6 on map)."},
      [12] = { str = "Follow the main path SE to the small dwarf camp and turn in #INColdridge Valley Mail Delivery# (#COORD[25.76]#). Accept #GETThe Troll Cave# ."},
      [13] = { str = "Around southern Coldridge Valley, start working on #DOThe Troll Cave# : kill #NPCFrostmane Troll Whelps#. There is a lot in the cave down south (entrance at #COORD[27.80]#). As soon as you hit level 4, stop what you are doing and go do the following steps:"},
      [14] = { str = "Go to the dwarf camp south on the main path and accept #GETScalding Mornbrew Delivery# (#COORD[25.76]#)."},
      [15] = { str = "Hearth to the starting spot."},
      [16] = { str = "Hunter, Next to you, accept your class quest #GETEtched Rune# (#COORD[30.71]#)."},
      [17] = { str = "Rogue, Next to you, accept your class quest #GETEncrypted Rune# / #GETMemorandum# (#COORD[30.71]#)."},
      [18] = { str = "Priest, Next to you, accept your class quest #GETHallowed Rune# (#COORD[30.71]#)."},
      [19] = { str = "Mage, Next to you, accept your class quest #GETGlyphic Memorandum# (#COORD[30.71]#)."},
      [20] = { str = "Go north and enter Anvilmar then accept #GETA Refugee's Quandary# (#COORD[29.68]#). Next to you, make sure you are repaired/resupplied."},
      [21] = { str = "Go north in Anvilmar and turn in #INScalding Mornbrew Delivery# (#COORD[29.66]#). Accept #GETBring Back the Mug# ."},
      [22] = { str = "In Anvilmar get your level 2/4 class's spells/abilities. The WARRIOR: #NPCWarrior Trainer# (#COORD[29.67]#) is behind the big fire pit.]The HUNTER: #NPCHunter Trainer# (#COORD[29.67]#) is next to the big fire pit, turn in #INEtched Rune# and get new spells/abilities.]At the entrance of PALADIN: Anvilmar you will find the #NPCPaladin Trainer# (#COORD[29.68]#).]The ROGUE: #NPCRogue Trainer# (#COORD[28.67]#) is in the room with the big fire pit, turn in #INEncrypted Rune# / #INMemorandum# and learn new abilities.]Next to you at the PRIEST: #NPCPriest Trainer#, turn in #INHallowed Rune# and learn new spells.]Next to you at the MAGE: #NPCMage Trainer#, turn in #INGlyphic Memorandum# and learn new spells/abilities.]The #NPCWarlock Trainer# (#COORD[29.66]#) is up in the back of Anvilmar."},
      [23] = { str = "Exit Anvilmar south, then finish #DOA New Threat# : kill #NPCRockjaw Troggs# (mostly east) and #NPCBurly Rockjaw Troggs# (mostly west)."},
      [24] = { str = "At the starting spot, turn in #INA New Threat# (#COORD[30.71]#). Make sure you are repaired/resupplied (from the #NPCblue shirted dwarf# under red tent)."},
      [25] = { str = "Go south to the small dwarf camp at the end of the main path and turn in #INBring Back the Mug# (#COORD[25.76]#, #3 on map)."},
      [26] = { str = "Go west and do #DOA Refugee's Quandary# : loot the 3 objects at the troll camps. First loot #ITEMFelix's Box# (in front of the Campfire, #COORD[21.76]#). See next steps for the other two:"},
      [27] = { str = "Loot #ITEMFelix's Chest# (next to the Campfire, #COORD[23.80]#)."},
      [28] = { str = "Loot #ITEMFelix's Bucket of Bolts# (in front of the Campfire, #COORD[26.79]#)."},
      [29] = { str = "Around southern Coldridge Valley, finish #DOThe Troll Cave# : kill 14 #NPCFrostmane Troll Whelps#. There is a lot in the cave down south (entrance at #COORD[27.80]#)."},
      [30] = { str = "Go back to the dwarf camp south on the main path and turn in #INThe Troll Cave# (#COORD[25.76]#), accept #GETThe Stolen Journal# ."},
      [31] = { str = "Go SE and enter the troll cave (entrance at #COORD[27.80]#, #4 on map) and do #DOThe Stolen Journal# : keep hugging the left side of the cave until you get to #NPCGrik'nir the Cold# and kill/loot this troll. If you are still working on your Warlock quest #DOBeginnings# then do that now as well by kill/looting the #NPCFrostmane Novices# in the back of the cave."},
      [32] = { str = "Go NW to the small dwarf camp at the end of the main path and turn in #INThe Stolen Journal# (#COORD[25.76]#, #5 on map), accept #GETSenir's Observations# ."},
      [33] = { str = "Die on purpose to get to the starting spot."},
      [34] = { str = "Go north to enter Anvilmar then turn in #INA Refugee's Quandary# (#COORD[29.68]#). Make sure you are repaired/resupplied."},
      [35] = { str = "Priest, Back in Anvilmar at the #NPCPriest Trainer# (#COORD[29.66]#) accept #GETIn Favor of the Light# ."},
      [36] = { str = "Warlock, Turn in (if you still need to) #INBeginnings# (#COORD[29.66]#) to get your Imp minion."},
      [37] = { str = "Exit Anvilmar (south) then head east on the main path to the entrance of Coldridge Pass and turn in #INSenir's Observations# (#COORD[33.72]#), accept the next #GETpart#."},
      [38] = { str = "Just next to you up the hill, accept #GETSupplies to Tannok# (#COORD[34.72]#)."},
      [39] = { str = "Enter Coldridge Pass next to you (entrance at #COORD[34.71]#) and work your way through it."},
    },
  },
  [0608] = {
    title = "6-8 Dun Morogh",
    items = {
      [1] = { str = "Go north into Kharanos and off to your right, accept #GETBeer Basted Boar Ribs# (#COORD[47.52]#)."},
      [2] = { str = "Next to you, enter Thunderbrew Distillery (the Inn) and turn in #INSupplies to Tannok# (#COORD[47.52]#)."},
      [3] = { str = "Next to the fireplace, from the #NPC Physician#, learn Apprentice First Aid (#COORD[47.53]#)."},
      [4] = { str = "Next to you by the bar, from #NPC Innkeeper Belm#, talk to him to make Thunderbrew Distillery your new home for your Hearthstone. Make sure you are resupplied. NOTE: Do not sell any #ITEMCrag Boar Ribs# you may have."},
      [5] = { str = "Find your class trainer around Kharanos and learn your level 6 spells/abilities. The HUNTER: #NPC Hunter Trainer# is outside up on the hill on the west side of the main path (#COORD[46.53]#).]The WARRIOR: #NPC Warrior Trainer# is right next to you in the Inn.]The PALADIN: #NPCPaladin Trainer# (#COORD[48.52]#) is up the steps near the entrance of the Inn.]The ROGUE: #NPCRogue Trainer# is in the kitchen.]At the PRIEST: #NPCPriest Trainer# near the entrance in the Inn, turn in #INIn Favor of the Light# (#COORD[47.52]#), accept #GETGarments of the Light# . And get new spells.]The MAGE: #NPCMage Trainer# (#COORD[48.52]#) is up the steps near the entrance of the Inn.]The #NPCWarlock Trainer# & #NPCDemon Trainer# (#COORD[47.54]#) are south of the Inn next to a cauldron and some boxes.Remember to Choose Your Class At Top of Screen!!!"},
      [6] = { str = "Across from Thunderbrew Distillery, at the entrance of the blacksmith shop, accept #GETTools for Steelgrill# (#COORD[46.52]#)."},
      [7] = { str = "Priest, Go south a bit to #NPCMountaineer Dolf# (#COORD[46.55]#) kneeling at the side of the cliff and do #DOGarments of the Light# : on him first use #VIDEOLesser Heal# R2 then #VIDEOPower Word: Fortitude# R1."},
      [8] = { str = "Priest, Go just north to the Inn and turn in #INGarments of the Light# (#COORD[47.52]#)."},
      [9] = { str = "Go NE to Steelgrill's Depot (#COORD[49.48]#) and accept #GETStocking Jetsteam# , and next to you #GETThe Grizzled Den# ."},
      [10] = { str = "Just to the east between the two huts, accept #GETAmmo for Rumbleshot# (#COORD[50.49]#)."},
      [11] = { str = "In front of the hut, turn in #INTools for Steelgrill# (#COORD[50.49]#)."},
      [12] = { str = "As you work on the following steps also start working on #DOBeer Basted Boar Ribs# along with #DOStocking Jetsteam# by kill/looting boars and bears scattered all around Dun Morogh (also do not sell the quest items to a vendor!):"},
      [13] = { str = "SW of Kharanos, do #DOAmmo for Rumbleshot# : loot the #ITEMAmmo Crate# next to the tent/Campfire (#COORD[44.57]#)."},
      [14] = { str = "Go north a bit and do #DOThe Grizzled Den# : kill/loot Yetis. You can find a lot more in the Den (entrance at #COORD[42.54]#)."},
      [15] = { str = "Go south to the small dwarf camp along the main path and turn in #INAmmo for Rumbleshot# (#COORD[41.65]#). Make sure you are resupplied. Do NOT sell your quest items!"},
      [16] = { str = "Just north at the open fields of Dun Morogh, finish #DOBeer Basted Boar Ribs# along with #DOStocking Jetsteam# : kill/loot boars and bears. NOTE: You will get the #ITEMRhapsody Malt# later."},
      [17] = { str = "Make sure you are at least 625 XP away from level 7, then hearth to Thunderbrew Distellery (or run back if you are already close)."},
      [18] = { str = "From #NPC Innkeeper Belm# (#COORD[47.52]#), purchase a #ITEMRhapsody Malt# from him for #DOBeer Basted Boar Ribs# . Make sure you are resupplied (Do NOT sell your quest items!)."},
      [19] = { str = "Just outside of the Inn, turn in #INBeer Basted Boar Ribs# (#COORD[47.52]#). You should be lvl 7 now, if not grind to it."},
      [20] = { str = "South of Kharanos, next to the tent/wagon, accept #GETFrostmane Hold# (#COORD[47.54]#)."},
      [21] = { str = "North in Kharanos, down in the goblin hut, accept #GETOperation Recombobulation# (#COORD[46.49]#)."},
      [22] = { str = "Go east to Steelgrill's Depot (#COORD[49.48]#) and turn in #INStocking Jetsteam# , accept #GETEvershine# . And next to you turn in #INThe Grizzled Den# ."},
      [23] = { str = "Go west (take the south route) and go up the mountain (entrance at #COORD[36.53]#).."},
      [24] = { str = "Up the mountain, accept #GETTundra MacGrann's Stolen Stash# (#COORD[35.52]#)."},
      [25] = { str = "Go east back down the mountain and do #DOTundra MacGrann's Stolen Stash# : In the cave loot #ITEMMacGrann's Meat Locker# and watch out for the #NPClvl 11 patrolling elite# yeti. Simply wait for this elite yeti to leave the cave then run in there to loot it."},
      [26] = { str = "Back up the mountain, turn in #INTundra MacGrann's Stolen Stash# (#COORD[35.52]#, #2 on map)."},
      [27] = { str = "Go NE to Brewnall Village and turn in #INEvershine# (#COORD[30.46]#), accept #GETA Favor for Evershine# . Also accept #GETThe Perfect Stout# ."},
      [28] = { str = "Next to you, accept #GETBitter Rivals# ."},
      [29] = { str = "You can get resupplied from #NPCKeeg Gibn# under the red canopy."},
      [30] = { str = "While doing the next steps, start working on #DOA Favor for Evershine# by killing the #NPC Ice Claw Bears#, #NPCElder Crag Boars# and #NPCSnow Leopards# around the western open fields of Dun Morogh:"},
      [31] = { str = "Go NE up to Shimmer Ridge (entrance at #COORD[38.42]#) and do #DOThe Perfect Stout# : kill/loot #NPCFrostmane Seers# and loot #ITEMShimmerweed Baskets#."},
      [32] = { str = "Go west to Brewnall Village and turn in #INThe Perfect Stout# (#COORD[30.46]#, #5 on map), then if you are lvl 8 accept #GETShimmer Stout# . And get resupplied."},
      [33] = { str = "All around western Dun Morogh (past Iceflow Lake) continue working on #DOA Favor for Evershine# by killing the #NPC Ice Claw Bears#, #NPCElder Crag Boars# and #NPCSnow Leopards# (#7 on map). Once you hit level 8, Hearth, or run to Kharanos."},
    },
  },
  [0810] = {
    title = "8-10 Dun Morogh",
    items = {
      [1] = { str = "Go down the steps in Thunderbrew Distillery to the room with all the barrels (#COORD[48.53]#) and do #DOBitter Rivals# : click on the #ITEMGuarded Thunder Ale Barrel#, then talk to #NPCJarven Thunderbrew# next to you to give him the #ITEM Thunder Ale#. Wait a few seconds, then click on the #ITEMUnguarded Thunder Ale Barrel# to turn in #INBitter Rivals# , accept #GETReturn to Marleth# ."},
      [2] = { str = "Find your class trainer around Kharanos and learn your level 8 spells/abilities. The HUNTER: #NPC Hunter Trainer# is outside up on the hill (#COORD[46.53]#).]The WARRIOR: #NPCWarrior Trainer# is right next to the bar/innkeeper.]The PALADIN: #NPCPaladin Trainer# (#COORD[48.52]#) is up the steps near the entrance of the Inn.]The ROGUE: #NPCRogue Trainer# (#COORD[48.53]#) is in the Inn's kitchen.]The MAGE: #NPCMage Trainer# (#COORD[48.52]#) is up the steps near the entrance of the Inn.]The #NPCWarlock Trainer# & #NPCDemon Trainer# (#COORD[47.54]#) are south of the Inn next to a cauldron and some boxes."},
      [3] = { str = "Go west to Brewnall Village (#COORD[30.46]#) and turn in #INReturn to Marleth# . Also accept (if you haven't yet) #GETShimmer Stout# ."},
      [4] = { str = "Go SW to enter Frostmane Hold (entrance at #COORD[25.51]#).."},
      [5] = { str = "Do #DOFrostmane Hold# : work your way to the middle of the cave (#COORD[23.52]#) to get it explored. Also kill 5 #NPC Frostmane Headhunters#."},
      [6] = { str = "Leave the cave then go up north to the entrance of Gnomeregan (around #COORD[25.44]#) and do #DOOperation Recombobulation# : kill/loot the #NPCLeper Gnomes#."},
      [7] = { str = "All around western Dun Morogh (past Iceflow Lake) finish #DOA Favor for Evershine# : kill #NPC Ice Claw Bears#, #NPCElder Crag Boars# and #NPCSnow Leopards# around the open fields of Dun Morogh."},
      [8] = { str = "Go to Brewnall Village and turn in #INA Favor for Evershine# (#COORD[30.46]#), accept #GETReturn to Bellowfiz# ."},
      [9] = { str = "Hearth (or run back if its still on a cooldown)Go east (Don't hearth) to Kharanos and south in the town, turn in #INFrostmane Hold# (#COORD[47.54]#), accept #GETThe Reports# . Make sure you are repaired/resupplied."},
      [10] = { str = "North in Kharanos, down in the goblin hut, turn in #INOperation Recombobulation# (#COORD[46.49]#)."},
      [11] = { str = "Go NE to Steelgrill's Depot and turn in #INReturn to Bellowfiz# (#COORD[49.48]#)."},
      [12] = { str = "Go east to Gol'Bolar Quarry (grind mobs along the way) and accept #GETThe Public Servant# (#COORD[69.56]#)."},
      [13] = { str = "Next to you, behind the tent, accept #GETThose Blasted Troggs!# (#COORD[69.56]#)."},
      [14] = { str = "At this point it is wise to get your level 10 spells/abilities before continuing, so grind on any mobs until you are level 10. You can start working on #DOThose Blasted Troggs!# by killing the #NPC Rockjaw Skullthumpers# at Gol'Bolar Quarry (around #COORD[68.59]#). You can also try to do #DOThe Public Servant# by killing #NPCRockjaw Bonesnappers# in the cave (entrance at #COORD[71.56]#). Turn these in if you complete them. Or you can grind on any mobs in the open fields of Dun Morogh."},
      [15] = { str = "Paladin, Once you hit level 10, hearth (or run back) to Kharanos and from the #NPCPaladin Trainer# (#COORD[48.52]#) in the entrance of the Inn, learn your new abilities."},
    },
  },
  [1001] = {
    title = "[Warrior] Level 10 Class Quests",
    items = {
      [1] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [2] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [3] = { str = "Go SE to Hall of Arms and turn in #INMuren Stormpike# (#COORD[71.90]#), accept #GETVejrek# ."},
      [4] = { str = "Exit Hall of Arms, then make a left to Timberline Arms and you will see two Weapon Masters (#COORD[62.90]#) that you can learn new weapon possibilities if you can afford to. Also if you can easily afford 22 silver, you can purchase a #ITEMTabar# downstairs from the #NPCAxe Merchant#."},
      [5] = { str = "Exit Ironforge SW (#COORD[16.85]#)."},
      [6] = { str = "Go SW in Dun Morogh and up on a mountain cliff do #DOVejrek# : kill/loot #NPCVejrek# (#COORD[28.58]#) in the hut."},
      [7] = { str = "Hearth, then (or otherwise) go back north to Ironforge (entrance at #COORD[53.35]#, #2 on map)."},
      [8] = { str = "Go SE to Hall of Arms and turn in #INVejrek# (#COORD[71.90]#, #4 on map), accept #GETTormus Deepforge# ."},
      [9] = { str = "Go to the middle of Ironforge and turn in #INTormus Deepforge# (#COORD[49.42]#), accept #GETIronband's Compound# ."},
      [10] = { str = "Exit Ironforge SW (#COORD[16.85]#, #6 on map)."},
      [11] = { str = "Now if you can greatly benefit from having a reward from this #DOquest# (which includes: #ITEM Axe#, #ITEMMace#, #ITEMDagger# or #ITEMSword#), then do the rest of this section, if not then skip to the next section below!"},
      [12] = { str = "If you want the reward (but sacrifice some time), then go SE in Dun Morogh, then downstairs in the hut and do #DOIronband's Compound# : loot #ITEMIronband's Strongbox# (#COORD[78.72]#)."},
      [13] = { str = "Die on purpose and res at Spirit to get back to Ironforge (entrance at #COORD[53.35]#, #2 on map)."},
      [14] = { str = "Go to the middle of Ironforge and turn in #INIronband's Compound# (#COORD[49.42]#, #10 on map). Wait a few seconds then complete #INGrey Iron Weapons# ."},
      [15] = { str = "Exit Ironforge SW (#COORD[16.85]#, #6 on map)."},
    },
  },
  [1002] = {
    title = "[Rogue] Level 10 Class Quests",
    items = {
      [1] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [2] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [3] = { str = "Go north to The Forlorn Cavern and turn in #INRoad to Salvation# (#COORD[52.15]#), accept #GETSimple Subterfugin'# ."},
      [4] = { str = "You can go south to Timberline Arms and you will see two Weapon Masters (#COORD[62.90]#) that you can learn new weapon possibilities if you can afford to."},
      [5] = { str = "Exit Ironforge SW (#COORD[16.85]#)."},
      [6] = { str = "Go west in Dun Morogh to the outside entrance of Gnomeregan and go up the spiral ramp on the wooden structure and then turn in #INSimple Subterfugin'# (#COORD[25.44]#), accept #GETOnin's Report# ."},
      [7] = { str = "Hearth (or go back) north to Ironforge (entrance at #COORD[53.35]#, #2 on map)."},
      [8] = { str = "In Ironforge, go north to The Forlorn Cavern and turn in #INOnin's Report# (#COORD[52.15]#, #4 on map)."},
      [9] = { str = "Exit Ironforge SW (#COORD[16.85]#, #6 on map)."},
    },
  },
  [1003] = {
    title = "[Priest] Level 10 Class Quests",
    items = {
      [1] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [2] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [3] = { str = "You can go south to Timberline Arms and you will see two Weapon Masters (#COORD[62.90]#) that you can learn new weapon possibilities if you can afford to."},
      [4] = { str = "Go east in Ironforge and go through The Deeprun Tram (entrance at #COORD[76.51]#)."},
      [5] = { str = "Once at the Deeprun Tram, accept #GETDeeprun Rat Roundup# (this is accepted between the two Tram tracks)."},
      [6] = { str = "Just around the immediate area do #DODeeprun Rat Roundup# : use the #ITEMRat Catcher's Flute# quest item on the #NPCDeeprun Rats#."},
      [7] = { str = "Go back between the two tracks at the Deeprun Tram, and turn in #INDeeprun Rat Roundup# , accept #GETMe Brother, Nipsy# ."},
      [8] = { str = "Then wait for the tram ride to show up and it will take you to Stormwind's side of the Deeprun Tram. Once you get to Stormwind's side of the Tram, between the two tracks, turn in #INMe Brother, Nipsy# ."},
      [9] = { str = "Go north to exit the Tram and to get to Stormwind.."},
      [10] = { str = "At Stormwind, go west to Cathedral of Light and turn in #INDesperate Prayer# (#COORD[39.26]#). You now have #VIDEODesperate Prayer# R1."},
      [11] = { str = "Hearth to Thunderbrew Distillery (Kharanos)."},
    },
  },
  [1004] = {
    title = "[Mage] Level 10 Class Quests",
    items = {
      [1] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [2] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [3] = { str = "Go NW to the bottom floor of Hall of Mysteries and turn in #INSpeak with Bink# (#COORD[27.8]#), accept #GETMage-tastic Gizmonitor# ."},
      [4] = { str = "You can go south to Timberline Arms and you will see two Weapon Masters (#COORD[62.90]#) that you can learn new weapon possibilities if you can afford to."},
      [5] = { str = "Exit Ironforge SW (#COORD[16.85]#)."},
      [6] = { str = "Go west in Dun Morogh to the outside entrance of Gnomeregan and do #DOMage-tastic Gizmonitor# : go in the hut with the spinning gears outside of it loot #ITEMBink's Toolbox# (#COORD[28.36]#)."},
      [7] = { str = "Hearth (if you can). Then (or otherwise) go north to Ironforge (entrance at #COORD[53.35]#, #2 on map)."},
      [8] = { str = "In Ironforge, go NW to the bottom floor of Hall of Mysteries and turn in #INMage-tastic Gizmonitor# (#COORD[27.8]#, #4 on map)."},
      [9] = { str = "Hearth (if you can), or exit Ironforge SW (#COORD[16.85]#, #6 on map)."},
    },
  },
  [1005] = {
    title = "[Warlock] Level 10 Class Quests",
    items = {
      [1] = { str = "At Ironforge, you can go SE to Timberline Arms and you will see two Weapon Masters (#COORD[62.90]#) that you can learn new weapon possibilities if you can afford to."},
      [2] = { str = "At the middle of Ironforge, at The High Seat, turn in #INThe Reports# (#COORD[39.58]#)."},
      [3] = { str = "Go north to The Forlorn Cavern and accept #GETThe Slaughtered Lamb# (#COORD[48.9]#)."},
      [4] = { str = "Go east in Ironforge and go through The Deeprun Tram (entrance at #COORD[76.51]#)."},
      [5] = { str = "Once at the Deeprun Tram, accept #GETDeeprun Rat Roundup# (this is accepted between the two Tram tracks)."},
      [6] = { str = "Just around the immediate area do #DODeeprun Rat Roundup# : use the #ITEMRat Catcher's Flute# quest item on the #NPCDeeprun Rats#."},
      [7] = { str = "Go back between the two tracks at the Deeprun Tram, and turn in #INDeeprun Rat Roundup# , accept #GETMe Brother, Nipsy# ."},
      [8] = { str = "Then wait for the tram ride to show up and it will take you to Stormwind's side of the Deeprun Tram. Once you get to Stormwind's side of the Tram, between the two tracks, turn in #INMe Brother, Nipsy# ."},
      [9] = { str = "Go north to exit the Tram and to get to Stormwind.."},
      [10] = { str = "At Stormwind, go west and enter The Slaughtered Lamb, then go down in the basement and turn in #INThe Slaughtered Lamb# . Accept #GETSurena Caledon# . Also get new spells/abilities."},
      [11] = { str = "At the Trade District, you can go in Weller's Arsenal and from the #NPCWeapon Master# (#COORD[57.58]#), you can learn new weapon possibilities if you can afford to."},
      [12] = { str = "Go east to the #NPCGryphon Master# (#COORD[66.62]#) in Stormwind to get the Flight Path."},
      [13] = { str = "Exit Stormwind (SE), then go east to Brackwell Pumpkin Patch in Elwynn Forest and in the small house do #DOSurena Caledon# : kill/loot #NPCSurena Caledon# (#COORD[71.81]#)."},
      [14] = { str = "Go back west to Stormwind at the Mage Quarter down in The Slaughtered Lamb and turn in #INSurena Caledon# (#1 on map), accept #GETThe Binding# ."},
      [15] = { str = "Next to you, go down the spiral ramp, then make a right and keep going down until you get to the purple summoning circle and do #DOThe Binding# : use the #ITEMBloodstone Choker# quest item there, then kill the voidwalker that spawns."},
      [16] = { str = "Go back up and turn in #INThe Binding# . You can now summon a Voidwalker!"},
      [17] = { str = "Hearth to Thunderbrew Distillery (Kharanos)."},
    },
  },
  [1006] = {
    title = "[Hunter] Level 10 Class Quests",
    items = {
      [1] = { str = "Go SE and do #DOTaming the Beast# : use the #ITEMTaming Rod# quest item on a #NPC Large Crag Boar# (around #COORD[48.57]#)."},
      [2] = { str = "Go back to Kharanos at the #NPCHunter Trainer# (#COORD[46.53]#, #1 on map) and turn in #INTaming the Beast# , accept the next #GETpart#."},
      [3] = { str = "Go SE and do #DOTaming the Beast# : use the #ITEMTaming Rod# quest item on a #NPCSnow Leapard# (around #COORD[48.59]#)."},
      [4] = { str = "Go back to Kharanos at the #NPCHunter Trainer# (#COORD[46.53]#, #1 on map) and turn in #INTaming the Beast# , accept the next #GETpart#."},
      [5] = { str = "Go east and do #DOTaming the Beast# : use the #ITEMTaming Rod# quest item on a #NPCIce Claw Bear# (there is one spawn at #COORD[50.54]#)."},
      [6] = { str = "Go back to Kharanos at the #NPCHunter Trainer# (#COORD[46.53]#, #1 on map) and turn in #INTaming the Beast# , accept #GETTraining the Beast# ."},
      [7] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [8] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [9] = { str = "Go SE to Hall of Arms and at the #NPCPet Trainer#, turn in #INTraining the Beast# (#COORD[71.86]#). Also learn new pet abilities."},
      [10] = { str = "Hunters, find the #NPC Meat Vendor#, he patrols counter-clockwise around the open part of The Military Ward (around #COORD[63.76]#) and stock up on meat so you can feed your future pet. I recommend getting about 40-60 of the #ITEM Haunch of Meat#."},
      [11] = { str = "Go SW a bit, downstairs in Timberline Arms and at the #NPCWeapon Merchant#, upgrade to a #ITEM Small Shot Pouch# (or #ITEMMedium Quiver# if using bows). Also, upgrade your ammo to #ITEMHeavy Shot# (or #ITEMSharp Arrow# if using bows). NOTE: There is two Weapon Masters upstairs that you can learn new weapon possibilities if you can afford to."},
      [12] = { str = "Leave Ironforge (SW, #COORD[16.85]#)."},
      [13] = { str = "Hunters, its time to find your first real pet. I recommend going to the middle of Iceflow Lake (around #COORD[34.42]#) and you will see two #NPCStarving Winter Wolves# along with (maybe) #NPCTimber# (a lvl 10 rare) patrolling around in a circle, tame any one of them (including the rare) to get Bite Rank 2."},
    },
  },
  [1011] = {
    title = "10-11 Dun Morogh",
    items = {
      [1] = { str = "Go back up and turn in #INThe Public Servant# (#COORD[69.56]#)."},
      [2] = { str = "Next to you, behind the tent, turn in #INThose Blasted Troggs!# (#COORD[69.56]#)."},
      [3] = { str = "GROUP ONLY: If you happen to have a group, then go north to Amberstill Ranch and accept #GETProtecting the Herd# (Elite, #COORD[63.50]#)."},
      [4] = { str = "GROUP ONLY: Just to the west of you is a hidden path that leads up the mountain, go up it then head north and try to do #DOProtecting the Herd# : kill/loot #NPCVagash#. This lvl 11 Elite Yeti patrols up around the mountain ledges. This mob is very difficult to solo, even at level 12, if you do not have some help, it can be skipped."},
      [5] = { str = "GROUP ONLY: Back at Amberstill Ranch, turn in (if you did it) #INProtecting the Herd# (#COORD[63.50]#, #4 on map)."},
      [6] = { str = "Warrior, Do this step only if you still have #DOIronband's Compound# . Go SE in Dun Morogh, then downstairs in the hut and do #DOIronband's Compound# : loot #ITEMIronband's Strongbox# (#COORD[78.72]#)."},
      [7] = { str = "Follow the path NE to North Gate Outpost and accept #GETThe Lost Pilot# (#COORD[84.39]#)."},
      [8] = { str = "Go NW a bit and click on #ITEMA Dwarven Corpse# to turn in #INThe Lost Pilot# (#COORD[80.36]#), accept #GETA Pilot's Revenge# ."},
      [9] = { str = "Go just SW up the path a bit and do #DOA Pilot's Revenge# : kill/loot #NPCMangeclaw# (#COORD[78.38]#)."},
      [10] = { str = "Back east at the Outpost turn in #INA Pilot's Revenge# (#COORD[84.39]#, #7 on map)."},
      [11] = { str = "Go to the South Gate Outpost and turn in #INShimmer Stout# (#COORD[86.49]#), accept #GETStout to Kadrell# ."},
      [12] = { str = "Enter South Gate Pass (entrance at #COORD[17.59]#) and go through it to get to Loch Modan.."},
    },
  },
  [1112] = {
    title = "11-12 Loch Modan",
    items = {
      [1] = { str = "Go up in the watchtower in front of you and accept #GETThe Trogg Threat# (#COORD[23.74]#)."},
      [2] = { str = "Follow the main path NE, then make a right to go to Stonesplinter Valley (around #COORD[32.73]#) and do #DOIn Defense of the King's Lands# along with #DOThe Trogg Threat# : kill 10 #NPC Stonesplinter Troggs# and 10 #NPCStonesplinter Scouts#, and loot them for the #ITEMStone Tooth#. Paladins, it is important to note that you need to save 10 PALADIN: #NPCLinen Cloth# for a future #DOquest#!]"},
      [3] = { str = "Go back west to Valley of Kings and turn in #INIn Defense of the King's Lands# (#COORD[22.73]#, #1 on map)."},
      [4] = { str = "Go up in the watchtower and turn in #INThe Trogg Threat# (#COORD[23.74]#)."},
      [5] = { str = "Go north to Thelsamar (around #COORD[34.48]#) and find #NPC Mountaineer Kadrell# (he patrols back and forth in the town) and turn in #INStout to Kadrell# . From him accept #GETRat Catching# and #GETMountaineer Stormpike's Task# ."},
      [6] = { str = "Go in the Inn (the building with the big barrels around it), (entrance at #COORD[35.48]#).. and the first NPC you see (#NPCInnkeeper Hearthstove#, #COORD[35.48]#), talk to him to make this Inn your new home."},
      [7] = { str = "At the bar, from #NPCVidra Hearthstove#, accept #GETThelsamar Blood Sausages# (#COORD[35.49]#). Make sure you are resupplied."},
      [8] = { str = "East in Thelsamar, down in the hut, accept #GETHonor Students# (#COORD[37.48]#)."},
      [9] = { str = "South in the town, go to the #NPCGryphon Master# and turn in #INHonor Students# (#COORD[34.51]#), accept #GETRide to Ironforge# ."},
      [10] = { str = "While working your way north to the next steps, also start working on #DORat Catching# by kill/looting Tunnel Rat mobs (troggs) along the west side of the main path (#3 on map). Also start working on #DOThelsamar Blood Sausages# by killing #NPCboars#, #NPCbears# and #ITEMspiders# (in the open fields of Loch Modan, #1 on map): "},
      [11] = { str = "Grind north to Algaz Station, go up in the watchtower and turn in #INMountaineer Stormpike's Task# (#COORD[25.18]#), Accept #GETStormpike's Order# . Also accept #GETFilthy Paws# . NOTE: You can get repaired/resupplied at the bottom of the watchtower but do not sell your #DOThelsamar Blood Sausages# quest items to a vendor!"},
      [12] = { str = "Go east to Silver Stream Mine (around #COORD[35.19]#) and finish #DORat Catching# : kill/loot the Tunnel Rat mobs (troggs) outside of the mine. And if you have a group, do #DOFilthy Paws# : loot the #ITEMMiner's League Crates# inside the mine. You can skip the quest if you cannot get a group (but keep it accepted, as you will be able to solo it later)."},
      [13] = { str = "If you did #INFilthy Paws# go west and turn in up in the watchtower at Algaz Station, (#COORD[25.18]#, #2 on map)."},
      [14] = { str = "Finish #DOThelsamar Blood Sausages# : kill #NPCboars#, #NPCbears# and #ITEMspiders# (in the open fields of Loch Modan, #1 on map)."},
      [15] = { str = "Hearth (if you can)Go to Stoutlager Inn (Thelsamar) and in the Inn at the bar, turn in #INThelsamar Blood Sausages# (#COORD[35.49]#). Make sure you are repaired/resupplied."},
      [16] = { str = "In Thelsamar, find #NPC Mountaineer Kadrell# (he patrols back and forth in the town) and turn in #INRat Catching# ."},
      [17] = { str = "You should be level 12 now, if not grind to it."},
      [18] = { str = "Hearth to Thunderbrew Distillery (Kharanos)."},
      [19] = { str = "From the #NPCPaladin Trainer# (#COORD[48.52]#) near the entrance in the Inn, accept #GETTome of Divinity# , and learn your lvl 12 spells/abilities."},
      [20] = { str = "Follow the path north to enter Ironforge (entrance at #COORD[53.35]#)."},
      [21] = { str = "At The High Seat, turn in #INThe Reports# (#COORD[39.58]# in Ironforge)."},
      [22] = { str = "In Ironforge, go north to Deep Mountain Mining Guild and turn in #INRide to Ironforge# (#COORD[51.26]#), accept #GETGryth Thurden# ."},
      [23] = { str = "Go NW and up the ramp at the Hall of Mysteries and turn in #INTome of Divinity# (#COORD[28.12]#), then accept and complete #INThe Tome of Divinity# , then from the #ITEMitem# received, accept #GETThe Tome of Divinity# . Turn that in right there and accept the next #GETpart#."},
      [24] = { str = "Go south and find #NPCJohn Turner#. He patrols around Ironforge's Inn/AH/entrance (see map). Once you found him, turn in #INThe Tome of Divinity# , accept the next #GETpart#."},
      [25] = { str = "With your 10 #ITEMLinen Cloth#, turn in #INThe Tome of Divinity# , accept the next #GETpart#."},
      [26] = { str = "Go back NW and up the ramp at the Hall of Mysteries and turn in #INThe Tome of Divinity# (#COORD[28.12]#, #7 on map), accept the next #GETpart#."},
      [27] = { str = "Next to you across the room, turn in #INThe Tome of Divinity# (#COORD[28.12]#), accept the next #GETpart#."},
      [28] = { str = "Hearth (if you can). Then (or otherwise), go east in Dun Morogh next to Helm's Bed Lake and do #DOThe Tome of Divinity# : use the #VIDEOSymbol of Life# quest item on #NPCNarm Faulk# (corpse up on a small hill, #COORD[78.58]#). Then turn in #INThe Tome of Divinity# , accept the next #GETpart#."},
      [29] = { str = "In the immediate area (south of the lake, around #COORD[77.60]#), do #DOThe Tome of Divinity# : kill/loot the #NPCDark Iron Spies# until the #ITEMDark Iron Script# drops."},
      [30] = { str = "Die on purpose and res at spirit to get to Ironforge (entrance at #COORD[53.35]#)."},
      [31] = { str = "At Ironforge, go NW and up the ramp at the Hall of Mysteries and turn in #INThe Tome of Divinity# (#COORD[23.8]#), accept the next #GETpart#."},
      [32] = { str = "Next to you across the room turn in #INThe Tome of Divinity# (#COORD[28.12]#). You now have #VIDEORedemption# R1."},
      [33] = { str = "You can upgrade First Aid upstairs in the Ironforge Physician (#COORD[55.58]#)."},
      [34] = { str = "If you can afford to, you can learn new weapon possibilities south at the two Weapon Masters inside Timberline Arms (#COORD[62.89]#)."},
      [35] = { str = "Go to the #NPCGryphon Master# (#COORD[55.48]#) and turn in #INGryth Thurden# , accept #GETReturn to Brock# . Then take a flight to Thelsamar, Loch Modan."},
      [36] = { str = "East in Thelsamar, down in the hut, turn in #INReturn to Brock# (#COORD[37.48]#)."},
      [37] = { str = "It is now time to travel to Auberdine to continue questing. To get there, first follow the main path north through Dun Algaz (entrance at #COORD[26.10]# in Loch Modan)."},
      [38] = { str = "Once you arrive in Wetlands, follow the main path north, then west to Menethil Harbor and from the #NPC Gryphon Master# (#COORD[9.60]# in Wetlands), get the Flight Path."},
      [39] = { str = "Go to the northern most docks (#COORD[4.57]#) to get on the boat to take you to Auberdine, Darkshore."},
      [40] = { str = "Once at Auberdine, follow the docks east, through the Inn, then up on the platform and from the #NPCHoppogryph Master# (#COORD[36.46]# in Darkshore), get the Flight Path."},
      [41] = { str = "You should be level 12 now, if not grind to it."},
      [42] = { str = "South in the town, go to the #NPCGryphon Master# (#COORD[34.51]#) and take a flight to Ironforge, Dun Morogh."},
      [43] = { str = "In Ironforge, go north to Deep Mountain Mining Guild and turn in #INRide to Ironforge# (#COORD[51.26]#), accept #GETGryth Thurden# ."},
      [44] = { str = "Warrior, ONLY do this step if you have #DOIronband's Compound# . Go to the middle of Ironforge and turn in #INIronband's Compound# (#COORD[49.42]#). Wait a few seconds then complete #INGrey Iron Weapons# ."},
      [45] = { str = "Warlock, Get your level 12 spells/abilities. Warlocks, go north to The Forlorn Cavern to find the Warlock Trainers (#COORD[50.6]#)."},
      [46] = { str = "Rogue, Get your level 12 spells/abilities. Rogues go north to The Forlorn Cavern to find the Rogue Trainers (up at #COORD[52.15]#)."},
      [47] = { str = "Priest, Get your level 12 spells/abilities. Priests, go NW to the Mystic Ward to find the Priest Trainers (#COORD[25.9]#)."},
      [48] = { str = "Mage, Get your level 12 spells/abilities. Mages, go NW to the Mystic Ward to find the Mage Trainers (#COORD[26.7]#)."},
      [49] = { str = "Go to the #NPCGryphon Master# (#COORD[55.48]#) and turn in #INGryth Thurden# , accept #GETReturn to Brock# . Then take a flight to Thelsamar, Loch Modan."},
      [50] = { str = "East in Thelsamar, down in the hut, turn in #INReturn to Brock# (#COORD[37.48]#)."},
      [51] = { str = "South in the town, go to the #NPCGryphon Master# (#COORD[34.51]#, #2 on map) and take a flight to Ironforge, Dun Morogh."},
      [52] = { str = "You can upgrade First Aid upstairs in the Ironforge Physician (#COORD[55.58]#).."},
      [53] = { str = "Hunter, Get your level 12 spells/abilities. Hunters, go SE to Hall of Arms to find the Hunter Trainers (#COORD[71.84]#), the #NPCPet Trainer# is right next to you as well."},
      [54] = { str = "Warrior, Get your level 12 spells/abilities. Warriors, go SE at the Military Ward (#COORD[67.89]#)."},
      [55] = { str = "If you can afford to, you can learn new weapon possibilities south at the two Weapon Masters inside Timberline Arms (#COORD[62.89]#)."},
      [56] = { str = "It is now time to travel to Auberdine to continue questing. We will take the big shortcut west in Dun Morogh. First leave Ironforge SW (exit at #COORD[16.84]#). NOTE: The normal route to get there would be to take the flight path back to Thelsamar then go north through Dun Algaz to get to Menethil, but we wont be doing this!"},
      [57] = { str = "Go west in Dun Morogh and above Brewnall Village take the hidden ramp up the mountains (starting at #COORD[31.33]#). This is kind of hard to find. VIDEO coming later for this!"},
      [58] = { str = "Continue north up the mountains, you will need to run for about 45 seconds then jump off the big mountain to your left to die on purpose. This should take you to the graveyard at Baradin Bay, res at spirit."},
      [59] = { str = "Go SW to enter Menethil Harbor and from the #NPC Gryphon Master# (#COORD[9.60]# in Wetlands), get the Flight Path."},
      [60] = { str = "Go to the northern most docks (#COORD[4.57]#) to get on the boat to take you to Auberdine, Darkshore."},
      [61] = { str = "Once at Auberdine, follow the docks east, through the Inn, then up on the platform and from the #NPCHoppogryph Master# (#COORD[36.46]# in Darkshore), get the Flight Path."},
    },
  },
}
