--[[--------------------------------------------------
003_Alliance_12to20.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 12 to Lvl 20
1.04.1
-- First Release
Alliance's Guide
from level 12 to lever 20
1.04.2
-- no changes in here for this revision

Faelwen
04 June 2019 - Guide replaced with Joanna's Alliance Guide (https://www.joanasworld.com/alliance-12-20.php)

------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_12to20 = {
  [1217] = {
    title = "12-17 Darkshore",
    items = {
      [1] = { str = "Go in the Inn and from #NPC Innkeeper Shaussiy# (#COORD[37.44]#), make Auberdine your new home. NOTE: From the #NPCFish Vendor# in the Inn you can purchase #ITEMLongjaw Mud Snapper#, which is a cheap tier 2 food and it is especially good food for most Hunter petsHUNTER: ]."},
      [2] = { str = "Go west of the Inn on the long docks and accept #GETFor Love Eternal# (#COORD[36.44]#)."},
      [3] = { str = "Go back toward the Inn, but go upstairs and accept #GETBuzzbox 827# (#COORD[37.44]#)."},
      [4] = { str = "Just outside of the Inn, next to the mailbox, accept #GETCave Mushrooms# (#COORD[37.44]#)."},
      [5] = { str = "Just across the path from you near the moonwell, accept #GETThe Red Crystal# (#COORD[38.43]#)."},
      [6] = { str = "Go north across the bridge and into the merchant building then accept #GETBashal'Aran# and #GETTools of the Highborne# (#COORD[37.40]#). COOKING QUEST: If your cooking skill is 10, then accept #GETEasy Strider Living# . This cooking quest requires 5 #ITEMStrider Meat# that drop from the Plainstriders throughout Darkshore. You can focus on this while doing the other quests and turn this in once finished."},
      [7] = { str = "Take the SE bridge to the other building and at the entrance, accept #GETPlagued Lands# (#COORD[39.43]#)."},
      [8] = { str = "Go inside the building and accept #GETHow Big a Threat?# (#COORD[39.44]#)."},
      [9] = { str = "Work your way down south along the shore while doing #DOBuzzbox 827# : kill/loot crabs. Work your way to the #ITEMBeached Sea Creature# (#COORD[36.51]#) and stand in the middle of it where the neck meets the body and then click on it to loot the #ITEMSea Creature Bones# for #DOWashed Ashore# ."},
      [10] = { str = "Go back north to Auberdine and next to the Hippogryph dock, off in the grass, from #ITEMBuzzbox 827# (#COORD[37.46]#, #1 on map), turn in #INBuzzbox 827# , accept #GETBuzzbox 411# ."},
      [11] = { str = "On the Hippogryph dock, turn in #INWashed Ashore# (#COORD[37.46]#), accept the next #GET part#."},
      [12] = { str = "Go west out in the sea and do #DOWashed Ashore# : loot the #ITEM Skeletal Sea Turtle's# head (#COORD[32.46]#)."},
      [13] = { str = "Around in the sea do #DOBuzzbox 411# : kill/loot #NPCDarkshore Threshers#."},
      [14] = { str = "Go back to Auberdine on the Hippogryph dock and turn in #INWashed Ashore# (#COORD[37.46]#)."},
      [15] = { str = "In the town, get repaired/resupplied."},
      [16] = { str = "Go north to the shore, at the #ITEMBeached Sea Creature# (#COORD[42.31]#) and stand where its neck meets its body and click on it to accept #GETBeached Sea Creature# ."},
      [17] = { str = "Go north along the shore and at #ITEMBuzzbox 411# (#COORD[42.29]#), turn in #INBuzzbox 411# , accept #GETBuzzbox 323# ."},
      [18] = { str = "As you work your way to do the next steps, start working on #DOBuzzbox 323# by kill/looting the Moonstalkers (cats):"},
      [19] = { str = "Go south to Bashal'Aran, up on the hill, in the blue mist, turn in #INBashal'Aran# (#COORD[44.36]#), accept the next #GETpart#."},
      [20] = { str = "Just south of where you are at, do #DOBashal'Aran# : kill/loot #NPCVile Sprites# and #NPCWild Grell#."},
      [21] = { str = "Go back up on the hill at Bashal'Aran, in the blue mist, turn in #INBashal'Aran# (#COORD[44.36]#, #6 on map), accept the next #GETpart#."},
      [22] = { str = "Just south of where you are at, do #DOBashal'Aran# : kill/loot #NPCDeth'ryll Satyr#."},
      [23] = { str = "Go back up on the hill at Bashal'Aran, in the blue mist, turn in #INBashal'Aran# (#COORD[44.36]#, #6 on map), accept the next #GETpart#."},
      [24] = { str = "Grind down south and on top of the hill, simply run up close to the #ITEMMysterious Red Crystal# (#COORD[47.49]#) for #DOThe Red Crystal# ."},
      [25] = { str = "Go west across the main path into the furbolg camp (#COORD[40.54]#) to simply get it discovered for #DOHow Big a Threat?# ."},
      [26] = { str = "Go down south on the main path and accept #GETThe Fall of Ameth'Aran# (#COORD[40.60]#)."},
      [27] = { str = "Go east at Ameth'Aran and start working on #DOTools of the Highborne# : kill/loot the #ITEMHighborne# mobs (apparitions). While doing this, also work your way to do the next steps:"},
      [28] = { str = "Do part of #DOThe Fall of Ameth'Aran# : next to the old dark gazebo, click #ITEMThe Lay of Ameth'Aran# (#COORD[43.59]#) white tablet laying on the ground."},
      [29] = { str = "Go south to the other gazebo and do #DOBashal'Aran# : click on the #ITEMAncient Flame# (#COORD[42.62]#). Also do #DOFor Love Eternal# : find and kill/loot #NPCAnaya Dawnrunner#, she patrols clockwise around this gazebo. Use /tar anaya to help you find her."},
      [30] = { str = "Go south a bit more and do the last part of #DOThe Fall of Ameth'Aran# : click on the #ITEMThe Fall of Ameth'Aran# tablet standing upright (#COORD[43.63]#)."},
      [31] = { str = "Make sure #DOTools of the Highborne# is finished: kill/loot the #ITEMHighborne# mobs (apparitions, #1 on map) around Ameth'Aran."},
      [32] = { str = "Make sure you are at least 6,000 XP into level 13 before continuing. Grind on #ITEMHighborne# mobs (apparitions) around Ameth'Aran until you are."},
      [33] = { str = "Go west to the main path and turn in #INThe Fall of Ameth'Aran# (#COORD[40.60]#)."},
      [34] = { str = "To the west of the main path do #DOPlagued Lands# : use #ITEMTharnariun's Hope# quest item on a #NPCRabid Thistle Bear# (around #COORD[39.60]#). NOTE: Make sure you are in range and in clear view of the mob when using the quest item, otherwise you might miss and will have to go back to Auberdine to get a new one."},
      [35] = { str = "Hearth to Auberdine. Make sure you are repaired/resupplied."},
      [36] = { str = "Go west of the Inn on the long docks and turn in #INFor Love Eternal# (#COORD[36.44]#)."},
      [37] = { str = "Just outside of the Inn and across the path by the moonwell, turn in #INThe Red Crystal# (#COORD[38.43]#), accept #GETAs Water Cascades# ."},
      [38] = { str = "Use the #ITEMEmpty Water Tube# quest item at the moonwell next to you (#COORD[38.44]#)."},
      [39] = { str = "Go east across the bridge and at the entrance to the building, turn in #INPlagued Lands# (#COORD[39.43]#), accept #GETCleansing of the Infected# ."},
      [40] = { str = "Go in the building and turn in #INHow Big a Threat?# (#COORD[39.43]#), accept the next #GETpart#. Also accept #GETThundris Windweaver# ."},
      [41] = { str = "Go up in the building and accept #GETThe Tower of Althalaxx# ."},
      [42] = { str = "Take the bride going north and at the dwarf area by the wagon, accept #GETDeep Ocean, Vast Sea# (#COORD[38.41]#)."},
      [43] = { str = "Go in the merchant building next to you (#COORD[37.40]#) and turn in #INTools of the Highborne# and #INThundris Windweaver# , accept #GETThe Cliffspring River# ."},
      [44] = { str = "Go to the Hippogryph dock (south of the Inn) and turn in #INBeached Sea Creature# (#COORD[37.46]#)."},
      [45] = { str = "You should be level 14 now. If you are a Druid, Hunter, Priest, Rogue or Warrior and could benefit from getting your level 14 spells/abilities, then you can do that now in Darnassus. Hunters, the lvl 14 spells/abilities are actually not much worth it so I recommend skipping this step.HUNTER: ] The other classes will have to go to Ironforge, but that is too far away and you will be going there a few levels later anyways, so I recommend just waiting until then. So if you can benefit from getting your lvl 14 abilities, Night Elves can take a Hippogryph ride from the #NPCHippogryph Master# next to you. If you are dwarf, gnome or human you will have to take the Boat to Teldrassil (at #COORD[33.40]#), then to get back to Auberdine take the flight path (at #COORD[58.94]# in Teldrassil)."},
      [46] = { str = "As you work on the following steps start working on #DOCleansing of the Infected# by killing the #NPC Rabid Thistle Bears#. Also continue working on #DOBuzzbox 323# by kill/looting the Moonstalkers (cats):"},
      [47] = { str = "Go north to Bashal'Aran, up on the hill, in the blue mist, turn in #INBashal'Aran# (#COORD[44.36]#)."},
      [48] = { str = "Go NW out in the sea and do #DODeep Ocean, Vast Sea# : loot the two chest in the two sunken boats. First one, go under the boat and enter the crack on the bottom of the boat (entrance at #COORD[39.29]#), then head NW in the boat and loot the #ITEMSilver Dawning's Lockbox# (#COORD[38.29]#):"},
      [49] = { str = "Head NE and enter the bottom of the other boat (#COORD[40.27]#), then head west in the boat and loot the #ITEMMist Veil's Lockbox# (#COORD[40.28]#)."},
      [50] = { str = "Go NE on the shore and click on the #ITEMBeached Sea Turtle's# arm (#COORD[44.21]#) to accept #GETBeached Sea Turtle# ."},
      [51] = { str = "Just south of you in the open fields of Darkshore, finish #DOBuzzbox 323# by kill/looting the Moonstalkers (cats, #1 on map)."},
      [52] = { str = "Follow the main path east and just past the bridge on your left is #ITEMBuzzbox 323# (#COORD[51.25]#), from it turn in #INBuzzbox 323# , accept #GETBuzzbox 525# ."},
      [53] = { str = "Next to you, drop down at the bottom of the waterfall and do #DOThe Cliffspring River# : use the #ITEMEmpty Sampling Tube #quest item at the bottom of the waterfall (#COORD[51.26]#)."},
      [54] = { str = "Go south, then up and through the waterfall in front of the cave (path entrance at #COORD[55.32]#) and do #DOCave Mushrooms# : loot the mushrooms on the ground in the cave."},
      [55] = { str = "Go south and up on the hill, click on the #ITEMMysterious Red Crystal# (#COORD[47.49]#) to turn in #INAs Water Cascades# , accept #GETThe Fragments Within# ."},
      [56] = { str = "Go SW past the main path to the furbolg camp (around #COORD[40.54]#) and do #DOHow Big a Threat?# : kill the needed Blackwood mobs (furbolgs)."},
      [57] = { str = "Work your way down south while killing #NPC Rabid Thistle Bears# (#6 on map) for #DOCleansing of the Infected# . Eventually make your way to the shoreline at the #ITEMBeached Sea Turtle# (#COORD[37.62]#) and click on its head to accept #GETBeached Sea Turtle# ."},
      [58] = { str = "Continue down south while killing #NPC Rabid Thistle Bears# (#6 on map) for #DOCleansing of the Infected# . Eventually make your way to the shoreline at the #ITEMBeached Sea Creature# (#COORD[36.71]#) and click where the neck meets the body to accept #GETBeached Sea Creature# ."},
      [59] = { str = "East of you around the open fields of Darkshore finish #DOCleansing of the Infected# : kill #NPC Rabid Thistle Bears#. Also start working on #DOBuzzbox 525# by kill/looting #NPC Grizzled Thistle Bears#."},
      [60] = { str = "Go down south (around #COORD[39.76]#) and finish #DOBuzzbox 525# : kill/loot #NPC Grizzled Thistle Bears# (#6 on map)."},
      [61] = { str = "Just right off the main path go to #ITEMBuzzbox 525# (#COORD[41.81]#) and turn in #INBuzzbox 525# ."},
      [62] = { str = "Hearth to Auberdine."},
      [63] = { str = "Go to the Hippogryph dock (south of the Inn, #COORD[37.46]#) and turn in ALL Beached Sea quests you may have."},
      [64] = { str = "Go below the Hippogryph dock, next to the shore and accept #GETFruit of the Sea# (#COORD[36.45]#). NOTE: #DOThe Family and the Fishing Pole# is a fishing quest that takes too much time for XP and I recommend skipping it. If you are bored and want to learn fishing or do something different you can give it a try."},
      [65] = { str = "Just outside of the Inn, next to the mailbox, turn in #INCave Mushrooms# (#COORD[37.44]#), accept #GETOnu# ."},
      [66] = { str = "Just across the path from you, near the moonwell, turn in #INThe Fragments Within# (#COORD[38.43]#)."},
      [67] = { str = "Take the bridge north and just outside of the merchant building (to your left), accept #GETThe Absent Minded Prospector# (#COORD[37.42]#)."},
      [68] = { str = "Go in the merchant building next to you and turn in #INThe Cliffspring River# (#COORD[37.40]#), accept #GETThe Blackwood Corrupted# (requires lvl 15). Make sure you are repaired/resupplied."},
      [69] = { str = "Just outside of the building at the dwarf camp next to the wagon, turn in #INDeep Ocean, Vast Sea# (#COORD[38.41]#)."},
      [70] = { str = "Take the SE bridge to the other building and at the entrance, turn in #INCleansing of the Infected# (#COORD[39.43]#), accept #GETTharnariun's Hope# ."},
      [71] = { str = "Go in the building and turn in #INHow Big a Threat?# (#COORD[39.43]#). Accept #GETA Lost Master# ."},
      [72] = { str = "Go to the moonwell in Auberdine and use your #ITEMEmpty Cleansing Bowl# quest item in it (#COORD[38.44]#)."},
      [73] = { str = "If you are level 16 by now: If you are a Druid, Priest, Rogue or Warrior and could benefit from getting your level 16 spells/abilities, you can do that now in Darnassus. Hunters, to save extra time, I recommend skipping this step and getting your spells/abilities once you get to HUNTER: Loch Modan later on. ] The other classes will have to go to Ironforge, but that is too far away and you will be going there very soon anyways, so I recommend just waiting until then. So if you can benefit from getting your lvl 16 abilities, you can take a Hippogryph ride from the #NPCHippogryph Master# (#COORD[36.46]#) or you might need to take the boat on the docks. Then hearth (or fly back) to Auberdine."},
      [74] = { str = "Go NE and do part of #DOThe Blackwood Corrupted# : loot the #ITEMBlackwood Grain Stores# (#COORD[51.35]#)."},
      [75] = { str = "Go up to the small cave (path entrance at #COORD[53.37]#). Once up there do #DOTharnariun's Hope# : kill #NPCDen Mother#."},
      [76] = { str = "Go NE a bit to the other furbolg camp and finish #DOThe Blackwood Corrupted# : loot the #ITEMBlackwood Nut Stores# (#COORD[52.33]#). See next steps for what else to do:"},
      [77] = { str = "On the other side of this camp, loot the #ITEM Blackwood Fruit Stores# (#COORD[53.33]#)."},
      [78] = { str = "Use the #ITEMFilled Cleansing Bowl# quest item at the Bonfire in the middle of the camp (#COORD[52.33]#). Kill #NPCXabraxxis# (lvl 19) that spawns, then loot #ITEMXabraxxis' Demon Bag# that spawns on the ground."},
      [79] = { str = "Go NE and just off the main path next to a rock, turn in #INThe Tower of Althalaxx# (#COORD[55.25]#), accept the next #GETpart#."},
      [80] = { str = "Go SE a bit (around the tower, #COORD[55.27]#) and do #DOThe Tower of Althalaxx# : kill/loot #NPCDark Strand Fanatics# (female humans)."},
      [81] = { str = "Back just off the main path next to a rock, turn in #INThe Tower of Althalaxx# (#COORD[55.25]#, #6 on map), accept the next #GETpart#."},
      [82] = { str = "Go north to the shore and click on the #ITEMBeached Sea Turtle's# head (#COORD[53.18]#) to accept #GETBeached Sea Turtle# ."},
      [83] = { str = "Work your way west along the shore and do #DOFruit of the Sea# : kill/loot #NPCEncrusted Tide Crawlers# (higher lvl crabs) and #NPCReef Crawlers# (lower lvl crabs more west)."},
      [84] = { str = "Hearth to Auberdine. If hearthstone is still on a cooldown, then die on purpose, res at spirit, then go to Auberdine. If you died on purpose, then turn in the following 4 quests in reverse:"},
      [85] = { str = "Go below the Hippogryph dock, next to the shore and turn in #INFruit of the Sea# (#COORD[36.45]#)."},
      [86] = { str = "Go to the Hippogryph dock (south of the Inn) and turn in #INBeached Sea Turtle# (#COORD[37.46]#)."},
      [87] = { str = "Take the north bridge and in the merchant building, turn in #INThe Blackwood Corrupted# (#COORD[37.40]#). Make sure you are repaired/resupplied."},
      [88] = { str = "Take the SE bridge to the other building and at the entrance, turn in #INTharnariun's Hope# (#COORD[39.43]#)."},
      [89] = { str = "Out on the long docks, take the boat to Menethil (#COORD[32.44]#)."},
      [90] = { str = "At Menethil Harbor, go to the #NPCGryphon Master# (#COORD[10.60]#), get the FP if you are a NE. Now depending on what race/class you are determines what you should do. If you are a Night Elf, you will have to run all the way to Loch Modan (run SE through Wetlands, entrance at #COORD[54.70]# in Wetlands). If you are another race that needs new spells/abilities, then fly to Ironforge, Dun Morogh to get them, if not (or otherwise) then fly to Thelsamar, Loch Modan. Hunters, you will be getting your spells/abilities soon in HUNTER: Loch Modan.]"},
    },
  },
  [1718] = {
    title = "17-18 Loch Modan",
    items = {
      [1] = { str = "NIGHT ELF ONLY: Go down south to Thelsamar, find #NPC Mountaineer Kadrell# (he patrols back and forth in the town, around #COORD[35.47]#) and from him accept #GETMountaineer Stormpike's Task# and #GETRat Catching# ."},
      [2] = { str = "NIGHT ELF ONLY: South in the town, go to the #NPCGryphon Master# (#COORD[34.51]#) and get the FP."},
      [3] = { str = "At Thelsamar, go down in the eastern most hut and accept #GETIronband's Excavation# (#COORD[37.47]# in Loch Modan)."},
      [4] = { str = "Go east to Ironband's Excavation Site and turn in #INIronband's Excavation# (#COORD[65.67]#), accept #GETGathering Idols# ."},
      [5] = { str = "Across the camp, accept #GETExcavation Progress Report# (#COORD[66.66]#)."},
      [6] = { str = "Just to the east of you around the Excavation Site, do #DOGathering Idols# : kill/loot the troggs."},
      [7] = { str = "Go back to the small camp at the Excavation Site and turn in #INGathering Idols# (#COORD[65.67]#, #5 on map)."},
      [8] = { str = "Go east to enter The Farstrider Lodge (entrance on the east side of the lodge), make a right, then accept #GETCrocolisk Hunting# (#COORD[82.62]#). Hunters, get new spells/abilities from the HUNTER: #NPCHunter Trainer# here in the lodge, and the #NPCPet Trainer# is there as well.]"},
      [9] = { str = "At the other side of the lodge, accept #GETA Hunter's Boast# (#COORD[83.65]#)."},
      [10] = { str = "Just west of The Farstrider Lodge, do #DOA Hunter's Boast# : kill #NPCMountain Buzzards#."},
      [11] = { str = "Go back to The Farstrider Lodge, make a left and turn in #INA Hunter's Boast# (#COORD[83.65]#), accept #GETA Hunter's Challenge# ."},
      [12] = { str = "Go NW (starting at #COORD[76.46]#) and do #DOA Hunter's Challenge# : kill #NPC Elder Mountain Boars#."},
      [13] = { str = "Go back to The Farstrider Lodge, make a left and turn in #INA Hunter's Challenge# (#COORD[83.65]#, #2 on map)."},
      [14] = { str = "In the middle of the lodge, accept #GETVyrin's Revenge# (#COORD[82.64]#)."},
      [15] = { str = "Go NW next to the lake and accept #GETBingles' Missing Supplies# (#COORD[64.48]#)."},
      [16] = { str = "Along the eastern shore of The Loch lake and on the two smaller islands in the lake do #DOCrocolisk Hunting# : kill/loot #NPCLoch Crocolisks#."},
      [17] = { str = "Go up north to the bigger island, starting at the bottom eastern part and do #DOBingles' Missing Supplies# : loot the 4 quest objects on the ground. First one, loot #ITEMBingles's Blastencapper# next to the hut (#COORD[54.27]#). See next steps for the other 3 to loot:"},
      [18] = { str = "Go west and loot #ITEMBingles's Toolbucket# (wrench) next to the shore (#COORD[49.30]#)."},
      [19] = { str = "Go NE a bit and loot #ITEMBingles's Toolbucket# (hammer) next to the light colored wagon (#COORD[52.24]#)."},
      [20] = { str = "Go NW a bit and loot #ITEMBingles's Toolbucket# (screwdriver) at the trogg camp (#COORD[48.20]#)."},
      [21] = { str = "Go NW to the entrance of Stonewrought Dam, go inside and you can get repaired/resupplied (#COORD[41.13]#). Be careful not to sell your #ITEMCrocolisk Meat# to a vendor!"},
      [22] = { str = "Go SE in the Dam and then under the tent, accept #GETA Dark Threat Looms# (#COORD[46.14]#)."},
      [23] = { str = "Go east to exit the Dam, then on the outside entrance of the Dam, you will see two #NPCDark Iron Sappers#. They are guarding a #ITEMSuspicious Barrel# (#COORD[56.13]#), click it to turn in #INA Dark Threat Looms# , accept the next #GETpart#."},
      [24] = { str = "Go west back onto the Dam and under the tent, turn in #INA Dark Threat Looms# (#COORD[46.14]#, #2 on map), SKIP the next #DOpart#."},
      [25] = { str = "Go west to Silver Stream Mine (entrance at #COORD[35.19]#) and do (if you haven't yet) #DOFilthy Paws# : loot the #ITEMMiner's League Crates# inside the mine. NIGHT ELF ONLY: While here also do #GETRat Catching# (kill the needed troggs)."},
      [26] = { str = "Turn in (if you need to) #INFilthy Paws# up in the tower (west at #COORD[25.18]#). And for Night Elves: turn in #INRat Catching# and #INMountaineer Stormpike's Task# , accept #GETStormpike's Order# ."},
      [27] = { str = "Follow the main path south to Thelsamar and make sure you are repaired/resupplied from #NPCMorhan Coppertongue# (#COORD[34.47]#) standing in front of the hut entrance.."},
      [28] = { str = "Go down in the eastern most hut and turn in #INExcavation Progress Report# (#COORD[37.47]#), accept #GETReport to Ironforge# ."},
      [29] = { str = "GROUP: If you can get a group, you can go SE and try to do #DOVyrin's Revenge# : kill/loot #NPCOl' Sooty# (lvl 20 Elite at 3 different spawns, see map)."},
      [30] = { str = "Go NE next to the lake and turn in #INBingles' Missing Supplies# (#COORD[64.48]#)."},
      [31] = { str = "Go east to The Farstrider Lodge, make a right in the lodge, then turn in #INCrocolisk Hunting# (#COORD[82.62]#)."},
      [32] = { str = "At the other side of the lodge, turn in (if you did it) #INVyrin's Revenge# (#COORD[83.65]#), accept the next #GETpart#."},
      [33] = { str = "Turn in (if you have it) #INVyrin's Revenge# in the middle of the lodge (#COORD[82.64]#)."},
      [34] = { str = "In the lodge, get repaired/resupplied. Hunters, if you need to, get your level 18 spells/abilities at the HUNTER: #NPCHunter Trainer# in the lodge.]"},
      [35] = { str = "Go just SW of the lodge and die on purpose, res at spirit to get to Thelsamar."},
      [36] = { str = "Go to the #NPCGryphon Master# (#COORD[34.51]#) south in Thelsamar and take a flight to Ironforge, Dun Morogh. Night Elves, see path on map to take to get to Ironforge! Also if you still have #DOVyrin's Revenge# in your quest log, abandon it."},
      [37] = { str = "You can upgrade First Aid up in the building from #NPCNissa Firestone# (#COORD[55.58]#)."},
      [38] = { str = "NIGHT ELF ONLY: Get the Flight Path in Ironforge from the #NPCGryphon Master# (#COORD[55.48]#)."},
      [39] = { str = "Go NE in Ironforge and turn in #INReport to Ironforge# (#COORD[75.12]#), SKIP #DOPowder to Ironband# ."},
      [40] = { str = "Find your class trainer and get new spells/abilities (if you need to). Also, if you can afford it, you can visit the Weapon Masters at Timberline Arms (#COORD[62.89]#) to learn new weapon possibilities. Hunters, you can find the HUNTER: Hunter Trainers (at #COORD[71.84]#).]"},
      [41] = { str = "Go east to Tinker Town and accept #GETSpeak with Shoni# (#COORD[69.51]#)."},
      [42] = { str = "Go east to enter The Deeprun Tram (#COORD[75.51]#). Take the Tram ride and once you get to the other side exit north through the tunnel."},
      [43] = { str = "Once at Stormwind, just SW, turn in #INSpeak with Shoni# (#COORD[55.12]#), SKIP #DOUnderground Assault# (Dungeon)."},
      [44] = { str = "Go just SE a bit and turn in #INStormpike's Order# (#COORD[58.17]#)."},
      [45] = { str = "You can stop at the #NPCWeapon Master# (at The Trade District, #COORD[57.58]#) and learn new weapon possibilities if you can afford to."},
      [46] = { str = "Go to the bank (#COORD[57.73]#) and put the following item into it: #ITEMLetter to Delgren#. And put into the bank (if you have any of these items): #ITEMFandral's Message# and any #ITEMFine Moonstalker Pelts#."},
      [47] = { str = "HUMAN ONLY: SE in The Trade District, go to the#NPC Gryphon Master# (#COORD[66.62]#) and fly to Lakeshire, Redridge. Then skip to step #2 on the next section!"},
      [48] = { str = "NIGHT ELF, GNOME & DWARF ONLY: SE in The Trade District, get the Flight Path from the #NPCGryphon Master# (#COORD[66.62]#, #12 on map)."},
      [49] = { str = "NIGHT ELF, GNOME & DWARF ONLY: Go SE to exit Stormwind (#COORD[71.89]#).."},
      [50] = { str = "NIGHT ELF, GNOME & DWARF ONLY: In Elwynn Forest follow the main path east to enter Redridge Mountains (#COORD[94.72]# in Elwynn Forest)."},
    },
  },
  [1820] = {
    title = "18-20 Redridge Mountains",
    items = {
      [1] = { str = "Go NE and on your left before the bridge turn in #INEncroaching Gnolls# (#COORD[31.60]#), accept #GETAssessing the Threat# . HUMANS ONLY: Humans only need to accept #GETAssessing the Threat# then skip to step #4."},
      [2] = { str = "Next to you, get the Flight Path from the #NPCGryphon Master#."},
      [3] = { str = "Go across the bridge and on your left, accept #GETThe Lost Tools# (#COORD[32.49]#)."},
      [4] = { str = "On the dock, accept #GETHilary's Necklace# (#COORD[29.54]#)."},
      [5] = { str = "Next to the shack, accept #GETSelling Fish# (#COORD[28.47]#)."},
      [6] = { str = "Go inside of the Inn and next to the bar, accept #GETA Free Lunch# (#COORD[27.44]#)."},
      [7] = { str = "Go west at Lakeshire and in the bigger house, accept #GETRedridge Goulash# (#COORD[23.44]#)."},
      [8] = { str = "Go west and start working on #DORedridge Goulash# : kill/loot #NPCGreat Goretusks# for the #ITEMsnouts# (around #COORD[17.47]#). There is only 8 mob spawns in this area, so kill what you can and move on.. NOTE: Watch out for #NPCBellygrub# (lvl 24 mob), we will be able to solo him later in the guide. Keep the next step in mind:"},
      [9] = { str = "Go in the lake and do #DOHilary's Necklace# : loot the #ITEM Glinting Mud# at the bottom of the lake. This mud has several different spawn locations under the lake, see map for locations."},
      [10] = { str = "Go south at the intersection of the main path and turn in #INA Free Lunch# (#COORD[15.71]#), accept #GETVisit the Herbalist# ."},
      [11] = { str = "Go just north to the gnoll camp and start working on part of #DOAssessing the Threat# : kill #NPCRedridge Mongrels# (around #COORD[15.63]#). NOTE: The Poachers are not at this camp, we will get them along with more Mongrels at the next step."},
      [12] = { str = "Grind east killing #NPCTarantulas# and #NPCGreat Goretusks# (#1 on map) for #DORedridge Goulash# . Once you get to the other gnoll camp (around #COORD[30.82]#) finish #DOAssessing the Threat# : kill #NPCRedridge Mongrels# and #NPCRedridge Poachers#."},
      [13] = { str = "Start working on part of #DORedridge Goulash# by killing #NPCDire Condor# (red birds) south middle of Redridge Mountains (starting at #COORD[46.77]#). Also, while in this area kill any #NPC Black Dragon Whelps# you see as they die fast and yield good XP/Time. Keep next step in mind:"},
      [14] = { str = "Around the middle of Lake Everstill start working on #DOSelling Fish# : kill/loot the murlocs (any of them can drop the #ITEMSpotted Sunfish#). NOTE: Make sure you save any #ITEMMurloc Fins# as you will use them for a later #DOquest#. You can work your way to the next steps when you run out of mobs:"},
      [15] = { str = "South of the bridge from Lakeshire, turn in #INAssessing the Threat# (#COORD[31.60]#)."},
      [16] = { str = "Go NE down in the lake and do #DOThe Lost Tools# : loot the #ITEM Sunken Chest# (next to a small sunken boat, #COORD[41.55]#)."},
      [17] = { str = "Finish #DOSelling Fish# : kill/loot the murlocs around Lake Everstill (any of them can drop the #ITEMSpotted Sunfish#). #7 on map. Also make sure you obtain 8 #ITEMMurloc Fins# (for a later #DOquest#), and remember to not sell them to a vendor!"},
      [18] = { str = "Finish #DORedridge Goulash# . For the spider meat and condor meat you can find #NPCGreater Tarantulas# (#11 on map) and more #NPCDire Condor# (#6 on map) up north (around #COORD[53.42]#). And #NPCGreat Goretusks# (#1 on map) are scattered around the western side of Redridge Mountains. NOTE: Make sure you do not sell these quest items to a vendor!"},
      [19] = { str = "North of the bridge at Lakeshire, turn in #INThe Lost Tools# (#COORD[32.49]#). Accept #GETThe Everstill Bridge# ."},
      [20] = { str = "On the dock, turn in #INHilary's Necklace# (#COORD[29.54]#)."},
      [21] = { str = "Next to the shack, turn in #INSelling Fish# (#COORD[28.47]#). Then if you are level 20, turn in #INMurloc Poachers# "},
      [22] = { str = "West at Lakeshire, turn in #INVisit the Herbalist# (#COORD[22.46]#), accept #GETDelivering Daffodils# ."},
      [23] = { str = "Go in the bigger house next to you and turn in #INRedridge Goulash# (#COORD[23.44]#)."},
      [24] = { str = "Go in Lakeshire Inn and turn in #INDelivering Daffodils# (#COORD[27.44]#). Make sure you are repaired/resupplied."},
      [25] = { str = "Go north of Lakeshire and do #DOThe Everstill Bridge# : kill/loot the gnolls. Except for the Alphas, the rest of the gnolls has a chance to drop the quest items you need."},
      [26] = { str = "Go back to Lakeshire and north of the bridge, turn in #INThe Everstill Bridge# (#COORD[32.49]#, #1 on map)."},
      [27] = { str = "At this point make sure you are level 20. I recommend grinding on #NPC Black Dragon Whelps# south of Lake Everstill until you are."},
      [28] = { str = "Once level 20, in Lakeshire next to the shack, accept and turn in #INMurloc Poachers# (#COORD[28.47]#, #3 on map). This quest requires the 8 #ITEMMurloc Fins# you farmed earlier."},
      [29] = { str = "Make sure you are repaired/resupplied."},
      [30] = { str = "It's time to get your level 20 spells/abilities. Go to the #NPCGryphon Master# (#COORD[31.59]#) and then fly to Stormwind, Elwynn."},
      [31] = { str = "At Stormwind, go to the bank (#COORD[57.73]#) and get the following items out: #ITEMLetter to Delgren# and (if you have any of these items): #ITEMFandral's Message# and any #ITEMFine Moonstalker Pelts#."},
      [32] = { str = "Get your new spells/abilities. Hunters, you can find the Hunter Trainers in HUNTER: Stormwind (at #COORD[62.15]#), and make sure you learn Growl R3 from the #NPCPet Trainer#. ]"},
    }
  },
}