--[[--------------------------------------------------
003_Alliance_20to30.lua
Authors: mrmr
Version: 1.04.2
------------------------------------------------------
Description: Guide Serie - 003 From Lvl 20 to Lvl 30
1.04.1
-- First Release
Alliance's Guide
from level 20 to lever 30
1.04.2
-- no changes in here for this revision

Faelwen
04 June 2019 - Guide replaced with Joanna's Alliance Guide (https://www.joanasworld.com/alliance-20-30.php)

------------------------------------------------------
Connection:
--]]--------------------------------------------------

Table_003_Alliance_20to30 = {
  [2021] = {
    title = "20-21 Darkshore",
    items = {
      [1] = { str = "Just outside of the Inn, from the #ITEM WANTED: Murkdeep!# sign, accept #GETWANTED: Murkdeep!# (#COORD[37.44]#)."},
      [2] = { str = "Follow the main path down south to the Grove of the Ancients and from #NPC Onu# (big tree NPC, #COORD[43.76]#), turn in #INOnu# , accept #GETThe Master's Glaive# . Also turn in (if you have it) #INGrove of the Ancients# ."},
      [3] = { str = "As you work on the following steps also start working on #DOA Lost Master# by kill/looting #NPC Moonstalker Sires# and #NPC Moonstalker Matriarch# (cats) south in Darkshore:"},
      [4] = { str = "Go SW to The Master's Glaive (the big glowing sword, #COORD[39.87]#) and get it discovered for #DOThe Master's Glaive# . Then use the #ITEM Phial of Scrying# quest item to spawn a #ITEM Scrying Bowl# next to you, then turn in #INThe Master's Glaive# , accept #GETThe Twilight Camp# ."},
      [5] = { str = "At The Master's Glaive there are two books around the altar (table), click on the #ITEM Twilight Tome# (#COORD[38.86]#) on the north side of the altar to turn in #INThe Twilight Camp# , accept #GETReturn to Onu# ."},
      [6] = { str = "Go south a bit behind the big glowing sword and accept and do the escort #DOTherylune's Escape# (#COORD[39.87]#). This escort only takes a couple minutes and leads to the main path east. NOTE: While kill/looting the Twilight mobs in this area you have a chance to get an #ITEM item#, that starts #GETThe Powers Below# , accept it if you were able to find it."},
      [7] = { str = "Go west to Remtravel's Excavation and turn in #INThe Absent Minded Prospector# (#COORD[36.84]#). Accept and do the next #DO part# (escort). Simply escort him around the Excavation site. Try to keep aggro off of #NPC Prospector Remtravel#, as he has low HP and can die easily."},
      [8] = { str = "Go west to the shore at the small Greymist murloc camp (#COORD[37.77]#) and do #DOWANTED: Murkdeep!# : clear all the murlocs at the small camp, then kill the two #NPC Greymist Warriors# that spawn, then kill #NPC Murkdeep# that spawns after that. NOTE: These mobs spawn at the sea and run onto the coast."},
      [9] = { str = "Go south to the #ITEM Beached Sea Creature# (#COORD[33.81]#) and click where the neck meets the body to accept #GETBeached Sea Creature# ."},
      [10] = { str = "Go south along the shore a bit more and click on the #ITEM Beached Sea Turtle's# arm (#COORD[32.84]#) to accept #GETBeached Sea Turtle# "},
      [11] = { str = "Go south along the shore a bit more and click on the #ITEM Beached Sea Turtle's# head (#COORD[31.85]#) to accept #GETBeached Sea Turtle# "},
      [12] = { str = "South a bit more, click on the #ITEM Beached Sea Creature# where the neck meets the body (#COORD[31.87]#) to accept #GETBeached Sea Creature# ."},
      [13] = { str = "Go NE to the Grove of the Ancients and from #NPC Onu# (big tree NPC, #COORD[43.76]#), turn in #INReturn to Onu# . Wait a few seconds, then accept #GETMathystra Relics# ."},
      [14] = { str = "Next to you, get resupplied. NOTE: At this point you no longer need the #ITEM Phial of Scrying# quest item. This can be destroyed to save bag space."},
      [15] = { str = "At the Grove of the Ancients, accept and do the escort #DOThe Sleeper Has Awakened# (#COORD[44.76]#). First thing to do is loot #ITEM Kerlonian's Chest# next to you to get the #ITEM Horn of Awakening#. #NPC Kerlonian Evershade# falls asleep periodically and you will need to use this horn to wake him up, so keep an eye out for him and use /tar kerlonian if you lose sight of him. Lead him to the next step:"},
      [16] = { str = "Go south a along the main path and right before entering Ashenvale make a left on the path into some mountains and from #NPC Sentinel Aynasha# (#COORD[46.90]#), accept and do the escort #DOOne Shot. One Kill.# (no exclamation mark): simply wait right there and kill several waves of furblogs."},
      [17] = { str = "Keep escorting #NPC Kerlonian Evershade# south into Ashenvale..."},
    },
  },
  [2122] = {
    title = "21-22 Ashenvale",
    items = {
      [1] = { str = "Just south at Maestra's Post, turn in #INThe Tower of Althalaxx# (#COORD[26.39]#), accept the next #GET part#."},
      [2] = { str = "Next to you, accept #GETBathran's Hair# ."},
      [3] = { str = "NOTE: As you do the following quests, you can focus on kill/looting the #NPC Ghostpaw Runners# to obtain 10 #ITEM Lean Wolf Flanks#, and do not sell them to a vendor! This is used for a later #DO quest# in Duskwood:"},
      [4] = { str = "Go north to The Ruins of Ordil' Aran (around #COORD[31.31]#) and do #DOThe Tower of Althalaxx# : keep killing the mobs there until the #ITEM Glowing Soul Gem# drops (very low drop rate). This is a good grinding spot, so be patient and grind the area clear anyways even if you found the item. If you have not found the item and the area is clear, then you can do the next step and come back to do this afterwards:"},
      [5] = { str = "Go north to Bathran's Haunt (around #COORD[31.23]#) and do #DOBathran's Hair# : loot the #ITEM Plant Bundles# around the area. They are kind of hard to see."},
      [6] = { str = "Go south in Maestra's Post and turn in #INBathran's Hair# (#COORD[26.39]#, #2 on map). Wait a few second, then accept #GETOrendil's Cure# ."},
      [7] = { str = "Next to you, turn in #INThe Tower of Althalaxx# . Wait a minute, then accept the next #GET part#."},
      [8] = { str = "Go south to The Shrine of Aessina and turn in #INTherylune's Escape# (#COORD[23.52]#)."},
      [9] = { str = "Follow the main path east into Astranaar, make a left after the blue bridge and get the Flight Path from the #NPC Hippogryph Master# (#COORD[34.48]#)."},
      [10] = { str = "Along the main path as you enter the town, accept #GETThe Zoram Strand# (#COORD[35.49]#)."},
      [11] = { str = "Go to the first house on your right and accept #GETOn Guard in Stonetalon# (#COORD[35.50]#)."},
      [12] = { str = "Go in the house to get repaired/resupplied. NOTE: You can sell all the Shredder Operating Manuals you find in Ashenvale as my guide will not tell you to do that quest."},
      [13] = { str = "Across the path, next to the glowing gazebo, accept #GETJourney to Stonetalon Peak# (#COORD[36.49]#)."},
      [14] = { str = "Go in the Inn just SE of you and accept #GETRaene's Cleansing# and #GETCulling the Threat# (#COORD[37.50]#)."},
      [15] = { str = "Go up the ramp, then talk to the #NPC Innkeeper# (#COORD[37.49]#) to make Astranaar your new home. Hunters, make sure you buy at least 1 stack of Bread to feed a pet you are about to tame from the HUNTER: ] #NPC Innkeeper#."},
      [16] = { str = "Hunter, Just outside of the Inn (next to the mailbox) go to the #NPC Stable Master# (#COORD[36.50]#) and stable your pet."},
      [17] = { str = "At the south-eastern most hut at Astranaar, turn in #INOrendil's Cure# (#COORD[37.52]#). Wait a few seconds then accept #GETElune's Tear# ."},
      [18] = { str = "Follow the main path west, then north, then go west towards The Zoram Strand and at the small camp, accept #GETThe Ancient Statuette# (#COORD[15.31]#)."},
      [19] = { str = "Hunter, Go west to the shore and tame a #NPC Clattering Crawler# for Claw R3. Try to tame a lvl 20 and then teach it Growl 3. Use this pet to do the following steps:"},
      [20] = { str = "Along The Zoram Strand start working on #DOThe Zoram Strand# : kill/loot the Wrathtail mobs (fishmen) while working your way to do the next steps:"},
      [21] = { str = "Go up north along the shore and do #DOThe Ancient Statuette# : loot the #ITEM Ancient Statuette# (white statue laying on the ground, #COORD[14.21]#)."},
      [22] = { str = "Go back south to the small camp and turn in #INThe Ancient Statuette# (#COORD[15.31]#), wait a few seconds then accept #GETRuuzel# ."},
      [23] = { str = "Go to the small island NW in The Zoram Strand and do #DORuuzel# : kill/loot #NPC Ruuzel#. She patrols clockwise around the small island with two bodyguards."},
      [24] = { str = "Make sure #DOThe Zoram Strand# is finished: kill/loot the Wrathtail mobs (fishmen) around The Zoram Strand. #1 on map."},
      [25] = { str = "Go SE to the small camp and turn in #INRuuzel# (#COORD[15.31]#, #3 on map)."},
      [26] = { str = "Go SE to the little island in the middle of Lake Falathim and turn in #INRaene's Cleansing# (#COORD[20.42]#), accept the next #GET part#."},
      [27] = { str = "In the immediate area around Lake Falathim, do #DORaene's Cleansing# : kill/loot the Saltspittle mobs (murlocs) until the #ITEM Glowing Gem# drops."},
      [28] = { str = "Hearth to Astranaar."},
      [29] = { str = "In the Inn, down the ramp, turn in #INRaene's Cleansing# (#COORD[37.50]#). Accept #GETRaene's Cleansing# and #GETAn Aggressive Defense# . Make sure you are repaired/resupplied. NOTE: The quest item #ITEM Teronis' Journal# can be destroyed as it is no longer used."},
      [30] = { str = "Hunter, Abandon your crab and just outside of the Inn (next to the mailbox) go to the #NPC Stable Master# (#COORD[36.50]#) and get your main pet back out and teach him Claw R3."},
      [31] = { str = "NW in Astranaar, turn in #INThe Zoram Strand# (#COORD[35.49]#). Accept #GETPridewings of Stonetalon# ."},
      [32] = { str = "Go NE to Iris Lake (path entrance at #COORD[43.46]#).."},
      [33] = { str = "At the middle of Iris Lake, do #DOElune's Tear# : loot an #ITEM Elune's Tear# (white ball) on the ground (#COORD[46.46]#)."},
      [34] = { str = "Go east at Iris Lake and go up the mountains (around #COORD[48.47]#) to take a shortcut to go east.."},
      [35] = { str = "Go NE to the Moonwell and turn in #INRaene's Cleansing# (#COORD[54.46]#), accept the next #GET part#."},
      [36] = { str = "Go down south to the furblog camp (around #COORD[51.61]#) and do #DOAn Aggressive Defense# : kill the needed Foulweald mobs (furblogs). Hunters, once you are level 22, you can go down south to HUNTER: Silverwing Refuge and get new spells/abilities at the #NPC Hunter Trainer# (#COORD[50.68]#) there.]"},
      [37] = { str = "Hearth (or run back if its still on a cooldown) to Astranaar."},
      [38] = { str = "In the Inn, turn in #INAn Aggressive Defense# (#COORD[37.50]#). Make sure you are repaired/resupplied."},
      [39] = { str = "At the south-eastern most hut at Astranaar, turn in #INElune's Tear# (#COORD[37.52]#). Wait a few seconds, then accept #GETThe Ruins of Stardust# ."},
      [40] = { str = "Go down south to The Ruins of Stardust (the island in the middle of the lake, around #COORD[33.68]#) and do #DOThe Ruins of Stardust# : loot #ITEM Stardust Covered Bushes#."},
      [41] = { str = "Go east to The Talondeep Path (cave entrance at #COORD[42.71]#) and go through it to get to Stonetalon Mountains.."},
    },
  },
  [2223] = {
    title = "22-23 Stonetalon Mountains",
    items = {
      [1] = { str = "Go south a bit and up on the hill, turn in #INOn Guard in Stonetalon# (#COORD[60.67]#), accept the next #GET part#."},
      [2] = { str = "Next to you, turn in #INOn Guard in Stonetalon# , accept #GETA Gnome's Respite# ."},
      [3] = { str = "All around Windshear Crag do #DOSuper Reaper 6000# along with #DOA Gnome's Respite# : kill/loot the #NPC Venture Co. Operators# until the #ITEM Blueprints# drop (its a low drop rate). Also kill 10 #NPC Loggers# and #NPC Deforesters# (scattered all around Windshear Crag). NOTE: There are a lot of operators on the big tank shredder, (#COORD[63.54]#) and more around other structures in the area. Keep the next step in mind:"},
      [4] = { str = "There is a #NPC goblin merchant# to the west in Windshear Crag (#COORD[58.52]#) that you can get repaired/resupplied at."},
      [5] = { str = "Go back SW to the goblin in the hut and turn in #INSuper Reaper 6000# (#COORD[59.63]#, #1 on map), SKIP #DOFurther Instructions# ."},
      [6] = { str = "Go south a bit and up on the hill, turn in #INA Gnome's Respite# (#COORD[59.67]#, #2 on map). Accept #GETAn Old Colleague# and #GETA Scroll from Mauren# ."},
      [7] = { str = "Follow the main path north to Mirkfallon Lake (starting around #COORD[50.42]#) and do #DOPridewings of Stonetalon# : kill/loot Pridewing mobs (wyverns) around the lake. There is a large concentration of these mobs (NE around #COORD[54.36]#)."},
      [8] = { str = "Go north to Stonetalon Peak and in front of the Moonwell turn in #INJourney to Stonetalon Peak# (#COORD[37.8]#), SKIP #DOReclaiming the Charred Vale# ."},
      [9] = { str = "Next to the Moonwell, go to the #NPC Hippogryph Master# (#COORD[36.7]#) and fly to Auberdine, Darkshore.."},
    },
  },
  [2324] = {
    title = "23-24 Darkshore",
    items = {
      [1] = { str = "Go in the Inn and from #NPC Innkeeper Shaussiy# (#COORD[37.44]#), talk to her to make Auberdine your new home. Make sure you are repaired/resupplied."},
      [2] = { str = "Just outside of the Inn, next to the Moonwell, turn in #INWANTED: Murkdeep!# (#COORD[38.43]#)."},
      [3] = { str = "Go north across the bridge in Auberdine and just outside of the merchant building, turn in #INThe Absent Minded Prospector# (#COORD[37.42]#), accept the next #GET part#."},
      [4] = { str = "Take a shortcut straight through the merchant building then go NE to Ruins of Mathystra (around #COORD[58.23]#) and do #DOMathystra Relics# : loot the #ITEM Mathystra Relics# on the ground."},
      [5] = { str = "Go north to the shore and accept #GETGyromast's Retrieval# (on the small hill, #COORD[57.13]#)."},
      [6] = { str = "Around the immediate area do part of #DOGyromast's Retrieval# : kill/loot the #NPC Raging Reef Crawlers# until the #ITEM Bottom of Gelkak's Key# drops. This key can also drop from the #NPC Encrusted Tide Crawlers# just SW."},
      [7] = { str = "Go north a bit into the water around the sunken ship (around #COORD[55.13]#) and do part of #DOGyromast's Retrieval# : kill/loot the murlocs until the #ITEM Middle of Gelkak's Key# drops."},
      [8] = { str = "Go north in the open fields of Darkshore (around #COORD[61.12]#) and finish #DOGyromast's Retrieval# : kill/loot #NPC Giant Foreststriders# for the #ITEM Top of Gelkak's Key#. Also in this same area, finish #DOA Lost Master# : kill/loot Moonstalkers (cats), there is only 7 spawns up north in Darkshore."},
      [9] = { str = "Go back to the shore and turn in #INGyromast's Retrieval# (on the small hill, #COORD[57.13]#, #6 on map), accept #GETGyromast's Revenge# ."},
      [10] = { str = "Go south a bit along the shore and do #DOGyromast's Revenge# : talk to #NPC The Threshwackonator 4100# (#COORD[56.18]#) to Insert key into it, then lead him to the next step:"},
      [11] = { str = "Go back north to the small hill (#COORD[57.13]#, #6 on map) and then kill #NPC The Threshwackonator 4100# (he's not to hard but be prepared). Then turn in #INGyromast's Revenge# . NOTE: Do NOT sell the reward received: #ITEM Elixir of Water Breathing# (you will be using this later)."},
      [12] = { str = "Hearth to Auberdine. Make sure you are repaired/resupplied. NOTE: The quest item #ITEM Gyromast's Key# is no longer used for anything and can be destroyed to free bag space."},
      [13] = { str = "Go east in Auberdine and in the building, turn in #INA Lost Master# (#COORD[39.43]#). Accept the next #GET part#."},
      [14] = { str = "Follow the main path south to Grove of the Ancients and from #NPC Onu# (big tree NPC, #COORD[43.76]#), turn in #INMathystra Relics# . If you still need to do the escort #DOThe Sleeper Has Awakened# (#COORD[44.76]#), then you can accept and try it again, remember to first loot #ITEM Kerlonian's Chest# next to him to get the #ITEM Horn of Awakening#. #NPC Kerlonian Evershade# falls asleep periodically and you will need to use this horn to wake him up, so keep an eye out for him and use /tar kerlonian if you lose sight of him. You will need to do the next few steps while on this as well."},
      [15] = { str = "Go south to the small cave at Blackwood Den and turn in #INA Lost Master# (#COORD[45.85]#)."},
      [16] = { str = "Accept and do the escort #DOEscape Through Force# . This leads west to the main path at #NPC Grimclaw# (#COORD[42.81]#)."},
      [17] = { str = "You will be headed to Darnassus soon, which means if you are a Druid, Hunter, Priest, Rogue or Warrior and could benefit from getting your level 22 / 24 spells/abilities then grind on any mobs down south in Darkshore until you are at least 1,750 XP away from level 24. I recommend grinding your way down into Ashenvale and continue kill/looting #NPC Ghostpaw Runners# (west in Ashenvale) to obtain 10 #ITEM Lean Wolf Flanks#, and remember to not sell them to a vendor! This is used for a later #DO quest# in Duskwood. If you are on #DOThe Sleeper Has Awakened# , then lead #NPC Kerlonian Evershade# south into Ashenvale. Keep aggro off of #NPC Kerlonian Evershade# as he can die easily. Then go in the hut at Maestra's Post and turn in #INThe Sleeper Has Awakened# (#COORD[27.36]#), if you fail again, then skip it."},
      [18] = { str = "Hearth (or run back if its still on a cooldown) to Auberdine. If you can't hearth and are close to Astranaar, then go to the #NPC Hippogryph Master# (#COORD[34.48]# in Ashenvale) and fly to Auberdine, Darkshore."},
      [19] = { str = "Make sure you are repaired/resupplied."},
      [20] = { str = "Go east in Auberdine and in the building, turn in #INEscape Through Force# (#COORD[39.43]#, #2 on map). Then next to you accept #GETTrek to Ashenvale# (no exclamation mark if lvl 24)."},
      [21] = { str = "Go to the #NPC Hippogryph Master# (south of the Inn, #COORD[36.46]#) and fly to Rut'theran Village, Teldrassil. NOTE: If you do not have the flight path for Rut'theran Village, then you will have to get on the boat on the docks (at #COORD[33.40]#)."},
      [22] = { str = "Go up the path to enter Darnassus through the red portal (#COORD[56.90]#)."},
      [23] = { str = "In Darnassus, go south and just outside of The Temple of the Moon, turn in #INThe Absent Minded Prospector# (#COORD[31.84]#), accept the next #GET part#."},
      [24] = { str = "If you are a Druid, Hunter, Priest, Rogue or Warrior get new spells/abilities in Darnassus. Hunters, go north to HUNTER: Cenarion Enclave (#COORD[40.9]#).]"},
      [25] = { str = "Go to Darnassus's bank (#COORD[40.42]#) and put the following items into it: 5 #ITEM Elixir of Water Breathing# (and if you have it) #ITEM Book: The Powers Below#."},
      [26] = { str = "Go back through the red portal in Darnassus (#COORD[28.40]#)."},
      [27] = { str = "Go to the #NPC Hippogryph Master# (#COORD[58.94]#) on the dock and fly to Astranaar, Ashenvale."},
    },
  },
  [2424] = {
    title = "24-24 Ashenvale",
    items = {
      [1] = { str = "Go in the Inn and turn in #INTrek to Ashenvale# (#COORD[37.50]#). Make sure you are repaired/resupplied."},
      [2] = { str = "At the south-eastern most hut at Astranaar, turn in #INThe Ruins of Stardust# (#COORD[37.52]#). Wait a few seconds, then accept #GETFallen Sky Lake# ."},
      [3] = { str = "Go SW to Fire Scar Shrine (grind on all mobs along the way) and go to the path (at #COORD[26.63]#).."},
      [4] = { str = "Go up the path and do #DOThe Tower of Althalaxx# : kill/loot #NPC Ilkrud Magthrull# (#COORD[25.61]#)."},
      [5] = { str = "Grind your way north through Thistlefur Village and then do #DOCulling the Threat# : kill/loot #NPC Dal Bloodclaw# (grey furblog patrols around #COORD[38.35]#)."},
      [6] = { str = "Keep grinding on furblogs in Thistlefur Village until you are at least a 1/4 way into level 24."},
      [7] = { str = "Go west to Maestra's Post and turn in #INThe Tower of Althalaxx# (#COORD[26.39]#), accept the next #GET part#."},
      [8] = { str = "Next to you, I recommend skipping the escort #DOSupplies to Auberdine# (overall). This difficult escort leads north to the border of Darkshore and Ashenvale and does not yield any crazy XP/time, but it is worth it if it can be done on the first try. If you do go for it, keep all aggro off of #NPC Delgren the Purifier# as he is very fragile and will die quickly. There are several waves of tough mobs and you have very little opportunity to eat/drink as he runs quick. If you did succeed with it, then turn it in at Maestra's Post (#COORD[26.39]# in Ashenvale, #8 on map) when done."},
      [9] = { str = "Finish obtaining 10 #ITEM Lean Wolf Flanks# from #NPC Ghostpaw Runners# (west in Ashenvale), and do not sell them to a vendor! This is used for a later #DO quest# in Duskwood."},
      [10] = { str = "Go to Astranaar and in the Inn, turn in #INCulling the Threat# (#COORD[37.50]#, #2 on map). Make sure you are repaired/resupplied."},
      [11] = { str = "Go SE to Silverwind Refuge and accept #GETElemental Bracers# (#COORD[50.67]#). Hunters, reminder that there is a HUNTER: #NPC Hunter Trainer# & #NPC Pet Trainer# here at Silverwind Refuge, so get new skill/abilities if you need to.]"},
      [12] = { str = "Just south of you at Mystral Lake do #DOElemental Bracers# : kill/loot the #NPC Befouled Water Elementals# for 5 #ITEM Intact Elemental Bracers#, then use the #ITEM Divining Scroll# quest item to complete the quest."},
      [13] = { str = "Go back to Silverwind Refuge and turn in #INElemental Bracers# (#COORD[50.67]#, #12 on map), SKIP #DOMage Summoner# ."},
      [14] = { str = "Hearth to Auberdine. Make sure you are repaired/resupplied."},
      [15] = { str = "Go out on the long docks at Auberdine and get on the boat to Menethil (#COORD[32.44]#)."},
    },
  },
  [2427] = {
    title = "24-27 Wetlands",
    items = {
      [1] = { str = "Go north near the stables and accept #GETYoung Crocolisk Skins# (#COORD[9.56]#)."},
      [2] = { str = "On the southern part of the town, next to the mailbox/Inn, accept #GETThe Third Fleet# and #GETThe Greenwarden# (#COORD[11.60]#)."},
      [3] = { str = "Go in the Inn next to you and talk to the #NPC Innkeeper# (by the bar, #COORD[11.61]#) to make Deepwater Tavern (Menethil Harbor) your new home. Also from the #NPC Innkeeper#, purchase a #ITEM Flagon of Mead# for #DOThe Third Fleet# ."},
      [4] = { str = "Go upstairs in the Inn (at the middle room) and turn in #INThe Absent Minded Prospector# , accept the next #GET part#."},
      [5] = { str = "Please note that there is a #NPC First Aid Trainer# upstairs in the Inn that you can use to upgrade First Aid."},
      [6] = { str = "Just outside of the Inn, turn in #INThe Third Fleet# (#COORD[11.60]#, #3 on map), accept #GETThe Cursed Crew# ."},
      [7] = { str = "On the east side of town in front of the small house, accept #GETDigging Through the Ooze# (#COORD[12.58]#)."},
      [8] = { str = "Enter the Fortress, make two lefts and at #NPC Neal Allen#, see if you can purchase a #ITEMBronze Tube# and a #ITEM Gyrochronatom# from him (if you haven't yet elsewhere), these are used for later quests. If you did, you can store them in the mailbox by sending them to your ALT and return them back to you."},
      [9] = { str = "Go near the top of the fortress and accept #GETWar Banners# (#COORD[10.57]#)."},
      [10] = { str = "As you exit Menethil Harbor NE on the bridge, accept #GETIn Search of The Excavation Team# (#COORD[11.52]#)."},
      [11] = { str = "Just north of the main path do #DOClaws from the Deep# : kill 12 #NPC Bluegill Murlocs# and kill/loot #NPC Gobbler# (#COORD[18.40]#)."},
      [12] = { str = "SE below the main path, enter Whelgar's Excavation Site (entrance at #COORD[35.42]#).."},
      [13] = { str = "Next go to the path that leads up the mountain side (entrance at #COORD[37.43]#).."},
      [14] = { str = "Go up the path and right before the small cave, accept #GETOrmer's Revenge# (#COORD[38.51]#)."},
      [15] = { str = "Go in the small cave and turn in #INIn Search of The Excavation Team# (#COORD[39.52]#), accept the next #GET part#."},
      [16] = { str = "Next to you on the ground, loot #ITEM Flagongut's Fossil# for part of #DOThe Absent Minded Prospector# ."},
      [17] = { str = "Exit Whelgar's Excavation Site (exit at #COORD[35.42]#, #2 on map).."},
      [18] = { str = "South of the main path at Black Channel Marsh (around #COORD[23.50]#) do #DOOrmer's Revenge# : kill 10 #NPC Mottled Raptors# and 10 #NPC Mottled Screechers#."},
      [19] = { str = "Make sure you are at least 1,900 XP away from level 25 before continuing, grind on any mobs in the immediate area until you are, and work your way to the next step while accomplishing this:"},
      [20] = { str = "SE below the main path, enter Whelgar's Excavation Site (entrance at #COORD[35.42]#).."},
      [21] = { str = "Go to the path that leads up the mountain side (entrance at #COORD[37.43]#).."},
      [22] = { str = "Go up the path and before the small cave, turn in #INOrmer's Revenge# (#COORD[38.51]#), accept the next #GET part#."},
      [23] = { str = "Go in the small cave and accept #GETUncovering the Past# (#COORD[39.52]#). Requires lvl 25."},
      [24] = { str = "Around Whelgar's Excavation Site, do #DOOrmer's Revenge# : kill #NPC Mottled Scytheclaws# and #NPC Mottled Razormaws#. While doing this also do #DOUncovering the Past# : loot the four fragments. The first one is at the bottom of the path, behind a tree, loot the #ITEM Loose Soil# (#COORD[36.42]#) for the #ITEM Neru Fragment#. See next step for the other three:"},
      [25] = { str = "Down in the first hole, loot the #ITEM Ancient Relic# (large vase, #COORD[35.44]#) for the #ITEM Golm Fragment#."},
      [26] = { str = "Just to the west of you, under the bridge, loot the #ITEM Ancient Relic# (slim vase, #COORD[34.44]#) for the #ITEM Modr Fragment #."},
      [27] = { str = "Go south a bit and loot the #ITEM Ancient Relic# (tomb, #COORD[35.47]#) for the #ITEM Ados Fragment#."},
      [28] = { str = "Once done with #DOOrmer's Revenge# , go to the path that leads up the mountain side (entrance at #COORD[37.43]#, #2 on map).."},
      [29] = { str = "Go up the path and before the small cave, turn in #INOrmer's Revenge# (#COORD[38.51]#, #3 on map), accept the next #GET part#."},
      [30] = { str = "Go in the small cave and turn in #INUncovering the Past# (#COORD[39.52]#, #4 on map)."},
      [31] = { str = "West in Whelgar's Excavation Site, go to the path entrance (at #COORD[32.50]#). Go up the path and then do #DOOrmer's Revenge# : kill/loot #NPC Sarltooth# (lvl 29 blue raptor). He's not too hard but be prepared."},
      [32] = { str = "Go to the path that leads up the mountain side (entrance at #COORD[37.43]#, #2 on map).."},
      [33] = { str = "Go up the path and before the small cave, turn in #INOrmer's Revenge# (#COORD[38.51]#, #3 on map)."},
      [34] = { str = "Go north to exit the Whelgar's Excavation Site (exit at #COORD[34.41]#).."},
      [35] = { str = "Make sure #DOThe Absent Minded Prospector# is finished by kill/looting the raptors (around #COORD[24.46]#) for the #ITEM Stone of Relu#."},
      [36] = { str = "Go east to Angerfang Encampment (around #COORD[43.43]#) and do #DOWar Banners# : kill/loot the orcs in the area."},
      [37] = { str = "Go north to the main path's intersection and accept #GETDaily Delivery# (#COORD[50.39]#)."},
      [38] = { str = "You can get resupplied at the #NPC goblin# (#COORD[50.38]#) next to the bridge."},
      [39] = { str = "As you work on the rest of this section start working on #DOYoung Crocolisk Skins# by kill/looting the #NPC Young Wetlands Crocolisk# (found mostly along the rivers)."},
      [40] = { str = "Go east to The Green Belt (past the main path a bit) and turn in #INThe Greenwarden# (#COORD[56.40]#), accept #GETTramping Paws# ."},
      [41] = { str = "Go down south (east of the main path, starting at #COORD[61.58]#) and do #DOTramping Paws# : kill 15 #NPC Mosshide Gnolls# and 10 #NPC Mosshide Mongrels#."},
      [42] = { str = "Go north to The Green Belt and turn in #INTramping Paws# (#COORD[56.40]#, #7 on map), accept #GETFire Taboo# ."},
      [43] = { str = "Go NW past the main path (starting at #COORD[45.35]#) and do #DOFire Taboo# : kill/loot the Mosshide gnolls. Any of them can drop the #ITEM flint#."},
      [44] = { str = "At Ironbeard's Tomb (around #COORD[44.25]#) do #DODigging Through the Ooze# : kill/loot the oozes (any type) until you get #ITEM Sida's Bag# (low drop rate)."},
      [45] = { str = "Go east to The Green Belt (past the main path a bit) and turn in #INFire Taboo# (#COORD[56.40]#, #7 on map), accept #GETBlisters on The Land# ."},
      [46] = { str = "Make sure #DOYoung Crocolisk Skins# is finished by kill/looting the #NPC Young Wetlands Crocolisk# (found mostly along the rivers, #6 on map). Also start working on #DOBlisters on The Land# by killing #NPC Fen Creepers# (stealthed elementals, #13 on map)."},
      [47] = { str = "Hearth to Deepwater Tavern (Menethil Harbor). Make sure you are repaired/resupplied."},
      [48] = { str = "Go upstairs in the Inn (at the middle room) and turn in #INThe Absent Minded Prospector# (#COORD[11.60]#). REMINDER: The #NPC First Aid Trainer# is in the other room upstairs if you need to upgrade First Aid."},
      [49] = { str = "Go west to the docks and turn in #INClaws from the Deep# (#COORD[8.58]#), accept #GETReclaiming Goods# ."},
      [50] = { str = "Go north near the stables and turn in #INDaily Delivery# and #INYoung Crocolisk Skins# (#COORD[9.56]#), accept #GETApprentice's Duties# ."},
      [51] = { str = "Go upstairs in the fortress and turn in #INWar Banners# (#COORD[10.57]#), accept #GETNek'Rosh's Gambit# ."},
      [52] = { str = "At the house east of the fortress, turn in #INDigging Through the Ooze# (#COORD[12.58]#). Make sure you are repaired/resupplied."},
      [53] = { str = "As you exit Menethil Harbor NE on the bridge, turn in #INIn Search of The Excavation Team# (#COORD[11.52]#)."},
      [54] = { str = "Just north of the main path above Menethil Harbor, click on the #ITEM Damaged Crate# (#COORD[13.41]#) to turn in #INReclaiming Goods# , accept #GETThe Search Continues# ."},
      [55] = { str = "Go north a bit to the next small murloc camp and click on the #ITEM Sealed Barrel# (#COORD[14.38]#) on the ground to turn in #INThe Search Continues# , accept #GETSearch More Hovels# ."},
      [56] = { str = "Go north a bit more to the next small murloc camp and click on the #ITEM Half-buried Barrel# (#COORD[14.35]#) to turn in #INSearch More Hovels# , accept #GETReturn the Statuette# ."},
      [57] = { str = "Go up north to the sunken ships and do #DOThe Cursed Crew# : go down in the southern boat and kill/loot #NPC First Mate Snelling# (down at #COORD[14.30]#). Also kill 13 #NPC Cursed Sailors# and 5 #NPC Cursed Marines#. There are more of these mobs up north on the other sunken boat (around #COORD[15.24]#)."},
      [58] = { str = "Just east of you around Sundown Marsh (starting at #COORD[17.26]#, then work east) do #DOApprentice's Duties# : kill/loot #NPC Giant Wetlands Crocolisks#. There is only 13 spawns NW in Wetlands. If you run out of mobs do the next few steps then come back to this area to complete it."},
      [59] = { str = "You can stop at (#COORD[26.26]#) to get repaired/resupplied. NOTE: At this small camp, you can have another chance to purchase a #ITEM Gyrochronatom# and a #ITEMBronze Tube# from the #NPC NPC# there (if you haven't yet elsewhere), these are used for later quests. If you did, you can store them in the mailbox by sending them to your ALT (next time you go to town) and return them back to you."},
      [60] = { str = "Finish #DOBlisters on The Land# : kill 12 #NPC Fen Creepers# (stealthed elementals, see map for locations). Hunters, use HUNTER: Track Hidden to spot the #NPC Fen Creepers# easier.]"},
      [61] = { str = "Go east to The Green Belt and turn in #INBlisters on The Land# (#COORD[56.40]#)"},
      [62] = { str = "Go to the east of you and keep grinding on dragon whelps until you are able to hearth."},
      [63] = { str = "Hearth to Deepwater Tavern (Menethil Harbor) and just outside of the Inn, turn in #INThe Cursed Crew# (#COORD[11.60]#), accept #GETLifting the Curse# ."},
      [64] = { str = "At the west side of the fortress, near the stables, turn in #INApprentice's Duties# (#COORD[8.56]#)."},
      [65] = { str = "On the docks, turn in #INReturn the Statuette# (#COORD[8.58]#)."},
      [66] = { str = "Go to the #NPC Gryphon Master# (#COORD[9.60]#) and fly to Ironforge, Dun Morogh."},
      [67] = { str = "At Ironforge, go to the bank (#COORD[35.60]#) and put the following item into it: #ITEM Dwarven Tinder#. Get the following items out of the bank: (If you have them) 4 #ITEM Minor Mana Potions# and 2 #ITEM Elixirs of Minor Fortitude#. You can also check the AH (#COORD[24.74]#) for these items. Also, from the bank, get your #ITEM Book: The Powers Below# out as well (if you have it)."},
      [68] = { str = "If you have the #ITEM Book: The Powers Below#, go north and turn in #INThe Powers Below# (#COORD[51.6]#)."},
      [69] = { str = "Go east in Ironforge and turn in #INAn Old Colleague# (#COORD[72.52]#), and if you have 4 #ITEM Minor Mana Potions# and 2 #ITEM Elixirs of Minor Fortitude# with you, accept and turn in #INIneptitude + Chemicals = Fun# , SKIP the next #DO part#."},
      [70] = { str = "Get new spells/abilities in Ironforge. Druids, you can get yours soon at Stormwind. Hunters, you can find the HUNTER: Hunter Trainers SE in the Hall of Arms.]"},
      [71] = { str = "Go to the #NPC Gryphon Master# (#COORD[55.48]#) and fly to Stormwind, Elwynn."},
      [72] = { str = "At Stormwind, go into Fragrant Flowers (entrance at #COORD[65.60]# in Stormwind) and from #NPC Felicia Gump#, purchase #ITEM Stormwind Seasoning Herbs# (for a later #DO quest#), and remember to not sell this to a vendor!"},
      [73] = { str = "Go to The Mage Quarter and turn in #INA Scroll from Mauren# (#COORD[43.80]#), SKIP #DODevils in Westfall# ."},
      [74] = { str = "Go west down in The Slaughtered Lamb and accept #GETA Noble Brew# (#COORD[26.79]#)."},
      [75] = { str = "Go to the #NPC Gryphon Master# (#COORD[66.62]#) and fly to Lakeshire, Redridge."},
    },
  },
  [2728] = {
    title = "27-28 Redridge Mountains",
    items = {
      [1] = { str = "Across the bridge on your right, accept #GETBlackrock Menace# (#COORD[33.49]#), (no exclamation mark)."},
      [2] = { str = "At the entrance of the Town Hall, from the Wanted Sign, accept #GETWanted: Gath'Ilzogg# (#COORD[30.46]#)."},
      [3] = { str = "Go in the Town Hall building and accept #GETSolomon's Law# (#COORD[30.44]#)."},
      [4] = { str = "At the entrance of the Inn, click on the Wanted Sign to accept #GETWanted: Lieutenant Fangore# (#COORD[27.46]#)."},
      [5] = { str = "Go in the Inn and talk to the #NPC Innkeeper# (#COORD[27.45]#) to make Lakeshire your new home."},
      [6] = { str = "At the west side of Lakeshire, accept #GETAn Unwelcome Guest# (#COORD[22.46]#)."},
      [7] = { str = "Go west near the mountain cliffs and do #DOAn Unwelcome Guest# : kill/loot #NPC Bellygrub# (#COORD[16.49]#)."},
      [8] = { str = "Go back east to Lakeshire and turn in #INAn Unwelcome Guest# (#COORD[22.46]#, #7 on map)."},
      [9] = { str = "Go east to the main path and follow it NE then NW (to #COORD[44.20]#) while starting on #DOBlackrock Menace# : kill/loot Blackrock mobs (orcs)."},
      [10] = { str = "Follow the path NW to Render's Rock and then enter the cave (entrance at #COORD[33.7]#). Keep hugging the left side of the cave until you get to the water area, and in a little nook, accept and do the escort #DOMissing In Action# : escort #NPC Corporal Keeshan# out of the cave and all the way back to Lakeshire."},
      [11] = { str = "Once back at Lakeshire, by the bridge, turn in #INBlackrock Menace# (it should be done by now) and #INMissing In Action# (#COORD[33.49]#). NOTE: Only accept #DOTharil'zun# and #DOShadow Magic# if you have a group of at least one other player your level with you."},
      [12] = { str = "In town, get repaired/resupplied (#COORD[31.47]#)."},
      [13] = { str = "Go NE in Redridge Mountains and do #DOSolomon's Law# along with #DOWanted: Lieutenant Fangore# : kill/loot the gnolls for the #ITEM pendants# and kill/loot #NPC Lieutenant Fangore# (at #COORD[80.37]#)."},
      [14] = { str = "GROUP ONLY: If you have a group with you of at least one other player your level, then go SW to Stonewatch and do #DOTharil'zun# : on the SE outside of the fortress, kill/loot #NPC Tharil'zun# (lvl 24 elite, #COORD[69.60]#)."},
      [15] = { str = "GROUP ONLY: With the group, go up in the fortress and do #DOWanted: Gath'Ilzogg# : kill/loot #NPC Gath'Ilzogg# (up at #COORD[70.56]#)."},
      [16] = { str = "GROUP ONLY: Before leaving Stonewatch, make sure #DOShadow Magic# is finished by kill/looting the #NPC Blackrock Shadowcasters# in and around the fortress."},
      [17] = { str = "Hearth to Lakeshire. Make sure you are repaired/resupplied."},
      [18] = { str = "Go in the Lakeshire Town Hall building (#COORD[30.44]#) and turn in #INSolomon's Law# and #INWanted: Lieutenant Fangore# . Also turn in (if you did it) #INWanted: Gath'Ilzogg# , otherwise abandon this quest!"},
      [19] = { str = "East at the bridge, turn in (if you did them) #INTharil'zun# and #INShadow Magic# (#COORD[33.49]#, #1 on map)."},
      [20] = { str = "At the other side of the bridge, turn in #INBlackrock Bounty# (#COORD[32.58]#)."},
      [21] = { str = "Take the SW path (#COORD[8.88]#) to exit Redridge Mountains and to get to Duskwood.."},
    },
  },
  [2829] = {
    title = "28-29 Duskwood",
    items = {
      [1] = { str = "Go south to Darkshire and in the first house on your left (#COORD[76.45]#), accept #GETThe Legend of Stalvan# and #GETThe Totem of Infliction# ."},
      [2] = { str = "Just across the path, next to the directional sign, go in the Inn and talk to the #NPC Innkeeper# (#COORD[74.44]#) to make Darkshire your new home."},
      [3] = { str = "In the kitchen of the Inn, accept and turn in #INSeasoned Wolf Kabobs# . PLEASE REPORT TO ME if this quest was available for you in Classic Beta and what level you are."},
      [4] = { str = "As you exit the Inn, on your right, accept #GETThe Night Watch# (#COORD[74.47]#)."},
      [5] = { str = "Just inside the Town Hall next to you, turn in #INThe Legend of Stalvan# (#COORD[72.47]#), accept the next #GET part#."},
      [6] = { str = "Just outside of the house next to the blacksmith shop, accept #GETWorgen in the Woods# (#COORD[75.48]#)."},
      [7] = { str = "Go inside the house next to you and accept #GETRaven Hill# , #GETDeliveries to Sven# and #GETThe Hermit# (#COORD[75.49]#)."},
      [8] = { str = "SE in Darkshire, you will see a gnome dressed in blue and red named #NPC Herble Baubbletump# (#COORD[78.48]#) standing outside, from him purchase a #ITEM Bronze Tube# (if one is not already in your mailbox). From this NPC, you also have another chance to purchase a #ITEM Gyrochronatom# from him (if you haven't yet elsewhere), this is used for a later #DO quest#. If you did, you can store it by sending it to your ALT through the mailbox. These items are also on a respawn timer from him."},
      [9] = { str = "Go just north of the path in Darkshire and from the #NPC Gryphon Master# (#COORD[77.44]#), get the Flight Path."},
      [10] = { str = "Go SE a bit, and up in the small house, accept and then turn in #INLook To The Stars# (#COORD[80.48]#), accept the next #GET part#."},
      [11] = { str = "Go south of Darkshire to the small house and turn in #INLook To The Stars# (#COORD[82.59]#), accept the next #GET part#."},
      [12] = { str = "Go south to Tranquil Gardens Cemetery (around #COORD[80.71]#) and do #DOThe Night Watch# : kill 8 #NPC Skeletal Warriors# and 6 #NPC Skeletal Mages#. Also do #DOLook To The Stars# : kill/loot #NPC Insane Ghoul# (patrols around the cemetery). PLEASE REPORT TO ME if the #NPC Insane Ghoul# patrols around the cemetery or only stays in the church!"},
      [13] = { str = "Go west to The Rotting Orchard (around #COORD[67.66]#) and do #DOWorgen in the Woods# : kill 6 #NPC Nightbane Shadow Weavers#."},
      [14] = { str = "Go NE to Darkshire and in front of the Town Hall, turn in #INThe Night Watch# (#COORD[74.47]#), accept the next #GET part#. Make sure you are repaired/resupplied."},
      [15] = { str = "South of the road, in front of the house turn in #INWorgen in the Woods# (#COORD[75.48]#), accept the next #GET part#."},
      [16] = { str = "In the small house east in Darkshire, turn in #INLook To The Stars# (#COORD[80.48]#), accept the next #GET part#."},
      [17] = { str = "Go west of Darkshire (around #COORD[67.46]#) and do #DOWorgen in the Woods# : kill 12 #NPC Nightbane Dark Runners#."},
      [18] = { str = "Go back to Darkshire and in front of the house south of the road, turn in #INWorgen in the Woods# (#COORD[75.48]#, #4 on map), accept the next #GET part#. Make sure you are repaired/resupplied."},
      [19] = { str = "Go south to Roland's Doom mine (#COORD[73.75]#) and do #DOWorgen in the Woods# : kill 8 #NPC Nightbane Vile Fangs# (outside the mine) and 8 #NPC Nightbane Tainted Ones# (inside the mine).e)."},
      [20] = { str = "Go SW to Vul'Gol Ogre Mound (cave entrance at #COORD[34.78]#) and do #DOLook To The Stars# : south in the cave, kill/loot #NPC Zzarc' Vul# (lvl 33 ogre, #COORD[37.84]#)."},
      [21] = { str = "Go NW to Raven Hill and turn in #INRaven Hill# (#COORD[18.56]#). Accept #GETJitters' Growling Gut# (no exclamation mark)."},
      [22] = { str = "Go north to Raven Hill Cemetery (around #COORD[20.46]#) and do #DOThe Night Watch# : kill 15 #NPC Skeletal Fiends# and 15 #NPC Skeletal Horrors#. These skeletons are found in the southern part of the cemetery. Before leaving the southern cemetery, make sure you have all 10 #ITEM Skeleton Fingers# for #DOThe Totem of Infliction# from the skeleton mobs. Keep the next step in mind:"},
      [23] = { str = "In the northern part of Raven Hill Cemetery (around #COORD[20.46]#) finish #DOThe Totem of Infliction# : kill/loot the ghouls for the #ITEM Ghoul Fangs# and spiders for the #ITEM Vial of Spider Venom#. You can find a lot of #NPC spiders# east of the cemetery. Also make sure you obtain 6 #ITEM Gooey Spider Legs# for a later #DO quest#, and do not sell them to a vendor! They can drop from any spider."},
      [24] = { str = "Go NE in Raven Hill Cemetery and in the small shack, turn in #INThe Hermit# (#COORD[28.31]#). Accept #GETSupplies from Darkshire# ."},
      [25] = { str = "Go west and from #ITEM A Weathered Grave# (#COORD[18.29]#), accept #GETThe Weathered Grave# ."},
      [26] = { str = "Go west a bit more to the small camp by the river and turn in #INDeliveries to Sven# (#COORD[8.34]#). Accept #GETSven's Revenge# ."},
      [27] = { str = "Hearth to Darkshire."},
      [28] = { str = "In the Inn's kitchen, turn in #INJitters' Growling Gut# (#COORD[74.43]#). Also, accept and turn in #INDusky Crab Cakes# . Accept #GETReturn to Jitters# (no exclamation mark)."},
      [29] = { str = "Make sure you are repaired/resupplied."},
      [30] = { str = "As you exit the Inn, in front of the Town Hall, turn in #INThe Night Watch# (#COORD[74.47]#), accept the next #GET part#."},
      [31] = { str = "Go in the Town Hall next to you and turn in #INThe Weathered Grave# (#COORD[73.48]#), accept #GETMorgan Ladimore# ."},
      [32] = { str = "Just outside of the Town Hall (#3 on map), turn in #INMorgan Ladimore# , SKIP #NPCMor'Ladim# . NOTE: The quest reward item #ITEM The Story of Morgan Ladimore# can be destroyed as it's not used for anything."},
      [33] = { str = "Go in the house north of the path in Darkshire (#COORD[76.45]#) and turn in #INThe Totem of Infliction# and #INSupplies from Darkshire# , accept #GETGhost Hair Thread# ."},
      [34] = { str = "In front of the other house across the road, turn in #INWorgen in the Woods# (#COORD[76.48]#), accept the next #GET part#."},
      [35] = { str = "Go in the house next to you and turn in #INWorgen in the Woods# (#COORD[75.49]#)."},
      [36] = { str = "Go east in Darkshire to the small house and turn in #INLook To The Stars# (#COORD[80.48]#)."},
      [37] = { str = "Go south to the small house and turn in #INGhost Hair Thread# (#COORD[82.59]#), accept #GETReturn the Comb# ."},
      [38] = { str = "Go back to Darkshire and in the house north of the path, turn in #INReturn the Comb# (#COORD[76.45]#, #6 on map), accept #GETDeliver the Thread# . Make sure you are repaired/resupplied."},
      [39] = { str = "Go SW to The Yorgen Farmstead and between the two buildings, click on the #ITEM Mound of loose dirt# (#COORD[50.78]#) to turn in #INSven's Revenge# , accept #GETSven's Camp# ."},
      [40] = { str = "Go NW to Raven Hill and turn in #INReturn to Jitters# (#COORD[18.56]#)."},
      [41] = { str = "NE in Raven Hill Cemetery, in the shack, turn in #INDeliver the Thread# (#COORD[28.31]#), accept #GETZombie Juice# ."},
      [42] = { str = "Go SW a bit to the cemetery and do #DOThe Night Watch# : kill 20 #NPC Plague Spreaders#. There is some outside and some down in the catacombs (entrance at #COORD[24.35]#). And there is 4 more spawns around the house (west at #COORD[18.34]#)."},
      [43] = { str = "Go west to the small camp by the river and turn in #INSven's Camp# (#COORD[8.34]#), accept #GETThe Shadowy Figure# ."},
      [44] = { str = "NON HUMANS: Go west to Westfall at Sentinel Hill and go to the #NPC Gryphon Master# (#COORD[56.53]# in Westfall) and get the Flight Path."},
      [45] = { str = "Go west into Westall, and go in the old Town Hall at Moonbrook and click the #ITEM Old Footlocker# to turn in #INThe Legend of Stalvan# (#COORD[41.67]# in Westfall), accept the next #GET part#."},
      [46] = { str = "Hearth to Darkshire. If Hearthstone is still on a cooldown, go NE to Westfall at Sentinel Hill and go to the #NPC Gryphon Master# (#COORD[56.53]# in Westfall, #6 on map) and fly to Darkshire, Duskwood."},
      [47] = { str = "In the Inn, turn in #INZombie Juice# , SKIP #DOGather Rot Blossoms# ."},
      [48] = { str = "Just outside of the Inn, turn in #INThe Night Watch# (#COORD[74.47]#)."},
      [49] = { str = "Go in the house north of the path in Darkshire and turn in #INThe Shadowy Figure# (#COORD[76.45]#), accept #GETThe Shadowy Search Continues# ."},
      [50] = { str = "Go in the Town Hall building and turn in #INThe Legend of Stalvan# (#COORD[72.47]#), accept the next #GET part#. Also turn in #INThe Shadowy Search Continues# , accept #GETInquire at the Inn# ."},
      [51] = { str = "In the Inn, turn in #INInquire at the Inn# (#COORD[74.44]#), accept #GETFinding the Shadowy Figure# . Make sure you are repaired/resupplied."},
      [52] = { str = "Go just NE of the path in Darkshire and from the #NPC Gryphon Master# (up at #COORD[77.44]#), fly to Sentinel Hill, Westfall."},
      [53] = { str = "Go east into Duskwood to Raven Hill and turn in #INFinding the Shadowy Figure# (#COORD[18.56]# in Duskwood), accept #GETReturn to Sven# ."},
      [54] = { str = "Go NW to the small camp by the river and turn in #INReturn to Sven# (#COORD[8.34]#), accept #GETProving Your Worth# ."},
      [55] = { str = "Go east to the NW side of Raven Hill Cemetery and do #DOProving Your Worth# : kill 15 #NPC Skeletal Raiders#, 3 #NPC Skeletal Healers# and 3 #NPC Skeletal Warders# (the warders are only found in the catacombs, entrance at #COORD[16.39]#)."},
      [56] = { str = "Go NW to the small camp by the river and turn in #INProving Your Worth# (#COORD[8.34]#, #8 on map), accept #GETSeeking Wisdom# ."},
      [57] = { str = "Go west to Westfall at Sentinel Hill and go to the #NPC Gryphon Master# (#COORD[56.53]# in Westfall) and fly to Stormwind, Elwynn."},
      [58] = { str = "While questing in Duskwood you may have came across an #ITEM item#, which starts #GETAn Old History Book# (accept it if you can)."},
      [59] = { str = "Go NW to Cathedral Square and from the #NPC Altar Boy# patrolling around (#COORD[40.28]#), accept #GETThe Missing Diplomat# ."},
      [60] = { str = "From #NPC Brother Sarno# in the cathedral, accept #GETTinkmaster Overspark# (#COORD[40.31]#)."},
      [61] = { str = "In the cathedral, turn in #INSeeking Wisdom# (#COORD[39.28]#), accept #GETThe Doomed Fleet# ."},
      [62] = { str = "In Stormwind, get new spells/abilities for your class. Hunters, you can find the Hunter Trainers in HUNTER: Stormwind (at #COORD[62.15]#).]"},
      [63] = { str = "Go NE to Stormwind Keep and turn in #INThe Missing Diplomat# (#COORD[78.25]#), accept the next #GET part#."},
      [64] = { str = "North at the Royal Library, turn in #INAn Old History Book# (#COORD[74.7]#), accept #GETSouthshore# ."},
      [65] = { str = "Go east in Stormwind City (near the entrance of the city) and turn in #INThe Missing Diplomat# (#COORD[73.78]#), accept the next #GET part#."},
      [66] = { str = "Go SE into Elwynn Forest to Lion's Pride Inn and from #NPC Innkeeper Farley# (#COORD[43.66]#) turn in #INThe Legend of Stalvan# , accept the next #GET part#."},
      [67] = { str = "Go upstairs in the Inn, make a right and back between the two beds do #DOThe Legend of Stalvan# : loot the #ITEM Storage Chest# (#COORD[44.66]#)."},
      [68] = { str = "Go NW to Stormwind and upstairs in Trias' Cheese, turn in #INThe Missing Diplomat# (#COORD[73.78]# in Stormwind), accept the next #GET part#."},
      [69] = { str = "Go to the bank (#COORD[57.73]#) and put the following items in your bank: #ITEM Tear of Tilloa#, #ITEM An Undelivered Letter# and #ITEM Sealed Note to Watcher Backus#. And get the following item out of your bank:#ITEM Dwarven Tinder#. And if you have it, get out #ITEM Hillman's Cloak# & #ITEM Bolt of Woolen Cloth# (and remember not to sell these items to a vendor!"},
      [70] = { str = "Go to the #NPC Gryphon Master# (#COORD[66.62]#) and fly to Menethil Harbor, Wetlands."},
    },
  },
  [2930] = {
    title = "29-30 Wetlands",
    items = {
      [1] = { str = "Go just south of Menethil Harbor, to the wrecked boat in the water and from the #ITEM Waterlogged Chest# (#COORD[12.64]#), turn in #INLightforge Iron# , accept #GETThe Lost Ingots# ."},
      [2] = { str = "In the immediate area, do #DOThe Lost Ingots# : kill/loot #NPC Bluegill Raiders#. These mobs extend down south to (#COORD[10.72]#)."},
      [3] = { str = "Go back in the Deepwater Tavern Inn and turn in #INThe Lost Ingots# (#COORD[11.61]#, #1 on map), accept #GETBlessed Arm# ."},
      [4] = { str = "Go north on the docks at Menethil Harbor to get on the boat to go to Auberdine, Darkshore (#COORD[5.57]#)."},
      [5] = { str = "At Auberdine, go to the #NPC Hippogryph Master# (#COORD[36.46]#) and fly to Astranaar, Ashenvale."},
    }
  },
}